### ISSUE TITLE
logout button?

### ISSUE THREAD

**Issue by dcsan** [meteor-useraccounts/core#133]
do you provide a similar styled button to show the users current logged in state, and allow them to logout?

currently I'm using   `+loginButtons` which will show the right state, but its ugly/unstyled...

![image](https://cloud.githubusercontent.com/assets/514002/4847709/00c8ae06-6055-11e4-9bf4-250670dcbb57.png)

**Comment by AJ-Acevedo** [comment]
This worked for me

```js
this.route('signOut', {
    path: '/sign-out',
    onBeforeAction: Meteor.logout
  });
```
