### ISSUE TITLE
Rearraging the form fields order

### ISSUE THREAD

**Issue by fardeem** [meteor-useraccounts/core#135]
First of all, congratulations on the 1.0 release. 

I added a new full name field at the top of my configuration file and want the field to be present at the top. It seems regardless of position in the source code, the new field is added to the bottom of the signup form. Is there any way to fix this?

**Comment by weeger** [comment]
Hi, it works well, but there is some suggestions : 
- Create AccountsTemplates.getField('filedName').after({...}); // And .before()
- Create a weight in float number : 
    * Default field have 1 / 2 / 3
    * Custom field could be inserted with weight:1.5, or 1.25, etc....

It could prevent to have to remove all fields of a form before to insert them again.

Cheers!
