### ISSUE TITLE
Set up github pages for docs with various configuration examples

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#136]
I would be a good thing to go through all closed issues and collect all different configuration strategies suggested to solve particular needs and put them as examples for advanced configuration.

**Comment by fardeemmunir** [comment]
So I'm back. I think a giant readme would be good. Easy to maintain and everything just works

**Comment by splendido** [comment]
Feel free to start with a `.md` file and then we'll see what to do with it ;-)

**Comment by splendido** [comment]
I started to populate the [wiki](https://github.com/meteor-useraccounts/wiki)
