### ISSUE TITLE
How to rearrange fields in the sign-in form?

### ISSUE THREAD

**Issue by willemx** [meteor-useraccounts/core#141]
How can I make sure that the password field comes after (under) the username/email field in the sign-in form?
(BTW: they are in the 'right' order in the sign-up form)
This is what I do:

```
var email = AccountsTemplates.removeField('email');
var pwd = AccountsTemplates.removeField('password');

AccountsTemplates.addFields([
    email,
    {
    _id: 'username',
    type: 'text',
    displayName: 'Username',
    required: true
    }
]);

AccountsTemplates.addField(pwd);
```

But in the sign-in form, the password field comes first, above the username/email field.

**Comment by obiwarn** [comment]
Will there be sth like an ordering number?

**Comment by splendido** [comment]
How would you manage them @obiwarn?
The default fields (i.e. email, password, password_again, etc.)  get number 0, 1, 2, 3, etc...
...the you'd like to add another field at position 2: how to ensure this?

**Comment by obiwarn** [comment]
maybe just like inserting into an array?

AccountsTemplates.insertFieldAtPosition( 3, field)

**Comment by splendido** [comment]
There's one problem: some *special* fields are added at init time, so the position you specify might get wrong.

Do you find the current way for reordering them so ugly?

**Comment by splendido** [comment]
...perhaps a better way could be:

```javascript
AccountsTemplates.addField({
  ...
},
{
  after: 'password'
});
```

but still you'll have to deal with `email` and `password` which are there by default...
