### ISSUE TITLE
How to change subject and text of email verification email?

### ISSUE THREAD

**Issue by vbmark** [meteor-useraccounts/core#149]
I would like to change the default subject "How to verify email address on..." and the text that goes out in the email verification email.

How do I do this?

Thank you.

**Comment by nicooprat** [comment]
This function takes two parameters `user` and `url `, eg.:

````js
Accounts.emailTemplates.verifyEmail.text = function (user, url) {
  return 'Hello '+user.profile.username+', please verify your mail address by visiting this URL: '+url;
};
````

[More in the Meteor docs](http://docs.meteor.com/api/passwords.html#Accounts-emailTemplates)
