### ISSUE TITLE
Change AccountsTemplates to UserAccounts

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#166]
AT remained unchanged by mistake during the transition to useraccounts :(

**Comment by AJ-Acevedo** [comment]
Rude? Not at all. Should be easily for most folks to run a simple find and replace using sed, perl or their text editor.

**Comment by splendido** [comment]
So, no need to put deprecation warnings here and there right? :-)

Tnx for sharing your view @AJ-Acevedo
