### ISSUE TITLE
Add configurable options for 3rd party login services

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#179]
from the discussion in #178 it turns out that at the moment the only way to pass some extra options to `Meteor.loginWith<service>` is adding the package `accounts-ui` and configure them with 

Actually it is possible to configure these options with [Accounts.ui.config](http://docs.meteor.com/#/full/accounts_ui_config) and get them passed to `Meteor.loginWith<service>` thanks to see [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js#L83-90)

A better solution would be to have these options be configured directly on AT

**Comment by wollardj** [comment]
:+1:

**Comment by adrianmc** [comment]
I can't get this to work. I tried putting this in the lib folder but it doesn't seem to work.

```
if (Meteor.isClient) {
    Accounts.ui.config({
      requestPermissions: {
        facebook: ['email','user_groups']
      }
    });
}
```

**Comment by omeid** [comment]
Why is this closed? I would like to have this feature.

**Comment by splendido** [comment]
I closed it because there's a (very triky) way to get around the problem
and also because I'm implementing it on v2.0...
See [here](https://github.com/meteor-useraccounts/oauth/blob/master/src/events.js#L30)

I'm sorry if closing this way was rude...

**Comment by Pushplaybang** [comment]
any news on v2.0, and this feature in particular?
