### ISSUE TITLE
Modal forms for sign-in / sign-up

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#180]
something to design as a plugin-package to be added with something like

```shell
meteor add useraccounts:modal
```

should be something on the lines pioneered by @zachdixon and @BradRyan as stated in #153

**Comment by BradRyan** [comment]
@fpoirier1, Thanks for working on the submitHook... worked perfectly.  I was working on a new app and this was the solution for redirecting after successfull sign in... love my sign in modals :).  Without it, AccountsTemplates.avoidRedirect = true was preventing me from redirecting, even though I was setting it to false on user logout.  I guess the redirect function was firing before my Tracker function could set it to false.

In case anyone else is interested in modals for sign-in, I'll share my setup.  In my navbar, I have a sign in button that show's a modal and set the session var 'currentModal' to true, which I fetch in tracker.autorun to prevent page redirect behind the modal.  

In Tracker.autorun:
```
Tracker.autorun(function() {
if (Meteor.userId()) {
      Session.set('currentModal',false);
      $('#BetaSigninModal').modal('hide');
  }
AccountsTemplates.avoidRedirect = Session.get('currentModal');
}
```
Navbar event handler:
```
Template.AdminLayout.events({
	'click #signIn': function() {
               Session.set('currentModal',true);
               $('#BetaSigninModal').modal('show');
	}
});
```

In my at_config.js file: 
```
var mySubmitFunc = function(error, state){
  if (!error) {
    if (state === "signIn") {
      // Successfully logged in
      Router.go('/admin/account');
      $('#signinModal').modal('hide');
    }
  }
};

AccountsTemplates.configure({
    onSubmitHook: mySubmitFunc
});
```

Thanks again for the package!

**Comment by splendido** [comment]
@BradRyan thanks for sharing!
Lets consider this when I'll be on v2.0 packages

Cheers

**Comment by BradRyan** [comment]
Sounds good!  Just a quick update before I forget.  I noticed a bug after my page would reroute on sign-in.  I ended up having to wait for the modal to close before calling Router.go, otherwise not all of the modal classes would clear before routing.  As a result, my body appeared to be frozen, but the modal-open class had persisted.  I update my code above with the fix.

**Comment by splendido** [comment]
@BradRyan, lets have a look at the [new client hooks](https://github.com/meteor/meteor/blob/devel/History.md#meteor-accounts) introduced with Meteor@1.0.4!

**Comment by splendido** [comment]
See the [modal-forms](https://trello.com/c/uQ0wipnG/14-modal-forms) card on Trello

**Comment by ipstas** [comment]
AccountsTemplates.avoidRedirect = true;
Can we please add it to the Readme? I had to dig it out, when it was so simple
