### ISSUE TITLE
Stuck Installing on "selecting package versions"

### ISSUE THREAD

**Issue by jonquixote** [meteor-useraccounts/core#183]
I have been using meteor for a while. i know everything is (or has been) set up properly. installing other packages works fine. i cannot install any useraccounts packages. i tried core first. it keeps getting hung up in the install. terminal reads "selecting package versions". the cursor to the right is just spinning. any suggestions??

**Comment by viellepeau** [comment]
Hi,

I have just installed meteor on Windows 8.1
I created a new meteor project (meteor create hello)
And then in the hello folder, when I type meteor command, I have the following result :

=> Started proxy.
   Selecting package versions                |

Stuck forever! I cannot even stop with Ctrl-c or Ctrl-z.
Same result if I use meteor-useraccounts boilerplates.
What do you recommend ? Thank you for your help

**Comment by splendido** [comment]
Have you also added some useraccounts packages to your hello project?

**Comment by splendido** [comment]
...sorry, I wrote to quickly.
In case you get the same problem with a *dummy* project, I'd say is something which has more to do with the network connection rather than with the packages you're using.

Have you solved it by chance in the meanwhile?
