### ISSUE TITLE
Change email

### ISSUE THREAD

**Issue by timothyarmes** [meteor-useraccounts/core#193]
Could we please include a form to allow the user to change their email address?

**Comment by dstollie** [comment]
Lets reopen this issue, think out a way to handle email management and than Im willing to start on this. I really need this "basic" functionality and contributing to the meteor community is something I have to do more.

**Comment by splendido** [comment]
Hi @dstollie,
actually this can be sfely implemented outside useraccounts.
I see it this way:
- once a user has logged in to the application, she should have access to a *settings* page where she can add or remove email addresses.
- the list of currently registered email addresses is avaiable from `Meteor.currentUser().emails` (provided that you published it to the client and the client subscribed to it...)
- by clicking some other buttons/elements the user might trigger the call to a couple of server-side methods like `addEmailAddress` and `removeEmailAddress`
- on the server side, once all checks for the case passed, these two methods has nothing too complicated to do: perform some operation on the current user's `field` array
- optionally, in case it is needed, send out a verification email with `Accounts.sendVerificationEmail`

I see it difficult for useraccounts to be able to provide a template to suite all's needs in terms of layout and design.

I hope this might give some pointer to get you started on this.
Please le me know if you need more help!

**Comment by dstollie** [comment]
Thanks @splendido, I hate to have lots of dependencies in my meteor project that's why I thought putting this functionality in useraccounts, but I will create a seperate package for this. Thanks!

**Comment by hrhitesh** [comment]
Hello @dstollie , did you implemented this functionality in useraccounts?
