### ISSUE TITLE
Allow users to request verification email on login forbidden 

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#197]
In case `ensureEmailVerification` is set, there's no way at the moment for a user to ask another verification email.
This could be dome on the same login form (perhaps by adding another internal state?) by switching the *login* button to something like *send email again*.

This issue was originally raised by @timothyarmes with #195.

In case `ensureEmailVerification` is not set, sending another verification email is just a matter of calling `Accounts.sendVerificationEmail` which can be easily done from a *user profile page* by devs.

**Comment by dalgard** [comment]
+1

Went live with a big system today and only now realize that this is missing. Gonna give the company a heap of support calls if I don't add this feature today ;)

**Comment by splendido** [comment]
Yep, reset email works almost like the verification email...
Unfortunately this is not a very quick thing to be added :(

As a work around you might want to add another link below the `atForm` saying something like *lost your verificatoin email?* and redirecting to the reset password page...
Could this be a feasible solution?

In case, I'll be happy to explain how to achieve this should you need help!

**Comment by dalgard** [comment]
I don't, it doesn't see *that* hard to do?

- Add a link or button inside the "you need to verify your email" message (using template-extension or whatever technique I can)
- Show a form looking like the "forgot my password" form
- On send, do the same thing as `useraccounts` does when a new user is created in regard to sending the verification e-mail (copy-paste code)

**Comment by dalgard** [comment]
Actually, I would probably just add a link under the form like you suggest.

**Comment by splendido** [comment]
all you have to do on the server side is call [Accounts.sendVerificationEmail](https://docs.meteor.com/#/full/accounts_sendverificationemail).

So I guess that when you get the "you need to verify your email" message you could add another button below "Login" (to say one) and call a custom server-side method taking the username or email the user entered into the form, in turn this method should call `Accounts.sendVerificationEmail`.


you should also be able to use a submit hook to test this particular case (not tested!!!!):

```javascript
var myOnSubmitHook = function(error, state){
  if (error.details == verifyError and status == 'signIn') {
    // add a button here
  }
};

AccountsTemplates.configure({
  onSubmitHook: myOnSubmitHook
})
```

Here is the error thrown [error](https://github.com/meteor-useraccounts/core/blob/c963bbb5fbeab88e9398404ab002360f48c47eec/lib/server.js#L112)

**Comment by dalgard** [comment]
Thanks :+1:

**Comment by splendido** [comment]
any news?

**Comment by dalgard** [comment]
I've actually finished the task – everything worked out fine, just as expected :) Unfortunately, I don't have time to extend the documentation and send a pull request until maybe later today or tomorrow.

There's also the question about updating the UI libraries, of course.... I'm using Semantic UI, but I don't suppose it would be too difficult to make this tiny adjustment to the others, too.

There's also my unfinished business with the neutral message I added... ;)

**Comment by splendido** [comment]
Don't worry, no need to rush!
priority goes to your business ;-)

Glad it worked, I'm curious to see it in action ;-)

Tnx!

**Comment by dalgard** [comment]
It's more or less made up of of already existing code copied and used where it makes sense for this scenario. The code is quite easy to navigate – good work!
