### ISSUE TITLE
 How to localize "Minimum required length:" error message?

### ISSUE THREAD

**Issue by willemx** [meteor-useraccounts/core#200]
What is the recommended way to do this?
(...and also for "Required Field")

**Comment by dalgard** [comment]
It is possible to translate those strings by using the exact text in English as the key in the root of the t9n map (incl. the number). Like this:

```javascript
T9n.map("da", {
  "Required Field": "Udfyld venligst",
  "Invalid email": "Ugyldig e-mail-adresse",
  "Minimum required length: 6": "Skal være på mindst 6 tegn",
  ...
});
```

**Comment by splendido** [comment]
Good catch @dalgard!
...I didn't realize those error messages are used as T9n keys the very same way as all the others errors
:+1:

**Comment by cosio55** [comment]
Im trying to set it up like:
```
T9n.map('es', {
  "Required Field" : "Este campo es requerido",
  "Minimum required length: 6": "Minimum Required : 6",
});
```
And the 'Required Field' is working but the 'Minimum required length: 6' is not, any ideas why?

**Comment by dalgard** [comment]
Well, if you've set a different minimum required length than 6? ;)

**Comment by cosio55** [comment]
@dalgard  You were absolutely right, thank you very much!
