### ISSUE TITLE
Configure custom url for sendEnrollmentEmail

### ISSUE THREAD

**Issue by rootedsoftware** [meteor-useraccounts/core#203]
My meteor app runs inside a subdirectory. Something like https://domain.com/give

When the enrollment email is sent the /give part isn't included so clicking the link won't get the user to the right domain. 

Any idea how I might add the /give to the URL that is sent out?

**Comment by fix** [comment]
Hi Here,
I am just getting mad about this :)
I have just tried whatever config i have found on the related issues here but i can't get the verify email sent with the right url. Always have this /#/ in the url. Any hint?

**Comment by fix** [comment]
Ok answering myself : put the code on server side, not on client side

Cheers

**Comment by splendido** [comment]
This might also be of interest for #277 I guess

**Comment by mitar** [comment]
I think the issue is if you are calling configuration only one the client. At least that was the issue for me.

Maybe that is unclear in the documentation? Or I missed something there.

**Comment by serkyen** [comment]
Can someone please help me with how to handle the enrollment link? I have not been able to find anything in docs.

After a user clicks the link in the email, I bring them to a page where I have to do something with the token. Is there an inbuilt Accounts function I need to call upon landing on this page?

For example, for email verification, I used this...
```
Accounts.verifyEmail( this.props.token, ( error ) =>{
      if ( error ) {
       this.setState({msg: error.reason});
      } else {
        this.setState({msg:'Email verified! Thanks!'});
      }
  });
```

What do I user for enrollment?
Is it `Accounts.onEnrollmentLink((token, done) => {}` ?

I understand that maybe I need to have a password field and allow the user to enter their password, but how do I ensure the token is valid and that the right account gets updated?

Thanks
