### ISSUE TITLE
Allow HTML in display names

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#205]
See https://github.com/meteor-useraccounts/bootstrap/issues/16

This is another improvement to be possibly considered!
...to be added to the list of #172

**Comment by JoshuaNovak919** [comment]
Would love to be able to add a lock icon like so:

```
texts: {
  button: {
      signIn: "<i class=\"fa-lock\"></i> Log In"
  }
}
```

**Comment by splendido** [comment]
This is now possible using custom templates for input fields: see #273 and [this example](https://github.com/meteor-useraccounts/core/issues/273#issuecomment-73137378)
