### ISSUE TITLE
Modulus url instead of custom url appears with password reset

### ISSUE THREAD

**Issue by LynnRas** [meteor-useraccounts/core#206]
The email link for reset password is the modulus url for my app
http://newkitsmart-21395.onmodulus.net/reset-password/xxxxxxxxxxxx.  It's not directing to the custom url:   http://kitsmart.com/reset-password/xxxxxxxx. 
The modulus url continues after sign in. 

Any suggestions?

**Comment by mmazloum** [comment]
Does this mean I can set the custom domain as ROOT_URL on modulus after the app is deployed ?
