### ISSUE TITLE
MAIL_URL warning

### ISSUE THREAD

**Issue by shrop** [meteor-useraccounts/core#210]
I don't think this is a major issue, but I am getting the error below in my server output:

`W20141219-21:50:39.649(-5)? (STDERR) [AccountsTemplates] WARNING: showForgotPasswordLink set to true, but MAIL_URL is not configured!`

`MAIL_URL` is set. I confirmed this with the new `meteor shell` :)

I am wondering if it has to do with the order Meteor loads the files in. My AT config is in `lib/at_config.js` and my `MAIL_URL` is setup in `server/smtp.js`

I think email is working just fine though. I get the verify email email.

**Comment by msamoylov** [comment]
I'm having exactly the same issue. Most probably ```lib/config/at.js``` is processed before ```server/config/smtp.js```

**Comment by shrop** [comment]
@splendido @deetergp and I are sourcing env.sh and then running meteor. That puts things in the right order and works for us. May still be good find a fix when doing smtp config in the JS code. Thanks!

**Comment by splendido** [comment]
If you think having this warning creates more problems than benefits, we might also think to get rid of it...
What's your view?
