### ISSUE TITLE
wrap in custom html tags?

### ISSUE THREAD

**Issue by mattkrick** [meteor-useraccounts/core#212]
I'd like to wrap the inputs in polymer tags to keep with my theme. How would you suggest I do this? Is it possible to do a jquery wrap or html injection? Anything more dynamic?

Example:

```
<paper-input>
  <input type="email" id="at-field-email" ...>
</paper-input>
```

**Comment by splendido** [comment]
@mattkrick any new about the material design?
...lets continue on this with #259

**Comment by Maxhodges** [comment]
OK I added the package `aldeed:template-extension`

and added a new template
`<template name="WREatPwdFormBtn">
  <button type="submit" class="at-btn submit btn btn-lg btn-block btn-primary {{submitDisabled}}" id="at-btn">
      {{buttonText}}
  </button>
</template>`

and added this to client code
`Template.WREAtPwdFormBtn.replaces("atPwdFormBtn");`

any idea how to resolve
error `Uncaught TypeError: Cannot read property 'replaces' of undefined in WREAtPwdFormBtn.js`
