### ISSUE TITLE
override Login forbidden

### ISSUE THREAD

**Issue by Hareramrai** [meteor-useraccounts/core#216]
Hi, 

Can anyone help me to override the default authentication error message "Login forbidden" to "Incorrect Login" . 

Thanks,
hare

**Comment by MarcioAntonioRezende** [comment]
I experimented this same error using semantic:accounts-ui. I just remove the pack and greats news... it work...

**Comment by v3rron** [comment]
Still have the same issue with semantic-ui package

**Comment by splendido** [comment]
which error/issue?
This was about changing the appearing text... wasn't it?
