### ISSUE TITLE
state='signUp' not working after meteor 1.0.2 upgrade

### ISSUE THREAD

**Issue by hsribei** [meteor-useraccounts/core#217]
I have a [template](https://github.com/obvio171/rideboard/blob/master/client/application/templates/home.html#L109) that uses `{{> atForm state='signUp'}}` to display a signup form on the landing page.

It worked perfectly until I upgraded to meteor 1.0.2 (from 1.0.1). Now it only displays the login form, without even a link to the signup form ('entrar' == 'log in'):

![mural_de_caronas](https://cloud.githubusercontent.com/assets/4315/5554287/3fda7616-8c32-11e4-8ab7-3fbad45cc6b8.png)

Any idea what I can do to fix this, please? Thanks!

**Comment by Pierre-Ferreira** [comment]
Hi there.
I am getting sort of the same issue.
When  doing {{> atForm state='signUp'}} my social logins shows register, but the email login shows 'Sign In'. 
![screenshot 2015-06-25 10 18 57](https://cloud.githubusercontent.com/assets/8502392/8350040/4c48a664-1b22-11e5-8cf6-3c9298c0914c.png)

I am using:
useraccounts:bootstrap@1.3.2
useraccounts:core@1.3.2
Meteor 1.1.0.2

Please help. Thank you!

**Comment by splendido** [comment]
`Sign in Text` is not the default text, so I guess you've changed it somehow.
In case this is the case, please have a look [here](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#button-text) to see how to specify different text for different states.

Let me know
