### ISSUE TITLE
Continuous Validation Improvements

### ISSUE THREAD

**Issue by ianserlin** [meteor-useraccounts/core#222]
Small enhancement: Don't give live *negative* feedback on an input until the user has blurred it once, meaning they thought they were done with that input.

Current: Live validation + negative feedback immediately shows an error color when entering an email address into the input the first time, e.g. after typing the "u" part of "user@example.com"

**Comment by splendido** [comment]
From your silence I guess you managed to solve this.

Let my know if I'm wrong ;-)
