### ISSUE TITLE
form doesn't render when logged in

### ISSUE THREAD

**Issue by dcsan** [meteor-useraccounts/core#223]
I have a template with 

```
    +atForm(state='signIn')
```

however if the user is logged in, nothing shows up in that form. no facebook button or anything...
also no error messages.
while looking at the page if I type  `Meteor.logout()` in the console, then all the form items appear.

is this expected behavior?

the reason is that I have a "guest" user account, which is a kind of temporary login. 
While "guest" I want to redirect the user to a login form and have them login with FB.

is there a way to show the form even when the user is logged in?

**Comment by splendido** [comment]
Hey @dcsan,
have you tried with the above trick?

can we close here?

**Comment by dcsan** [comment]
havent tried yet but i will make a memo, so feel free to close. thanks for all your help!
