### ISSUE TITLE
changePwd form password field label and placeholder

### ISSUE THREAD

**Issue by msamoylov** [meteor-useraccounts/core#224]
I thinks that's too ambiguous and the 'password' field should be changed to 'new password'. So, there will be 'current password' and 'new password' fields. 

Does it make any sense?

![screenshot 2015-01-01 21 34 00](https://cloud.githubusercontent.com/assets/106813/5593107/31a4c0ca-91fe-11e4-9213-347b4960594c.png)

**Comment by splendido** [comment]
Yep!
Lets keep this open so that it will be fixed with version 2.0....

Tnx!

**Comment by splendido** [comment]
Hey @msamoylov,
I'm sorry I gave you a wrong answer.

The default password field works correctly:

![newpassword](https://cloud.githubusercontent.com/assets/6148980/5880483/3bab7a40-a339-11e4-8e39-427df23b6fe6.png)

So I guess you changed your password field configuration by removing the old one and adding your customized version.
Please make sure you include the correct options for the `displayName` and `placeholder`: lets have a look at [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L304-313) specifying different texts, for the different states...

Let me know if you manage to configure it right!
Tnx!
