### ISSUE TITLE
ensureSignedIn not working with two level URL

### ISSUE THREAD

**Issue by AJ-Acevedo** [meteor-useraccounts/core#225]
I have the following code.

```js
Router.onBeforeAction(AccountsTemplates.ensureSignedIn, {
    only: ['dashboard', 'profile']
});

Router.route('/dashboard', function () {
  this.render('dashboard');
});

Router.route('/dashboard/profile', function () {
  this.render('profile');
});
```

When I navigate to /dashboard I receive the 'Must be logged in' message as expected. But when I visit /dashboard/profile the template renders.

**Comment by splendido** [comment]
It seems you did not define the name `profile` for your `/dashboard/profile` route.
See the [named routes](EventedMind) documentation.
Am I correct?

**Comment by AJ-Acevedo** [comment]
@splendido Yup! You are correct. I was missing the named route.
