### ISSUE TITLE
Consider updating signature for configureRoute to match new Iron.Router style

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/core#226]
In newer versions of Iron.Router, routes are defined with the path as the first parameter instead of the name. See the comments here:

```javascript
Router.route('/post/:_id', {
  // The name of the route.
  // Used to reference the route in path helpers and to find a default template
  // for the route if none is provided in the "template" option. If no name is
  // provided, the router guesses a name based on the path '/post/:_id'
  name: 'post.show',

  // To support legacy versions of Iron.Router you can provide an explicit path
  // as an option, in case the first parameter is actually a route name.
  // However, it is recommended to provide the path as the first parameter of the
  // route function.
  path: '/post/:_id',
```

**Comment by splendido** [comment]
...mmm, the thing is I'm using the first mandatory parameter as the route 'code' to check if the configuration attempt is for a *valid* route.

See [here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L423)

Put the other way, there will be no assurances to get also the route 'code'.
The method `configureRoute` is heavily connected to the `Router.route` one, but it's functioning is a bit different.

What would you suggest considering this?

**Comment by dalgard** [comment]
It's a good point, I guess I'll give it some thought... Maybe I'll return. Thanks for the quick reply and awesome work.
