### ISSUE TITLE
Sign Up form submit redirect

### ISSUE THREAD

**Issue by doubletaketech** [meteor-useraccounts/core#227]
Is there an way to configure a route for the signup button submit?  I want to take the new user directly to my another route after they sign up.

Thanks,
Don

**Comment by splendido** [comment]
Yeah, sure!
Lets have a look at the [Routing](https://github.com/meteor-useraccounts/core#routing) section of the docs.

Basically, you should setup your sign up route with something like this:

```
AccountsTemplates.configureRoute('signUp', {
    redirect: '/user-profile',
});
```

Unless you whish to specify also the template to be used, or other things as explained in the docs.

**Comment by doubletaketech** [comment]
perfect.  Thanks!  I saw this section of the docs, but missed that it can apply to after the submit of the registration form.

I'll give it a try.

Appreciate the help.
Don

**Comment by doubletaketech** [comment]
redirect works great. Thanks.

```
AccountsTemplates.configureRoute('signUp', {
    redirect: '/editProfile'
});
```
Any idea why the redirect doesn't pick up the global layout?
I tried hardcoding 'masterLayout' in the configureRoute and also in AccountsTemplates.configure defaultLayout, but neither worked.
```
Router.configure({
    layoutTemplate: 'masterLayout',
    loadingTemplate: 'loading',
    notFoundTemplate: 'pageNotFound',
    yieldTemplates: {
        navbar: {to: 'navbar'},
        leftMenu: {to: 'leftMenu'},
        rightMenu: {to: 'rightMenu'}
    }
});
```
I still need my navbar to be at the top after redirect.

Any ideas?

**Comment by doubletaketech** [comment]
Thanks! Redirect works great!
