### ISSUE TITLE
Invite code verification field not working

### ISSUE THREAD

**Issue by sdybskiy** [meteor-useraccounts/core#228]
I have `accouts.js` running on client/server to initiate a new field
```
AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(val){
    Meteor.call('validateInvite', val, function (error, valid) {
      if (error) {
        console.log(error.reason);
        AccountsTemplates.state.form.set('invite', error.reason);
      } else {
        console.log(valid);
        if (valid) {
          AccountsTemplates.state.form.set('invite', false);
        } else {
          AccountsTemplates.state.form.set('invite', 'Invalid Invitation code. Please email hi@dmno.io');
        }
      }
    });
    return true;
  },
  errStr: 'Invalid Invitation code.',
});
```
The `Meteor.call('validateInvite', val);` method is here 
```
validateInvite: function (invite) {
    var item = Invites.findOne({_id: invite});
    if (typeof item == 'undefined'){
      throw new Meteor.Error("invite-error", "Invite is not valid!");
    } else {
      console.log('validation passed');
      return true;
    }
  }
```

When I take an invite from the Mongo Collection, the field isn't getting validated. This bug isn't there when I'm using the `@1.1.1` version, but i'd like to update to the current one

**Comment by splendido** [comment]
mmm, it's weird it's working on v1.1.1 and not on the current one, I don't remember having changed validation stuff since then.

Have you managed to trace down at wich point things stop working?
Inside the callback or even before on the server?

**Comment by sdybskiy** [comment]
@splendido what's weird is I'm getting the server console log `validation passed` so the method returns the correct value as it should. However `Meteor.call('validateInvite', val);` returns `undefined` -> but maybe that's because I'm testing it on the console. 
Is there a way to avoid the `function (error, valid)` callback ?

**Comment by splendido** [comment]
oh, no!
methods always return `undefined` on the client!!!
You MUST pass in a callback to get the result...

I'd say your first example is correct....

**Comment by sdybskiy** [comment]
@splendido so what's my error? :disappointed:

**Comment by splendido** [comment]
do you have a public repo for it?

**Comment by sdybskiy** [comment]
@splendido unfortunately i don't. i can provide code you might think can be interfering

**Comment by sdybskiy** [comment]
@splendido i believe `AccountsTemplates.state.form.set('invite', false);` is giving me an error: 
```
Exception in delivering result of invoking 'validateInvite': TypeError: Cannot read property 'form' of undefined
I20150109-16:17:42.323(-5)?     at app/lib/accounts.js:73:34
I20150109-16:17:42.324(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150109-16:17:42.325(-5)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150109-16:17:42.325(-5)?     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1528:1)
I20150109-16:17:42.325(-5)?     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1455:1)
I20150109-16:17:42.326(-5)?     at [object Object].AccountsTemplates.addField.func (app/lib/accounts.js:66:12)
I20150109-16:17:42.326(-5)?     at [object Object].Field.validate (packages/useraccounts:core/lib/field.js:201:1)
I20150109-16:17:42.326(-5)?     at packages/useraccounts:core/lib/methods.js:52:1
I20150109-16:17:42.326(-5)?     at Array.forEach (native)
I20150109-16:17:42.327(-5)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
```

**Comment by sdybskiy** [comment]
@splendido figured out the issue, not sure how to solve it. Since `Meteor.call` has a callback, it runs asynchronously so the actual `func` first returns `true` and then does runs the method. However, I'm boggled as to why a version update of your package is causing this since I'm using the same Meteor version in both cases.

**Comment by splendido** [comment]
Yeah, the asynchronous run is mandatory...

I'll try to have a better look at this when I get some time.
Lets keep this open for now!

**Comment by sdybskiy** [comment]
@splendido any news? :smile:

**Comment by splendido** [comment]
Hi there,
sorry for the delay!


I've just followed the `Custom validation` paragraph inside the [Form Fields Configuration](https://github.com/meteor-useraccounts/core#form-fields-configuration) section.

This is what I tried with success:

```javascript
AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, valid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (valid) {
            self.setSuccess();
          }
          else {
            self.setError("Invalid Code");
          }
        }
        self.setValidating(false);
      });
        return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

**Comment by sdybskiy** [comment]
@splendido awesome! thank you very much!

**Comment by sdybskiy** [comment]
@splendido weird :confused: now confirmPassword is buggy, saying passwords don't match when I make sure they are the same.

These are my options and I have it set up in `lib/accouts.js` and after the configuration, in the same file, i put the above code for `addField`. 

```
// Options
AccountsTemplates.configure({
  //defaultLayout: 'emptyLayout',
  showForgotPasswordLink: true,
  overrideLoginErrors: true,
  enablePasswordChange: true,
  sendVerificationEmail: false,

  //enforceEmailVerification: true,
  confirmPassword: true,
  //continuousValidation: false,
  //displayFormLabels: true,
  //forbidClientAccountCreation: false,
  //formValidationFeedback: true,
  //homeRoutePath: '/create-transfer',
  showLabels: false,
  showAddRemoveServices: true,
  //showPlaceholders: true,
  termsUrl: '/tos',
  privacyUrl: '/privacy',
  continuousValidation: true,
  negativeValidation: true,
  positiveValidation: true,
  negativeFeedback: true,
  positiveFeedback: true,
  texts: {
    errors: {
      mustBeLoggedIn: "Please login to use the service",
    }
  }
});
```

**Comment by splendido** [comment]
So if you add the asynchronous validation password matching stops working??

**Comment by sdybskiy** [comment]
@splendido im going to assume that's the case since i haven't touched any other settings. also if i set `confirmPassword: false`, and fill the 3 fields in, the invite field get's validated but i still get `Validation Errors` error from the form

**Comment by splendido** [comment]
Ok, it's my fault! :(

```javascript
if (Meteor.isServer){
  Meteor.methods({
    validateInvite: function (invite) {
      Meteor._sleepForMs(500);
      console.log("invite");
      var invalid = false;
      //var invalid = true;
      return invalid;
    }
  });
}

AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

this is working ok also with password confirmation.


The thing is the logic for the return value is the other way around:

- true -> there are errors
- false -> correct value
- undefined/null -> no validation performed

So when you first `return` right after having called the validation method on the client, there's no validation state set for the field. You set it later with `self.setSuccess();` or `self.setError("Invalid Code");`.

When you are on the server the result of the return value of the validation method (not the one you get on the callback, there are no callback on server-side methods!) is taken as the validation result.

I'm sorry to have provided you with a wrong example, but it's a bit of time I wrote this and had no changes to use it recently.

Let me know whether this fixes everything also on your side!

**Comment by sdybskiy** [comment]
@splendido thanks for your speedy replies. I adjusted my stuff and I am still getting a password match error :/ 

My `/server/methods.js` 

```
Meteor.methods({
  validateInvite: function (invite) {
    var item = Invites.findOne({_id: invite});
    if (typeof item == 'undefined'){
      throw new Meteor.Error("invite-error", "Invite is not valid!");
    } else {
      console.log('validation passed');
      // return true;
      var invalid = false;
      return invalid;
    }
  }
});
```

My `/lib/accouts.js`

```
//Routes
AccountsTemplates.configureRoute('changePwd');
AccountsTemplates.configureRoute('enrollAccount');
AccountsTemplates.configureRoute('forgotPwd');
AccountsTemplates.configureRoute('resetPwd');
AccountsTemplates.configureRoute('signIn', {
    name: 'sign-in',
    path: '/sign-in',
    template: 'sign-in',
    redirect: '/',

});
AccountsTemplates.configureRoute('signUp', {
    name: 'sign-up',
    path: '/sign-up',
    template: 'sign-up',
    redirect: '/',

});
AccountsTemplates.configureRoute('verifyEmail');

// Options
AccountsTemplates.configure({
  //defaultLayout: 'emptyLayout',
  showForgotPasswordLink: true,
  overrideLoginErrors: true,
  enablePasswordChange: true,
  sendVerificationEmail: false,

  //enforceEmailVerification: true,
  confirmPassword: true,
  //continuousValidation: false,
  //displayFormLabels: true,
  //forbidClientAccountCreation: false,
  //formValidationFeedback: true,
  //homeRoutePath: '/create-transfer',
  showLabels: false,
  showAddRemoveServices: true,
  //showPlaceholders: true,
  termsUrl: '/tos',
  privacyUrl: '/privacy',
  continuousValidation: true,
  negativeValidation: true,
  positiveValidation: true,
  negativeFeedback: true,
  positiveFeedback: true,
  texts: {
    errors: {
      mustBeLoggedIn: "Please login to use the service",
    }
  }
});

Meteor.startup(function () {
  // AccountsTemplates.init();
});

AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

Can you just confirm I'm not missing anything important?

**Comment by splendido** [comment]
Try with this:

```javascript
Meteor.methods({
  validateInvite: function (invite) {
    return !Invites.findOne({_id: invite});
  }
});
```

**Comment by sdybskiy** [comment]
invite validation works but password validation still doesn't :( @splendido

**Comment by splendido** [comment]
I've tried it on the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) and simply returning true or false from the validation method worked fine also with password confirmation!

Could you give it a try too?

```shell
git clone https://github.com/meteor-useraccounts/boilerplates.git
cd boilerplates/semantic-ui
vim lib/config/at_config.js ...

meteor
```

When you edit the config file paste the following at the beginning:

```javascript
if (Meteor.isServer){
  Meteor.methods({
    validateInvite: function (invite) {
      Meteor._sleepForMs(500);
      //var invalid = false;
      var invalid = true;
      return invalid;
    }
  });
}

AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

I swear this works for me! ;-)

**Comment by sdybskiy** [comment]
@splendido weird... i removed 

```
AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

and the password validation still says pw's don't match :/. im using

```
useraccounts:bootstrap@1.4.1
useraccounts:core@1.4.1
```

Any clue why?

**Comment by splendido** [comment]
Have you tried with the boilerplates?

...if you have a public repo for this, I might try to have a look at it!

**Comment by sdybskiy** [comment]
@splendido the pw match works in boilerplates, i just don't know what value would validate the invite.

**Comment by sdybskiy** [comment]
new error: 

```
Exception while simulating the effect of invoking 'validateInvite' TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"}
```

my method is the following: 

```
Meteor.methods({
  validateInvite: function (invite) {
    Meteor._sleepForMs(500);
    return !Invites.findOne({_id: invite});
  }
});
```

```
AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

Sorry, i wish i had a public repo for this but i can't atm.

**Comment by sdybskiy** [comment]
@splendido annddd final update lol

This is the weirdest thing ever, invite validation works, pw matching doesn't. if i set `confirmPassword: false` and do the sign-up process, it works perfectly but i need to have user put in their password twice. I have no clue what's going on there.

**Comment by splendido** [comment]
So you mean you still have two password inputs on the sign up form?

Could you at least share the whole AT configuration file?
...or, what if you put it among the boilerplate code?

I'm sorry I cannot be of much help, it's hard to say without being able to test the actual code :(

P.S. don't forget to remove the `Meteor._sleepForMs(500);` once this will be solved... ;-)

**Comment by sdybskiy** [comment]
```
Meteor.methods({
  validateInvite: function (invite) {
    // var item = Invites.findOne({_id: invite});
    // if (typeof item == 'undefined'){
    //   throw new Meteor.Error("invite-error", "Invite is not valid!");
    // } else {
    //   console.log('validation passed');
    //   // return true;
    //   var invalid = false;
    //   return invalid;
    // }
    // Meteor._sleepForMs(500);
    return !Invites.findOne({_id: invite});
  }
  // AccountsTemplates.init();
});

AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});

//Routes
AccountsTemplates.configureRoute('changePwd');
AccountsTemplates.configureRoute('enrollAccount');
AccountsTemplates.configureRoute('forgotPwd');
AccountsTemplates.configureRoute('resetPwd');
AccountsTemplates.configureRoute('signIn', {
    name: 'sign-in',
    path: '/sign-in',
    template: 'sign-in',
    redirect: '/',

});
AccountsTemplates.configureRoute('signUp', {
    name: 'sign-up',
    path: '/sign-up',
    template: 'sign-up',
    redirect: '/',

});
AccountsTemplates.configureRoute('verifyEmail');

// Options
AccountsTemplates.configure({
  //defaultLayout: 'emptyLayout',
  showForgotPasswordLink: true,
  overrideLoginErrors: true,
  enablePasswordChange: true,
  sendVerificationEmail: false,

  //enforceEmailVerification: true,
  confirmPassword: false,
  //continuousValidation: false,
  //displayFormLabels: true,
  //forbidClientAccountCreation: false,
  //formValidationFeedback: true,
  //homeRoutePath: '/create-transfer',
  showLabels: false,
  showAddRemoveServices: true,
  //showPlaceholders: true,
  termsUrl: '/tos',
  privacyUrl: '/privacy',
  continuousValidation: true,
  negativeValidation: true,
  positiveValidation: true,
  negativeFeedback: true,
  positiveFeedback: true,
  texts: {
    errors: {
      mustBeLoggedIn: "Please login to use the service",
    }
  }
});
```

This setup works but it only has one input for a password, i need it to have the password confirmation so I'd need it to work without `confirmPassword: false,`

**Comment by splendido** [comment]
Are yo using the regular `atForm` inside your `sign-up` template?

**Comment by sdybskiy** [comment]
`{{> atForm state="signUp"}}`

**Comment by splendido** [comment]
Ok, I'll give it a try asap

**Comment by sdybskiy** [comment]
@splendido have you had a chance to take a look?

**Comment by splendido** [comment]
Hi @sdybskiy,
I might have a little time this afternoon.
Sorry for the delay, it's busy time this period... :(

**Comment by splendido** [comment]
Ok @sdybskiy, I've managed to try your configuration file with the semantic boilerplate.

Unfortunately for you :-(, it seems regularly working for me.

The only thing I've notice is that the `validateInvite` method is not wrapped inside a `if (Meteor.isServer)` conditional block, so you get simulation erros on the client... lets make it a server-only method and the error will go away...
Another suggestion would be turning on `continuousValidation` for the invite field to prevent pinging the server at each new character, which might be queueing up too much method calls...

My only suggestion would be to try start again from the raw AT templates and see whether things get any better.

Otherwise I can always get a local clone of `useraccounts:core` into your `pacakges` folder (see [Working locally](https://github.com/meteor-useraccounts/core#working-locally)) and try to debug the password matching at [this](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L97) line.

I'm sorry I cannot be of much help :(
...I'd be glad to debug you're code if you could send me somehow.

Let me know!

**Comment by sdybskiy** [comment]
Hey @splendido thought updating the packages would resolve anything but I'm still stuck. just to confirm, you mentioned 

```
AccountsTemplates.addField({
  _id: 'invite',
  type: 'text',
  trim: true,
  displayName: "Invitation Code",
  required: true,
  func: function(invite){
    if (Meteor.isClient) {
      console.log("Validating invitation code...");
      var self = this;
      Meteor.call("validateInvite", invite, function(err, invalid){
        if (err) {
          console.log(err.reason);
          self.setError(err.reason);
        } else {
          if (invalid) {
            self.setError("Invalid Code");
          }
          else {
            self.setSuccess();
          }
        }
        self.setValidating(false);
      });
      return;
    }
    // Server
    return Meteor.call("validateInvite", invite);
  },
  errStr: 'Invalid Invitation code.',
});
```

With the first method call on the Client. Then you mentioned that I should wrap up my method into `if (Meteor.isServer)` does it mean i need to have to different validate invite methods?

**Comment by splendido** [comment]
I meant the definition of the method:

```javascript
if (Meteor.isServer) {
  Meteor.methods({
    validateInvite: function (invite) {
      return !Invites.findOne({_id: invite});
    }
  });
}
```

to prevent having also a client-side version which will not be able to access the `Invites` collection, which you want to keep safe on the server-side only ;-)

**Comment by sdybskiy** [comment]
Yeah, this whole thing boggles me.

I removed the additional field and the password matcher still doesn't work. Which parts of code will you need to hopefully help me out? or how do i start off fresh? :/ i tried replicating the error but i don't know where to start to track it down

**Comment by splendido** [comment]
I'm sorry, but if I cannot try your code, my only suggestion for you would be to start again from one of the boilerplates with your AT configuration (which seems to work from my side, also setting `confirmPassword` to `true`) and then start adding back other parts of your app until you discover which is the one creating problems...

What would you suggest different than this?

**Comment by sdybskiy** [comment]
@splendido would any other package potentially have an affect on the way `useraccouts:core` works?

**Comment by splendido** [comment]
I'd say, no.
The only thing might be some weird reactive re-rendering due to some custom weird middleware routing from iron:router.

Lets try to create a `packages` folder inside your app.
Clone `useraccounts:core` into it with `git clone https://github.com/meteor-useraccounts/core.git`
...at this point you should be using the local version of `core`...

Head to `lib/templates_helpers/at_pwd_form.js` and insert at [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L98) the following:

```javascript
console.log("pwd1: " + password);
console.log("pwd2: " + password_again);
```

to visually check what's the two inpputs' value. The try to track what happens from there on...

**Comment by sdybskiy** [comment]
do i mention it in `.meteor/packages` as `core` or `useraccouts:core` ?

**Comment by splendido** [comment]
`useraccounts:core` but I guess you already have it as dependency...
To be sure issue a `meteor add useraccouts:core` from the main folder

**Comment by sdybskiy** [comment]
make sure you spell your packages correctly ;)

**Comment by splendido** [comment]
I've just copy/pasted from your line above ;-)

**Comment by sdybskiy** [comment]
Touche

**Comment by sdybskiy** [comment]
inside `.meteor/packages` i have: 

```
useraccounts:core
useraccounts:bootstrap
```

under `/packages/core/lib/template_helpers/at_pwd_form.js` i did this

```
        // Extracts username, email, and pwds
        var current_password = formData.current_password;
        var email = formData.email;
        var password = formData.password;
        console.log("pwd1: " + password);
        var password_again = formData.password_again;
        console.log("pwd2: " + password_again);
        var username = formData.username;
        var username_and_email = formData.username_and_email;
        // Clears profile data removing username, email, and pwd
        delete formData.current_password;
        delete formData.email;
        delete formData.password;
        delete formData.password_again;
        delete formData.username;
        delete formData.username_and_email;

        if (AccountsTemplates.options.confirmPassword){
```

Nothing is getting through to my console :(

**Comment by splendido** [comment]
the client browser's console right?

**Comment by sdybskiy** [comment]
Yup :)

**Comment by splendido** [comment]
To check you're using the local version, try to comment/change one line and verify that your server i sbeing restarted as a consequence

**Comment by sdybskiy** [comment]
`Client modified -- refreshing ` goes up

**Comment by sdybskiy** [comment]
I'm really sorry this is wasting your time, I wish it worked lol. Thanks again for communicating so well

**Comment by splendido** [comment]
you're welcome

**Comment by sdybskiy** [comment]
is there anything else i can check for in the console to see how the form is behaving?

**Comment by splendido** [comment]
well, it's hard to believe you're not getting any log... :(
Please try insist this way!

other places to check are [this](https://github.com/meteor-useraccounts/core/blob/685aff51a8d0008359fc4f0d3385826196642b96/lib/templates_helpers/at_input.js#L78) and [this](https://github.com/meteor-useraccounts/core/blob/685aff51a8d0008359fc4f0d3385826196642b96/lib/templates_helpers/at_input.js#L100)

**Comment by sdybskiy** [comment]
if i just do `$("#at-field-password").val()` in the console with the password field filled in, i get back an empty string

**Comment by splendido** [comment]
what if you *inspect* the element? id the `id` correct?
`$("#at-field-password")` returns something?

**Comment by sdybskiy** [comment]
```
if (value && fieldId === "password_again"){
          console.log(value);
          console.log(fieldId);
            if (value !== $("#at-field-password").val())
                return this.setError(AccountsTemplates.texts.errors.pwdMismatch);
        }
```

outputs the value of that field on focusout so that's working!

**Comment by sdybskiy** [comment]
now not sure why the other logs weren't working

**Comment by sdybskiy** [comment]
![screen shot 2015-01-25 at 7 13 46 pm](https://cloud.githubusercontent.com/assets/3760543/5893993/72d5aab6-a4c6-11e4-92e7-337b028e00df.png)

i have it log the input field values on focus out :/

**Comment by splendido** [comment]
Hei, but are you using `useraccounts:polymer`?!?!
...I forgot to ask :(
This might change everything....
Let me give it a try later on today.

**Comment by sdybskiy** [comment]
@splendido nope, I'm using 
```
useraccounts:bootstrap@1.5.0
useraccounts:core@1.5.0
```

**Comment by splendido** [comment]
...oh, sorry actually you already told it :(

**Comment by sdybskiy** [comment]
@splendido yeah, wish it was something that helped :/ I have a reset password `{{> atForm state="changePwd"}}` and the passwords match there

**Comment by splendido** [comment]
there must be some black magic poisoning your js code ;-)

**Comment by sdybskiy** [comment]
can i submit an issue for black magic then? :P how do i start from scratch with this

**Comment by splendido** [comment]
No, no black magic issues, please...

...what if you remove `state="..."`?
just to see what happens, then you should be able to navigate from one state to the other by mean of links.

Actually you don't need it at all, since you're using `configureRoute`: setting the initial state is already done for you on the `onBeforeAction` hook for the route.

**Comment by sdybskiy** [comment]
with `{{> atForm}}`

![screen shot 2015-01-26 at 12 11 46 pm](https://cloud.githubusercontent.com/assets/3760543/5904165/97876820-a554-11e4-8064-f199ea862824.png)

**Comment by sdybskiy** [comment]
@splendido so i went back to using the atmosphere package instead of the local one i cloned, and everything fell back into pieces. confirm password and invite work. Black magic, you were right

**Comment by splendido** [comment]
wow, that's weird at least :(

Btw, I'm happy you got back to working status!
tnx!
