### ISSUE TITLE
Cancel Forgot Password 

### ISSUE THREAD

**Issue by Kestanous** [meteor-useraccounts/core#229]
Whats the best way to add a cancel button to the forgot password page? Running this in Cordova means that users don't have a back button. Thanks!
![cancel_button_please](https://cloud.githubusercontent.com/assets/1283884/5712789/771a8bfc-9a83-11e4-9020-5b9c03662481.png)

**Comment by Kestanous** [comment]
This is also true for the reset-password page. I am guessing I should just use a custom template but what about the form triggered by the "Forgot your password?" link on the "sign-in" page.

**Comment by splendido** [comment]
mmm, there should be a link to the sign up page below the submission button!
You can test it on crater.io, for ecample

are you using the latest version? ...there was no link ages ago ;-)

**Comment by Kestanous** [comment]
We are doing invite only... so the config looks like:
```js
AccountsTemplates.configure({
  forbidClientAccountCreation: true,
  showForgotPasswordLink: true
});
```

Which I believe removes all cases of "sign up".

**Comment by splendido** [comment]
I see...

So this is actually a bug!
...in case sign ups are not allowed we should show at least the link back to sign in.
Would you be fine with this?

A cancel button might be more work to be done since there's none right now.

Can you wait the next week for this fix?

**Comment by Kestanous** [comment]
That would be awesome! We don't go live until the end of the month so that works great for us.

**Comment by splendido** [comment]
Ok let me try to give it a look in the next days...
I guess it's just a matter of changing the condition about when the sign in link is to be shown.
Should be [this method](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_form.js#L44) actually ;-)

**Comment by splendido** [comment]
...well, feel free to experiment with if and come back with a PR if you have more time than me ;-)

**Comment by Kestanous** [comment]
Will do ^_^ kinda busy right now but if I can I will do a dive. Knowing about that method might just be enough.

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
you should be able to pick up `AccountsTemplate.options.forbidClientAccountCreation` from inside there...

**Comment by Kestanous** [comment]
Also lets not forget change-password, where a user will be logged in but may not wish to change there password after clicking on the button.

**Comment by splendido** [comment]
right!

What about the *back* button of the mobile device? ;-)
...kidding apart, do you think it might be worth possibly having a `back` button shown below the submission one for both the forgot password and change password states?

**Comment by Kestanous** [comment]
A button strikes me as the most intuitive, and not just for mobile. Also for change-password, maybe a link that says "forgot-password" like Github does. If a user has been logged in for a number of months its not unreasonable for them to have forgotten.

**Comment by Kestanous** [comment]
Having thought on it I think two changes would be best:

1. When you click the "forgot-password" link on sign-in and want to go back there should be a back button that takes you back to the sign-in. 

2. Routes should have a cancelLink option. Then when you render the fullPageAtForm you can check if cancelLink is defined and add an appropriate button:
```js
AccountsTemplates.configureRoute('changePwd', {
  cancelLink: '/profile'
});
```

What do you think?

**Comment by Kestanous** [comment]
@splendido What do you think of the above ideas? If you like them I will try to PR some time this week.

**Comment by splendido** [comment]
Yeah sure, you're welcome to send PRs!
Sorry have lost this issue among the others...

the `cancelLink` option looks good.
The only think is I guess it would be easier to implement it as a configuration option rather than as a route's parameter.

something like:

```javascript
AccountsTemplates.configure({
    cancelLink: {
        forgotPwd: <something>,
        ...
    }
});
```

and perhaps you could accept both string or functions like we did for the `redirect` option for the routes.

the default logic (to be run when the value passed in is `null` or `undefined`?) could send you back to the last form sate (to be added as another property on AccountsTemplates) or to the previous path (even if this would be somehow useless, since it wouldn't bring you back to the sign-in from the forgot-pwd page...)


Btw, feel free to code what you feel more confident with.
Tnx!

**Comment by splendido** [comment]
...and the html template part

```html
{{#if showCancelBtn}}
   <cancel button>
{{/if}}
```

to be added [here](https://github.com/meteor-useraccounts/semantic-ui/blob/master/lib/at_pwd_form.html#L11) (for example, but you'll have to add it to all frameworks ;-) )

could use as a `showCancelBtn` like this:

```javascript
AT.prototype.atPwdFormHelpers = {
  showCancelBtn: function(){
    var parentData = Template.currentData();
    var state = (parentData && parentData.state) || AccountsTemplates.getState();
    return (state in AccountsTemplates.options.cancelLink);
  }
};
```

to be added [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L17)

**Comment by splendido** [comment]
Let me know if you need furter pointers!

**Comment by Kestanous** [comment]
Awesome thanks, I will look into it. FYI it may be a few days before I can put something up. I am fighting my own army of issues :P

**Comment by splendido** [comment]
I see, I'm lacking free time too :(

**Comment by Kestanous** [comment]
Yeah, you seem swamp on this project alone. Don't over do it, we meteorites need you! Seriously this package save so much work as is, so don't stress this issue at least.

**Comment by splendido** [comment]
Thanks for the support ;-)

Well I'm still on this with my mind, the thing is I'm having a busy time at work and also at home with my family...
During the holidays I manages to launch autopublish.meteor.com, now I should be back on this.
...slowly trying to shape the v2.0 ;-)

But count on me!

**Comment by Kestanous** [comment]
@splendido how does https://github.com/meteor-useraccounts/core/commit/7c1dce12d480a4a2b75a1176a25c1e79437451ce look?

**Comment by Kestanous** [comment]
I only added support for the back button on forgot password for now.

**Comment by Kestanous** [comment]
Well shoot. I pulled in current master and it looks like this was solved already. There is a "If you already have an account [sign in]()" link at the bottom of the form now.

**Comment by splendido** [comment]
Yeah, I've added the link back to sign in with fbe21dd as reported above here

**Comment by splendido** [comment]
I've added some comments on the commit diff...
But it's a very good start!

**Comment by splendido** [comment]
This should be easily doable in v2.0 by adding a custom module to the default ones.
Closing here for now...
