### ISSUE TITLE
text area

### ISSUE THREAD

**Issue by michelkeyaerts** [meteor-useraccounts/core#230]
Is it possible to add a textarea field trough the AccountsTemplates.addField method?

**Comment by splendido** [comment]
At the moment this is not supported. 

But could be easily added...
would you be willing to prepare a PR if I point you the the files to be changed?

**Comment by michelkeyaerts** [comment]
I could, altough I'm a beginner. 
Thank you for your reply.

**Comment by splendido** [comment]
Please refer to the [Working Locally](https://github.com/meteor-useraccounts/core#working-locally) guide to try to play around.

[Here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L231) you have the list of allowed input types. You should add `textarea`

...you might be also interested in adding some configuration parameter (*lines number*?) to the current list [here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L133)

you'll have to test what happens [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_input.js#L24) where the template to display is choosed based on the input type.

Then, for all frameworks, you might need to add/modify something in the [file](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_input.html) where input field templates are defined.


This is more about a guide to add new input fields type, than a request for you to proceed.
Feel free to try, but please don't feel obliged to.

Let me know about any proceedings!

**Comment by splendido** [comment]
I think this could be solved with what proposed in #273.

Could you please give it a try?

**Comment by splendido** [comment]
Ok, this is a working example:

```html
<template name="biographyInput">
  <div class="at-input field">
    <label for="at-field-{{_id}}">
      {{displayName}}
    </label>
    <textarea rows="4" id="at-field-{{_id}}" name="at-field-{{_id}}" {{disabled}}></textarea>
  </div>
</template>
```

```javascript
AccountsTemplates.addField({
  _id: 'bio',
  type: 'text',
  displayName: "Short Biography",
  template:"biographyInput"
});
```

**Comment by splendido** [comment]
See also [customInputFields/semantic-ui/textarea](https://github.com/meteor-useraccounts/wiki/blob/master/customInputFields/semantic-ui/textarea.md) on the wiki.
