### ISSUE TITLE
Configure text in multiple language

### ISSUE THREAD

**Issue by MoriartyJoke** [meteor-useraccounts/core#231]
Hi, 

I'm a french developper, and I'm using your package for my company.

I want to change some fields, but maintain the possibility of translation to english.
I don't really know if I'm clear or not, so here is my code :

        AccountsTemplates.configure({
            texts: {
                signUpLink_link: "S'inscrire",
                socialSignUp: "S'inscrire",
                button: {
                    signUp: "S'inscrire"
                },
                title: {
                    signUp: "S'inscrire"
                }
            }
        });

The base translation for signUp in french, it's "S'enregistrer". I want to replace that by "S'inscrire", but I don't want to loose the possibility of changing language.

It's the actual state, all translations are replaced by "S'inscrire". And it's not really what I'm looking for!

Ok, I hope you understand my issue, and sorry by advance for my english
If you have a solution, it would be awesome!

**Comment by splendido** [comment]
Hi there,
I see what you mean!

The correct way is to overwrite the key mapping for the French language on T9n.

I'm not at the PC now but should be something like:

```T9n.map('fr', {signUp: 'S'inscrire'})```

Lets have a look at the T9n [docs](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/README.md#define-translations)

This should preserve all other translations...

Let me know if it works!

**Comment by Kestanous** [comment]
@MoriartyJoke I can confirm that @splendido solution works as we are doing that for formal 'es' translations.

**Comment by MoriartyJoke** [comment]
Yes, it works perfectly! Thanks a lot

**Comment by splendido** [comment]
You're welcome!
