### ISSUE TITLE
role management using useraccounts-core 

### ISSUE THREAD

**Issue by Hareramrai** [meteor-useraccounts/core#232]
Hi,

Is there any package that will be work with useraccounts-core to support role management feature ? 

Can anyone help me for this . 

Thanks,
Hare

**Comment by kevohagan** [comment]
What do you mean?

the best/only real role management package for meteor is alanning:roles

You can definitely make useraccounts:core and alanning:roles work together.

It all really depends on what you want

On 14 January 2015 at 16:17, Hare Ram Rai <notifications@github.com> wrote:

> Hi,
>
> Is there any package that will be work with useraccounts-core to support
> role management feature ?
>
> Can anyone help me for this .
>
> Thanks,
> Hare
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/core/issues/232>.
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by Kestanous** [comment]
@Hareramrai I use alanning:roles with this. I often work with invite only so I create the users on the server. But you could use matb33:collection-hooks to pull of a `Meteor.users.after.insert` for the same effect:

```js
      var user = {
        email: data.email,
        profile: {
          username: data.name //editable by user
        }
      }
      var id = Accounts.createUser(user);
      roles = {}
      roles[data.groupId] = [data.role]
      //add groupId to the user object to for fast users queries. 
      Meteor.users.update(id, {$set: {
        groups: [{_id: data.groupId}],
        roles: roles
      }});
      Accounts.sendEnrollmentEmail(id)
```
This example includes groups but they are not required. Once the enrollment email is set user-accounts handles the rest.

**Comment by splendido** [comment]
If you wish to filter page access based on use roles, it should be straighforward to start from the [AccountsTemplates.ensureSignedIn]() code and check whether the current user has the right roles or not:

```javascript
ensureRightRole = function() {
    var user = Meteor.user();
    if (!user || !Roles.userIsInRole(user._id, ['view-secrets','admin'], group)) {
        AccountsTemplates.setPrevPath(Router.current().url);
        AccountsTemplates.setState(AccountsTemplates.options.defaultState, function(){
            var err = AccountsTemplates.texts.errors.mustBeLoggedIn;
            AccountsTemplates.state.form.set("error", [err]);
        });
        AccountsTemplates.avoidRedirect = true;
        // render the login template but keep the url in the browser the same

        var options = AccountsTemplates.routes["ensureSignedIn"];

        // Determines the template to be rendered in case no specific one was configured for ensureSignedIn
        var signInRouteTemplate = AccountsTemplates.routes.signIn && AccountsTemplates.routes.signIn.template;
        var template = (options && options.template) || signInRouteTemplate || "fullPageAtForm";

        // Determines the layout to be used in case no specific one was configured for ensureSignedIn
        var defaultLayout = AccountsTemplates.options.defaultLayout || Router.options.layoutTemplate;
        var layoutTemplate = (options && options.layoutTemplate) || defaultLayout;

        this.layout(layoutTemplate);
        this.render(template);
        this.renderRegions();
    } else {
        this.next();
    }
};

Router.onBeforeAction(ensureRightRole, only: ["my", "role", "protected", "route", "names"]);
Router.onBeforeAction(AccountsTemplates.ensureSignedIn, only: ["my", "protected", "route", "names"]);
```

See also [Usage Example](https://github.com/alanning/meteor-roles#usage-examples) of `alanning:roles`
