### ISSUE TITLE
Have to click "Forget Password?" link twice

### ISSUE THREAD

**Issue by deetergp** [meteor-useraccounts/core#234]
We are using Accounts Template for our application and it's pretty fantastic! We have one issue though and that's that it takes two clicks of the "Forgot Password?" link in order to get to the `forgotPwd` template. The first click, regardless of whether or not there is anything entered in the _email_ field, we get a "Must be logged in" error. But the next click always takes you to the right place. 

Any thoughts on why that may be or where I ought to go to troubleshoot this further? I'm happy to help but am a little in the weeds as to where to start debugging it. Thanks!

**Comment by splendido** [comment]
Hi there!

This sounds like you have protected the access also for the `/forgot-password` route...
How are you using `AccountsTemplates.ensureSignedIn`?
May it be you have some other middleware for iron:router interfering with this?


Could you please have a try with the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) and verify it's working fine with them?

**Comment by deetergp** [comment]
@splendido, we are using `AccountsTepmlates.ensureSignedIn in the following way:

    // Configure non-password protected routes.
    Router.onBeforeAction(AccountsTemplates.ensureSignedIn, {
      except: ['home', 'atSignIn', 'atSignUp', 'atForgotPassword', 'atResetPwd']
    });

Should we be doing it differently?

**Comment by splendido** [comment]
Yeah, it seems the right way.

Could you still try to temporarily comment it out and see if the double click need disappear?

**Comment by onip** [comment]
@deetergp please verify, in the array you pass to except that all strings are actual route names. At the first glance one in 'Password' and 'Pwd' is wrongly spelled.

**Comment by splendido** [comment]
thanks @onip, you're right!

The actual name for the forgot password route is `atForgotPwd`.
I'm sorry @deetergp, I haven't noticed it at a first sight :(

**Comment by deetergp** [comment]
That was it! Thanks for the update.

**Comment by splendido** [comment]
Actually, reasoning with @onip, it turned out that the `except` option works with routes' name and not with routes' path.

so the most concise way to do it would be

```javascript
Router.onBeforeAction(AccountsTemplates.ensureSignedIn, {
  except: _.pluck(AccountsTemplates.routes, 'name')
});
```

...just make sure this is run after the AT configuration file ;-)
