### ISSUE TITLE
Add default values to hidden custom fields

### ISSUE THREAD

**Issue by buduguru** [meteor-useraccounts/core#235]
I need 2 hidden custom fields to be added to `profile` field on sign up by adding this:

```javascript
AccountsTemplates.addFields([
    {
        _id: 'ratedItems',
        type: 'hidden'
    },
    {
        _id: 'starredItems',
        type: 'hidden'
    }
]);
```

They both should be empty arrays `[]`. 
How can I indicate default values? Can I add smth like `default: '[]'` ?

**Comment by kevohagan** [comment]
why do you want to include them inside your accountstemplate if they are
hidden?

you could just extend the user object on signup with the desired values.

see http://docs.meteor.com/#/full/accounts_oncreateuser

On 17 January 2015 at 18:02, Alex Alexeev <notifications@github.com> wrote:

> I need 2 hidden custom fields to be added to profile field on sign up by
> adding this:
>
> AccountsTemplates.addFields([
>     {
>         _id: 'ratedItems',
>         type: 'hidden'
>     },
>     {
>         _id: 'starredItems',
>         type: 'hidden'
>     }
> ]);```They both should be empty arrays `[]`. How can I indicate default values? Can I add smth like `default:"[]"` ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/core/issues/235>.
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by buduguru** [comment]
You are right, thanks.

I just had an issue with OrionJs https://github.com/orionjs/core/issues/13 (error: `Can only call onCreateUser once`) and from its dependencies I discovered useraccounts, so I thought It would be better Idea to add fields by its means. But if it is not possible, I need to remove OrionJs then and find another admin package. Furthermore, OrionJs depends on useraccounts:bootstrap but I use Semantic-UI so I would need to fork it and rewrite html. 

PS obviously deleted OrionJS and now `onCreateUser` can be used.

**Comment by kevohagan** [comment]
Cool!! great to hear!

yeah i agree , those admin packages are interesting (orionjs, meteor-admin,
etc) but still very immature and all depend solely on bs3 which is a shame
but understandable at the beginning i guess.



On 17 January 2015 at 19:48, Alex Alexeev <notifications@github.com> wrote:

> You are right, thanks.
>
> I just had an issue with OrionJs orionjs/core#13
> <https://github.com/orionjs/core/issues/13> (error: Can only call
> onCreateUser once) and from its dependencies I discovered useraccounts,
> so I thought It would be better Idea to add fields by its means. But if it
> is not possible, I need to remove OrionJs then and find another admin
> package. Furthermore, OrionJs depends on useraccounts:bootstrap but I use
> Semantic-UI so I would need to fork it and rewrite html.
>
> PS obviously deleted OrionJS and now onCreateUser can be used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/core/issues/235#issuecomment-70379002>
> .
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by buduguru** [comment]
Yes.... I will also try https://github.com/gterrono/houston/ though it depends on bs3 too :)

**Comment by kevohagan** [comment]
what are you're trying to do?

because generally with autoform and its plugins you can build an admin
interface quite suited for your needs

On 17 January 2015 at 19:58, Alex Alexeev <notifications@github.com> wrote:

> Yes.... I will also try https://github.com/gterrono/houston/ though it
> depends on bs3 too :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/core/issues/235#issuecomment-70379380>
> .
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by buduguru** [comment]
I will have very much content so I need some panel to be able making changes fast. I'm quite new to meteor, so I did not try autoform yet, will check it out, thanks.

**Comment by splendido** [comment]
@buduguru, if you're using Semantic-UI checkout `useraccounts:semantic-ui` ;-)

and yes, at the moment hidden fields does not support default values.
They where introduced mainly to pick up query parameters on the url (i.e. if you're coming from a link you got by email which proposes some kind of offers, discounts, etc..)

`Accounts.onCreateUser` is supposed to be the right place where to do this kind of *default* settings.
Unfortunately some packages burns out this possibility, as you already discovered...

**Comment by buduguru** [comment]
@splendido yes, I installed 'useraccounts:semantic-ui' and it works like a charm except this https://github.com/meteor-useraccounts/semantic-ui/issues/10

**Comment by elie222** [comment]
@kevohagan the reason you'd not want to use onCreateUser is that it can only be implemented once, so packages can't make use of it in case the regular app also uses it.

**Comment by timbrandin** [comment]
I'd love a default field on hidden, because having query parameters as the only way to add values to that field is very limited. 

In the case that one parttakes in a survey as the first thing you do before you sign up and there are multiple pages in between, then the query would need to be passed down to every page. I'd rather have the contextual parameter be added by a method in a default value or method.

**Comment by BrianJLennon** [comment]
Good to know you can't use a default value - should this be in the docs?
