### ISSUE TITLE
onloggedin hook

### ISSUE THREAD

**Issue by babnik63** [meteor-useraccounts/core#236]
Is there any event after successful attempt?
I think it is very useful, for example you want to subscribe to some publications after authenticating the user in client side.

**Comment by splendido** [comment]
...at the moment there's no hook for this.
But since it's a very requested feature (lets try to google a bit...) I'll try to put it in...

**Comment by splendido** [comment]
...mmm, I guess I've lost the control on AT ;-)

Please have a look at `onSubmitHook` described among the available [Options](https://github.com/meteor-useraccounts/core#options).

you can configure it with a  function like this:

```javascript
var mySubmitFunc = function(error, state){
  if (!error) {
    if (state === "signIn") {
      // Successfully logged in
      // ...
    }
    if (state === "signUp") {
      // Successfully registered
      // ...
    }
  }
};

AccountsTemplates.configure({
    onSubmitHook: mySubmitFunc
});
```

Let me know it this suites your needs, and forgive me for the wrong answer!
