### ISSUE TITLE
Position of signIn link on signUp form

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/core#239]
When showing the link to signIn on the signUp form, it should probably be placed below the terms-and-conditions paragraph. Seems more logical.

**Comment by splendido** [comment]
I'm quite indifferent about this.
Lets see what others think...
@meteor-useraccounts/core-devs, @meteor-useraccounts/bootstrap, @meteor-useraccounts/famous @meteor-useraccounts/semantic-ui?

**Comment by kevohagan** [comment]
mm for me i don't really see the benefit. i think it's similar so I would
just keep it as is for simpleness

On 20 January 2015 at 14:51, Luca Mussi <notifications@github.com> wrote:

> I'm quite indifferent about this.
> Lets see what others think...
> @meteor-useraccounts/core-devs
> <https://github.com/orgs/meteor-useraccounts/teams/core-devs>,
> @meteor-useraccounts/bootstrap
> <https://github.com/orgs/meteor-useraccounts/teams/bootstrap>,
> @meteor-useraccounts/famous
> <https://github.com/orgs/meteor-useraccounts/teams/famous>
> @meteor-useraccounts/semantic-ui
> <https://github.com/orgs/meteor-useraccounts/teams/semantic-ui>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/core/issues/239#issuecomment-70655684>
> .
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by dalgard** [comment]
Interestingly, the position struck me as outright illogical. The paragraph with the terms is directly related to the button – these are the terms you must accept before clicking.

Whatever other links are related, such as taking the user to another page (could be any number of links), has to belong *after* the form.

**Comment by splendido** [comment]
Interestingly the [github signup](https://github.com/) shows the paragraph abouth terms and the like below the *sign up* button.

...but if you click the button leaving all inputs black (for example), the new page shows the same text right above the button.

**Comment by splendido** [comment]
Thought a bit about this...
...and I appreciate it makes more sense to appear right below the button, before any other link.

Tnx!

**Comment by dalgard** [comment]
Thank *you* :)
