### ISSUE TITLE
Options for customizing form layout and style

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/core#242]
This is a continuation of [this thread](https://github.com/meteor-useraccounts/semantic-ui/issues/11) under the Semantic UI version.

The properties on each object that is given to `addField` are picked using a white-list before they go into the final `Field` object which is used as the context for the templates. I am wondering why this is necessary. Are there any security implications of this? Or is it simply because it is considered a best-practice using the `check()` function?

Here's how it currently works in the code. I, as a developer, write this:

```javascript
AccountsTemplates.addField({
  _id: 'organization',
  type: 'text',
  options: {
    dividerBefore: true
  }
});
```

The core code then does this, with `FIELD_PAT` being the white-list:

```javascript
AT.prototype.addField = function (field) {
  ...
  field = _.pick(field, _.keys(FIELD_PAT));
```

This means that the custom `options` object that I put on my field cannot be accessed in the templates.

What I would like to change in the core code, to begin with, is adding `options` to `FIELD_PAT`. This is the minimal change necessary for me to go and use my custom options in the templates.

```javascript
FIELD_PAT = {
  ...
  options: Match.Optional(Object)
};
```

What I would then do, in order to do some subtle changes to the layout or style of the form, is override the smallest sub-template necessary for my change, using the [template-extension](https://github.com/aldeed/meteor-template-extension) package.

With the divider example, it would look like this:

```html
<template name="myAtInput">
  {{#if options.dividerBefore}}<hr>{{/if}}

  {{> Template.dynamic template=templateName}}
</template>
```

```javascript
Template.myAtInput.replaces("atInput");
```

I realize that overriding templates is not the end goal for the `useraccounts` packages, but this solution gives a lot of flexibility in the short term.

**Comment by splendido** [comment]
Hi @dalgard,
tnx for continuing the discussion here with a so comprehensive explanation.

My first answer would probaly be: "we can also add the `dividerBefore` option to the field object and change the `atInput` template accordingly for each framework".

But I also recognize this wont be a general solution to facilitate template *customization* in the long run.
You're right, using `template-extension` is not the best solution but for now it does a great job.
(It might be that templates overwrite will be supported in some future as a core Meteor feature...)

I'm open to accept a PR about this if we get agreement from others too.
Thoughts from the @meteor-useraccounts/core-devs?

**Comment by dalgard** [comment]
I've called the property `options` but I'm pretty indifferent about the name. Might be `templateOptions`, `customOptions`, `config` etc.

I'm using the patch in my app right now – works fine.

**Comment by dalgard** [comment]
See this gist on how to customize the layout of an AccountsTemplates form using the `options` object and [template-extension](https://github.com/aldeed/meteor-template-extension):

https://gist.github.com/dalgard/a844f6569d8f471db9a7

The trick with the collect loop makes it hard for me to boil it down more than it already is, so it's not ideal documentation material. Maybe it would be worth linking to it?

(A pull request for the docs is coming up, btw.)

**Comment by splendido** [comment]
Great customization, weel done!

You'll defenitely have to link to it from the docs (for which add more commits to #243 please!)

Thanks a bunch!

**Comment by dalgard** [comment]
Thanks :)

(Just to note, https://github.com/meteor-useraccounts/core/pull/243 was deprecated, because I messed up the repo somewhat. The new one is https://github.com/meteor-useraccounts/core/pull/250)

**Comment by splendido** [comment]
yep!
