### ISSUE TITLE
Uncaught Error: No such template: atNavButton   Blaze.View.lookup	

### ISSUE THREAD

**Issue by doubletaketech** [meteor-useraccounts/core#244]
Any idea why  I get this error?
Uncaught Error: No such template: atNavButton
  Blaze.View.lookup	

I'm running Meteor 1.0.3.1 with latest useraccounts:bootstrap

**Comment by splendido** [comment]
It's hard to say wih so little information...

I've just tried the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) and worked without problems with Meteor 1.0.3.1

**Comment by doubletaketech** [comment]
I don't really have any other information to share.  However, I can say that removing the package and re-adding it fixed the problem with template not being found.

Thanks
Don

**Comment by splendido** [comment]
ok, good!
