### ISSUE TITLE
Date type for extra registration form fields

### ISSUE THREAD

**Issue by aashiqerasool** [meteor-useraccounts/core#245]
In an app I am creating I need to store the date of birth of the user however a date form element has not been defined and thus I figure the user would have to type their date of birth in and this can be processed and converted, on form submission, into a date type to be stored into the mongodb for later use as a date. 

I would like to request you add a date form element/type that can be defined in the type field of the add field function to make adding date form elements easier.

**Comment by splendido** [comment]
Are you willing to play with this and come back with a PR?
I'd be happy to give you some pointers to make the process easier!
The *hardest* part at the moment is test it on all available frameworks...

Actually this is very similar to #230. Perhaps you and  @michelkeyaerts could join your efforts and collaborate on this?

**Comment by splendido** [comment]
I think this could be solved with what proposed in #273.

Could you please give it a try?

**Comment by aashiqerasool** [comment]
I have not tried your earlier suggestion as I have been quite busy recently. However when i tried the new recommendation you made from #273 i was given the below errors in the browser terminal.

W20150216-02:44:57.358(0)? (STDERR)                                             throw(ex);                                                                                             
W20150216-02:44:57.358(0)? (STDERR)                                                   ^                                                                                                
W20150216-02:44:57.375(0)? (STDERR) Error: field.type is not valid!                                                                                                                    
W20150216-02:44:57.375(0)? (STDERR)     at [object Object].AT.addField (packages/useraccounts:core/lib/core.js:338:1)                                                                  
W20150216-02:44:57.375(0)? (STDERR)     at app/lib/at_config.js:50:19                                                                                                                  
W20150216-02:44:57.375(0)? (STDERR)     at app/lib/at_config.js:61:3                                                                                                                   
W20150216-02:44:57.375(0)? (STDERR)     at /home/action/qcDashboard/.meteor/local/build/programs/server/boot.js:205:10                                                                 
W20150216-02:44:57.375(0)? (STDERR)     at Array.forEach (native)                                                                                                                      
W20150216-02:44:57.376(0)? (STDERR)     at Function._.each._.forEach (/home/action/.parts/packages/meteor/1.0/packages/meteor-tool/.1.0.40.kc4p9p++os.linux.x86_64+web.browser+web.cord
ova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)                                                                                     
W20150216-02:44:57.376(0)? (STDERR)     at /home/action/qcDashboard/.meteor/local/build/programs/server/boot.js:116:5                                                                  
=> Exited with code: 8                                                                                                                                                                 
=> Your application is crashing. Waiting for file change.

**Comment by splendido** [comment]
Lets try to *tweak* the configuration and pass `text` as field's type.

The following seems to work for me::

```javascript
AccountsTemplates.addField({
  _id: 'birthday',
  type: 'text',
  template: "dateInput",
});
```

```html
<template name="dateInput">
  <div class="at-input inline field">
    <label for="at-field-{{_id}}">{{displayName}}</label>
    <input type="date" id="at-field-{{_id}}" name="at-field-{{_id}}" {{disabled}}>
  </div>
</template>
```

Let me know!

**Comment by splendido** [comment]
The following is another working example (for bootstrap using [rajit:bootstrap3-datepicker](https://atmospherejs.com/rajit/bootstrap3-datepicker)).

Custom template:

```html
<template name="birthdayInput">
  <div class="at-input form-group {{#if isValidating}}validating{{/if}} {{#if hasError}}has-error{{/if}} {{#if hasSuccess}}has-success{{/if}} {{#if feedback}}has-feedback{{/if}}">
    <label class="control-label {{#unless showLabels}}sr-only{{/unless}}" for="at-field-{{_id}}">
      {{displayName}} {{#unless required}}{{optionalText}}{{/unless}}
    </label>
    <input type="{{type}}" class="form-control" id="at-field-{{_id}}" name="at-field-{{_id}}" placeholder="{{placeholder}}" autocapitalize="none" autocorrect="off">
    {{#if hasIcon}}
      <span class="{{iconClass}} form-control-feedback"></span>
    {{/if}}
    <span class="help-block {{#unless hasError}}hide{{/unless}}">{{errorText}}</span>
  </div>
</template>
```

```javascript
Template.birthdayInput.rendered = function() {
  this.$('input').datepicker();
};
```

UserAccounts configuration:

```javascript
AccountsTemplates.addField({
  _id: 'birthday',
  type: 'text',
  displayName: "Birthday",
  template:"birthdayInput"
});
```

See also [customInputFields/bootstrap/datepicker](https://github.com/meteor-useraccounts/wiki/blob/master/customInputFields/bootstrap/datepicker.md) on the wiki,

**Comment by aashiqerasool** [comment]
It's been a while since I have been able to get round to this but I attempted the workaround you suggested on Feb 16th due to using the semantic-ui flavour of useraccounts. Works perfectly with standard html date selector. Thanks

**Comment by aboobakkar** [comment]
Good Answer  @splendido
