### ISSUE TITLE
_id not capitalized when used as label/placeholder

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/core#247]
The documentation says this:

> In case nothing is specified, the capitalized `_id` will be used.

But it doesn't seem to become capitalized. See the screenshot at the bottom of this gist:

https://gist.github.com/dalgard/a844f6569d8f471db9a7

**Comment by splendido** [comment]
Good catch!
...I guess I lost it when I introduced the [Field](https://github.com/meteor-useraccounts/core/blob/master/lib/field.js) class :(

It seems you're gathering a good knowledge about AT...
Do you have any willing to be part of the official developers?

**Comment by dalgard** [comment]
Thanks for asking. I don't have the energy for another project, but will help out this way when I can :+1:

**Comment by splendido** [comment]
ok, great!
