### ISSUE TITLE
onSubmitHook not called properly for signUp form with enforceEmailVerification

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/core#249]
See [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L151-164) in `at_pwd_form.js`. Here's what's going on:

After the user is created, `submitCallback` is called. `submitCallback` is the internal function that actually begins with calling the `onSubmitHook` provided by the developer, but `submitCallback` is called with `undefined` as the `state` – I believe this is because the function is called again further down with the correct state.

The problem is, in the special case of `enforceEmailVerification`, `submitCallback` isn't being called again. The form's result text is set to `signUpVerifyEmail` and the form is reset – but calling `submitCallback` again with the proper state is forgotten before returning.

I've created a patch that solves this and will send a pull request shortly.

**Comment by dalgard** [comment]
I will explain my use for `onSubmitHook` in this specific case really quick.

After successfully submitting the signUp form with `enforceEmailVerification` enabled, the result is shown and the form is reset (rudimentarily). But the way I see it, instead of having the user look at the same form again, I'd much rather show the result in a box alone, in the same style as the verification success message.

Fortunately, this is really easily achievable: The `verifyEmail` state formats the form exactly the way I like it. So, with the patch that I'm submitting in a moment, all I need to do is this:

```javascript
onSubmitHook: function (error, state) {
  if (!error && state === "signUp") {
    AccountsTemplates.setState("verifyEmail");
  }
}
```

**Comment by splendido** [comment]
Should be fine now after the above merge, right?
