### ISSUE TITLE
Enroll account terms and agreements

### ISSUE THREAD

**Issue by Kestanous** [meteor-useraccounts/core#253]
Currently terms and agreements are only available via sign up. For invite only apps there is no way to require users to agree to terms and agreements via user-accounts. Can we consider extending that logic to the enrollAccount page?

**Comment by splendido** [comment]
Yep, it makes sense!
...the magic happens [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_form.js#L59)

would you mind testing something like:

```javascript
  showTermsLink: function(next_state){
    if (!!AccountsTemplates.options.privacyUrl || !!AccountsTemplates.options.termsUrl) {
      var state = next_state || this.state || AccountsTemplates.getState();
      if (state === "signUp" || state === "enrollAccount" ) {
        return true;
      }
  },
```

**Comment by splendido** [comment]
...or you can test something like:

```javascript
state === "signUp" || (AccountsTemplates.forbidClientAccountsCreation && state === "enrollAccount")
```

**Comment by Kestanous** [comment]
Ack! Thanks and sorry! Still caught up in app deployment.

**Comment by splendido** [comment]
don't worry, it was an easy change.

But for the button I'll wait, promised ;-)

**Comment by mymedicalshopper** [comment]
I'm experiencing an issue with the terms and privacy urls on the enroll account page. It seems that it puts "enroll-account" before "terms" or "privacy" such as the following:

"/enroll-account/terms" or "/enroll-account/privacy" 

instead of:

"/terms" or "/privacy".

This is happening whether I put "privacy" or "/privacy" as the 'privacyUrl' setting (and the same for termsUrl).

**Comment by splendido** [comment]
@mymedicalshopper do you have any public repo reproducing this to share?

**Comment by mymedicalshopper** [comment]
Sorry, I do not. 

My AccountsTemplate config code looks like this:

AccountsTemplates.configure({
	...    

    // Privacy Policy and Terms of Use
    privacyUrl                          : '/privacy’, 			// I also tried just it without the leading slash and had the same result.. 
    termsUrl                            : '/terms’,

	…
});

**Comment by mcoenca** [comment]
Same bug here, privacy and terms links are broken whenever i arrive on the signUp state of atForm on an url that is not /signup. For exemple if i try to access http://myurl/first-road/start, terms will redirect me to /first-road/terms-of-use and privacy will redirect me to /first-road/privacy. Will look into it soon anyway, should not be too hard to fix
