### ISSUE TITLE
Request: Materialize

### ISSUE THREAD

**Issue by yejodido** [meteor-useraccounts/core#259]
Saw all the new additions over @ https://useraccounts.meteor.com/ and was wondering if there are any plans to create a Materialize (http://materializecss.com/) version to accompany the Polymer version.

I know there are issues between Polymer and Blaze with regards to reactivity, and I'd love to see a Materialize template.

**Comment by splendido** [comment]
Hello @yejodido,
thank you for asking!

I'm not in a position to start off anything about material design but there was already some activity about this: @mattkrick waas trying to override the templates to properly convert them.

If you decide to continue on this, I can provide some *step by step* guide on what should be changed.

Let me know!

**Comment by yejodido** [comment]
I'd love to help! A step by step guide would be incredibly helpful :+1:

**Comment by mattkrick** [comment]
I currently recommend the polymer skin by @kevohagan without problems. You can follow the polymer/meteor conversation here: https://groups.google.com/d/msg/meteor-talk/e1MyZ2vpquY/UtGttsHqqZgJ

With regards to reactivity, polymer lays on top of Blaze surprisingly nicely & in my experience feeding ReactiveVars into polymer elements hasn't been a problem. There is a healthy handful of material frameworks (material-ui, material.angular, boostrap material-design, and materializecss to name a few which all have a slightly different feel and all have a handful of bugs. My reason for going with polymer is ease of deployment (1 liners), the google bankroll to ensure that it doesn't go abandoned, the growing userbase for bugfinding, and the clear avoidance of bootstrap. If you wanted to avoid polymer, I'd recommend recreating the elements using meteor templates and helpers, which you could then use to create a useraccounts skin.

**Comment by yejodido** [comment]
I'm a huge fan of Polymer as well and love the stuff Differential has done with it, but I'm nowhere near  convinced it's production ready for Meteor apps. At this point in time, I just do not feel comfortable doing client-work in Polymer + Meteor.

That being said, I am a huge proponent of material design, and absolutely want to have that as an option for my production apps, and Materialize CSS definitely seems to me to be the clear leader when it comes to a javascript/css only implementation, and there should absolutely be a Accounts-UI implementation to reflect those of us who want the material animations/stylings without the overhead of web components, polyfills, and packages like Vulcanize to manage enormous includes.

**Comment by splendido** [comment]
Sorry guys I'm not that into these frameworks, so I think I cannot appreciate the level of the discussion.

Btw, if there's enough commitment/interest in developing another UI version, I'll have no problems in creating another repo from which you can start off.
@meteor-useraccounts/core-devs what do you think?

Let me know!

**Comment by yejodido** [comment]
@splendido I'd love to contribute to a meteor-useraccounts/materializecss

Your step by step guide would be greatly appreciated as well

**Comment by splendido** [comment]
Yeah, you're more than right.
We should have a step-by-step guide in the docs about how to start off a new UI version.

...btw, basically you'd need to copy the latest unstyled version into a new repo and start changing the html files in there.
Unless there are particular problems, the javascript files should remain unchanged.

I'd say the [polymer](https://github.com/meteor-useraccounts/polymer) could be a good example to understand what was changed wrt the [unstyled](https://github.com/meteor-useraccounts/unstyled) one.

**Comment by Kestanous** [comment]
I just really sat down to look at MaterializeCSS for the first time yesterday and I have to say I am sold. 

@yejodido I am willing to help you get this running, have you gotten started yet?

@splendido you should eye it when your free, I am ditching Semantic-UI for materializeCSS, semantic is a nightmare on Cordova.

**Comment by splendido** [comment]
If you guys are willing to jump on it, I'll be happy to create a new repository (as I already did for Pure.css).
Just let me know!

**Comment by splendido** [comment]
well...
Here you go: https://github.com/meteor-useraccounts/materialize

**Comment by Novashock** [comment]
Thanks @splendido! I will like to help with this project as well. I knew I was gearing toward polymer, but as @Kestanous said, I am sold to MaterializeCss.

**Comment by Kestanous** [comment]
Thanks @splendido! I will see if I can get if flushed out by tonight. @Novashock and @yejodido how do you want to collaborate on this?

**Comment by splendido** [comment]
@Kestanous, I'll try to see if we can get an official integration of materialize with autopublish.meteor.com

**Comment by Kestanous** [comment]
@yejodido @Novashock see https://github.com/meteor-useraccounts/materialize/pull/1 and tell me what you think. Maybe you can improve on it.

**Comment by yejodido** [comment]
Wow! Glad to see so many people on board and such progress being made! I won't have time to really sit down and look at what's been done till the weekend, but as soon as I can I'll pitch in, all hands on deck.

I think we'd be wise to take inspiration from Josh Adamous, who made this material login/subscribe form on codepen: http://codepen.io/joshadamous/pen/yyyqJZ

Hits all the right notes, is straightforward and flexible, and checks all the boxes on the material checklist. Thoughts?

**Comment by Kestanous** [comment]
@yejodido looks good, I think we have that much done if I am not mistaken.

You should checkout https://github.com/meteor-useraccounts/boilerplates and run the materialize example.
