### ISSUE TITLE
Login after verify

### ISSUE THREAD

**Issue by advany** [meteor-useraccounts/core#260]
How do I login a user if they have verified their account?

**Comment by splendido** [comment]
Hi @advany,
could you explain it a little more?

In case you're using the `verifyEmail` route, the user should get logged in straigth after a successful verification.

[Here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L583) is the call made to `Accounts.verifyEmail` for which you can read the official docs [here](http://docs.meteor.com/#/full/accounts_verifyemail)

**Comment by advany** [comment]
@splendido I saw that somehow the routes don't work.

I have them in my libs/routes.js

AccountsTemplates.configureRoute('signUp');
AccountsTemplates.configureRoute('signIn');
AccountsTemplates.configureRoute('changePwd');
AccountsTemplates.configureRoute('verifyEmail');
AccountsTemplates.configureRoute('forgotPwd');
AccountsTemplates.configureRoute('resetPwd');

This should be enough to verify the user right?

**Comment by advany** [comment]
Found the problem. Somehow the url returned by Accounts.emailTemplates.resetPassword.html has an extra hashtag

**Comment by splendido** [comment]
See #266
