### ISSUE TITLE
Persistent

### ISSUE THREAD

**Issue by advany** [meteor-useraccounts/core#261]
Hi there,

I saw that the session object is not used. I use persistent session package to keep a user logged in even after they leave the page and come back. How can I make useraccounts persistent because it doesn't use sessions?

**Comment by splendido** [comment]
This behaviour should be the default for the meteor accounts system!
Isn't it?

**Comment by advany** [comment]
sorry it is... that why I closed it

**Comment by splendido** [comment]
Ok, no worries, I just wanted to confirm it.
Tnx!
