### ISSUE TITLE
Iron router hooks run multiple times for routes that are protected by ensureSignedIn

### ISSUE THREAD

**Issue by bumbleblym** [meteor-useraccounts/core#262]
The onBeforeAction and onAfterAction hooks run twice when logged out, and thrice when logged in.

[Here's a reproduction repro.](https://github.com/bumbleblym/useraccounts-bug-repro)

**Comment by bumbleblym** [comment]
My mistake, the hooks only run once when logged in. Still, are they supposed to run twice when logged out?

**Comment by splendido** [comment]
I've cloned the repo and gave it a quick try.

I think the only reactive var within `ensureSignedIn` is the `Meteor.user()`, see [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/client.js#L162).
...which should be better changed to `Meteor.userId()`

I'll try to investigate more asap...

**Comment by splendido** [comment]
The source or reactivity was `Router.current()` :(

Btw, good catch!
Tnx!!

**Comment by bumbleblym** [comment]
Thanks for the prompt fix! :+1:

**Comment by splendido** [comment]
It was an easy one ;-)
