### ISSUE TITLE
Verify Email Link Not Working

### ISSUE THREAD

**Issue by adrianmc** [meteor-useraccounts/core#266]
The link generated by the email verification is:

http://localhost:3000/#/verify-email/Z3EZ6C1KvuXb_2GNh9X6CXTq2AqVvw_tFtgRXtSy0mE

But when I click that, nothing happens. It just takes me back to the home page. Also, I've checked that 	emails.0.verified = false. I'm not sure how to set up email verification.

**Comment by splendido** [comment]
Hi @adrianmc,
the `#` should not be present in the link. [Here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L541) is where the link it configured.

Have you configured the `verifyEmail` route with `AccountsTemplates.configureRoute`?

**Comment by splendido** [comment]
...in case you don't want to use `configureRoute`, the other solution is that you set `Accounts.urls.verifyEmail` by your self with something like [this](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L543-545):

```javascript
Accounts.urls.verifyEmail = function(token){
  return Meteor.absoluteUrl("verify-email/" + token);
};
```

**Comment by adrianmc** [comment]
Ah, I can't believe I missed that. Configuring the route fixed it. My bad for not catching this earlier. Much thanks for helping me out.

**Comment by splendido** [comment]
You're welcome!
I'm glad you solved it ;-)

**Comment by rjayako** [comment]
@splendido I'm a bit confused by "...in case you don't want to use configureRoute" as you stated above. Can you please explain to a beginner what you meant by that? and how I go about using that? I have the issue as OP and having difficulty getting it working :(

**Comment by splendido** [comment]
@rjayako what I meant is that in case you use `AccountsTemplates.configureRoute('verifyEmail')` everything will be set up by AccountsTemplates.

While in case you'd like to set up the route on your own (might be for many different reasons...) by using the IR API (or the FR API) you'll have to assign `Accounts.urls.verifyEmail` the above functions to get things working. 

I'd say in first place you'll want to use `AccountsTemplates.configureRoute('verifyEmail')` ;-)

**Comment by mitar** [comment]
I think the issue is if you are calling configuration only one the client. At least that was the issue for me.

Maybe that is unclear in the documentation? Or I missed something there.

**Comment by funkyeah** [comment]
Confirming with @mitar, I saw this issue when I mistakenly did configureRoute's on my client side router. If you primarily use a client-side routing file its easy to miss the spot in the documentation that says it needs to be defined at the common level. I think the biggest issue is that __most__ things work when you use configureRoute on client only. Could usage of configureRoute anywhere other that at a common level be detected and throw an Error or warning? 

Is it possible to catch that configureRoute is not being called at the common level and issue a warning?
