### ISSUE TITLE
WARNING: showForgotPasswordLink set to true, but MAIL_URL is not configured!

### ISSUE THREAD

**Issue by SachaG** [meteor-useraccounts/core#267]
Telescope users get this error when they run the app. I get why it happens, but in Telescope you can configure MAIL_URL from the Settings panel, so it's normal if it's not defined on the first run. 

Is there any way to disable the error? Or maybe it could only be shown when someone actually tries to send an email?

**Comment by splendido** [comment]
Yeah, this was already exposed by #210
I think I'll remove the warning.

Hopefully with the new organization foreseen for v2.0 (see also #221 and #240) we'll have better means to check whether the email service is correctly configured or not (possibly at actual need as you're suggesting).

Tnx!
