### ISSUE TITLE
Requesting permission tokens for Facebook login

### ISSUE THREAD

**Issue by fardeemmunir** [meteor-useraccounts/core#271]
I guess this is a naive question but I can't quite figure this out. So I have setup the facebook login but I need access tokens for the profile picture. In the Meteor docs its say loginWithFacebook function accepts an array for permissions but since the package is doing it is there anyway to set it up from the outside?

**Comment by splendido** [comment]
Hello @fardeemmunir,
this is actually a missing feature: see #179

But there's a way off thanks to [Accounts.ui.config](http://docs.meteor.com/#/full/accounts_ui_config)
