### ISSUE TITLE
Any way to hide the location bar in the inappbrowser ?

### ISSUE THREAD

**Issue by teknologist** [meteor-useraccounts/core#272]
Hi,

I have come across this issue. The rest is working great but that location bar is pretty ugly on android. (Cordova's InAppBrowser).

On the same project using ionic/Angularjs I managed to hide that by passing location=no,hidden=yes args to the window.open call.

Can anybody point me to the solution for a meteor/Cordova app.

By the way, I am literally falling in love with Meteor ! :-)

Thanks in advance,

Eric

**Comment by splendido** [comment]
Hi @teknologist,

I'm sorry but I never had a chance to play with the Cordova integration, and it doesn't seem this has actually something to do with `useraccounts`.

Perhaps someone within the @meteor-useraccounts/core-devs had some experience with this?
