### ISSUE TITLE
Terms of Use Checkbox

### ISSUE THREAD

**Issue by nickw** [meteor-useraccounts/core#273]
This is a pretty standard use case that appears to be impossible in `meteor-useraccounts`:

![17lx7v541o](https://cloud.githubusercontent.com/assets/3907/6051442/f50f66e4-ac7c-11e4-9cd5-fc44211f4dcc.png)

- I can't add links to the `displayName` property because the form labels get escaped
- Even if I do create a custom theme to wrap my labels in `{{{ }}}`, the error message is displayed as `I agree to the terms of use: Required Field`. 
- I can't create my own custom validation `func` to return a sane error message, because the `func` won't run if there isn't a `valueLength`

Any other ideas?

**Comment by splendido** [comment]
What you can do at the moment is to display the link below the submit button by configuring `privacyUrl` and `termsUrl` (see the [options](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options) section withing the Guide).

But you won't get the checkbox this way.

We might think to provide another configuration option to select whether to display the terms as plain text or with a checkbox on the side as you're requesting. But this could take some time.
I'd also say that this won't be a regular field, but should be considered as a special section of the `pwdForm` making the submission button disabled unless the checkbox is ticked.

Should ew put this for the v2.0 Milestone?

**Comment by nickw** [comment]
> What you can do at the moment is to display the link below the submit button by configuring privacyUrl and termsUrl

Right, but in this case the client requires that a user manually clicks something, and that that click is stored in the database as a boolean. I'm not sure how valid that request is, but it's not the first time I've gotten it.

> We might think to provide another configuration option to select whether to display the terms as plain text or with a checkbox on the side as you're requesting. But this could take some time.

I would opt for more flexibility, not more configuration. For instance, if I could easily override a template for a specific field by passing a `templateName` option to `addField`, and customize the error message for required fields like you can with `errStr`, then implementing this would be trivial. (Unless those two things are already possible and I'm just not seeing it?)

**Comment by splendido** [comment]
The better solution (at least for this use case) would be having the possibility to specify some html tags for the display name.
This is just a matter of changing `{{displayName}}` for `{{{display}}}` within the html templates, but would require to have a good sinitizer routine to be used on text configuration.
This was requested also in #205.

I've had a look at what Telescope is doing about this but then had no chance to implement something.

If you could help a bit with this, I'm open to switch to triple curly brackets! :-)

**Comment by splendido** [comment]
> I can't create my own custom validation func to return a sane error message, because the func won't run if there isn't a valueLength

What you mean with this?
I'll check the validation routine...

**Comment by nickw** [comment]
https://github.com/meteor-useraccounts/core/blob/master/lib/field.js#L202

Since `required: true` forces a specific error message, I thought that I could set `required: false`, but then implement a custom `func` to do the same thing as `required: true` but return my own error message. But `func` only runs of the field has a value.

**Comment by splendido** [comment]
Ok, I think I've got it...
Should be change [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/field.js#L202) for:

```javascript
if (this.func){
```

**Comment by splendido** [comment]
Yeah, I think the correct configuration would be something like this:

```javascript
AccountsTempaltes.addField({
  _id: 'terms',
  displayName: "I've read and agree to the </a href="...">Terms and Conditions</a>",
  errStr: "You must agree to the Terms and Conditions",
  func: function(value) {
    return value == "1"; 
  }
});
```

and we should get this working changing the validation function and switching to `{{{displayName}}}`

Thoughts?

**Comment by nickw** [comment]
Yeah, for the `func` and `errStr` that's exactly it. 

For `{{{displayName}}}`, like I said, I think it might be easier to just let users override a field's template (I believe autoform does this pretty well). That will allow a lot more flexibility, rather than having to tackle use cases like this on a case-by-case basis.

**Comment by splendido** [comment]
with 
> override a field's template
you mean only the html part right?

**Comment by nickw** [comment]
Yeah, just pass a `templateName` option and create my own HTML template. For instance I might need some different markup for my terms of service checkbox that I don't want/need in my normal checkboxes.

**Comment by splendido** [comment]
this should be easy too...
see [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_input.js#L24-34): if we got a `template` (or `templateName` option we return that one...

**Comment by splendido** [comment]
...but might be error prone because you'll need to give the correct `id` to the input element...

**Comment by nickw** [comment]
I think the way autoform and Telescope do it is to attach the helpers and event handlers using a dynamic template name e.g. `Template[this.templateName].helpers()`, that way if someone uses a custom template they still get all of the built in functionality.

**Comment by splendido** [comment]
:+1: 
I was just thinking to do something like that at init time.

Give me ten minutes ;-)

**Comment by splendido** [comment]
![custominputtemplate](https://cloud.githubusercontent.com/assets/6148980/6069934/c791e9d2-ad88-11e4-9c18-054675512734.png)

**Comment by splendido** [comment]
Done!

```javascript
AccountsTemplates.addField({
  _id: 'terms',
  type: 'checkbox',
  template: "termsCheckbox",
  errStr: "You must agree to the Terms and Conditions",
  func: function(value) {
    console.log("terms validation: " + value);
    console.dir(value);
    return !value;
  },
  negativeValidation: false
});
```

```html
<template name="termsCheckbox">
  <div class="at-input inline field">
    <div class="ui checkbox">
      <input type="{{type}}" id="at-field-{{_id}}" name="at-field-{{_id}}" {{disabled}}>
      <label for="at-field-{{_id}}">
        I've read and agree to the <a href="/terms">Terms and Conditions</a>
      </label>
    </div>
  </div>
</template>
```

Let me know if it works also for you!

**Comment by nickw** [comment]
Yeah that looks perfect - I'll give it a try!

**Comment by splendido** [comment]
Shipped with version `1.7.0`!

Thank you Nick!

**Comment by Levino** [comment]
Good stuff. Just used this. Very handy.

**Comment by guilhermedecampo** [comment]
using still today ;) Thanks guys @splendido @nickw
