### ISSUE TITLE
reset-password

### ISSUE THREAD

**Issue by doubletaketech** [meteor-useraccounts/core#277]
The /reset-password email link is re-directing to login screen (when my home page is set to require login).  I added this code below, but it still prompts the user to login.

Router.onBeforeAction(AccountsTemplates.ensureSignedIn, {
    except: ['atSignIn', 'atChangePwd', 'atForgotPwd','atResetPwd']
});

I have enablePasswordChange: true 

What am I missing?

Thanks,
Don

**Comment by doubletaketech** [comment]
After further debugging, something is adding a /#/ to the link in the email
does not work
http://mine-42275.onmodulus.net/#/reset-password/
works
http://mine-42275.onmodulus.net/reset-password/

**Comment by splendido** [comment]
Hi @doubletaketech,
have yo uconfigured the `resetPwd` route with  `AccountsTemplates.configureRoute`?

See also #266

**Comment by doubletaketech** [comment]
Yes, the restPwd is configured.  Just not sure how the /#/ gets added to the email url.  Stripping it our before sending the email is a good workaround for now.  If /#/ is removed, the resetPwd page loads fine.

**Comment by splendido** [comment]
Lets have a look at the [boilerplates[(https://github.com/meteor-useraccounts/boilerplates)
[This line](https://github.com/meteor-useraccounts/boilerplates/blob/master/bootstrap/lib/config/at_config.js#L5) is where `resetPwd` route is configured, and it used to work without problems...

**Comment by splendido** [comment]
I suppose this is not a bug since it proved to work without problems and I wasn't able to reproduce it.

Thanks for writing.

**Comment by doubletaketech** [comment]
Something is adding the /#/ , in real world production environments. No idea why, but it is bug somewhere.

My workaround is fine for now to strip it out.

Thanks for looking into it.
Don

**Comment by splendido** [comment]
It would be great if you could test the boilerplates within the same production environment...

**Comment by Tim-W** [comment]
Having the exact same issue as @doubletaketech mentioned. The following stackoverflow post may help you (it did for me): http://stackoverflow.com/questions/14130310/how-do-you-change-the-reset-password-url-in-meteor

**Comment by mitar** [comment]
I think the issue is if you are calling configuration only one the client. At least that was the issue for me.

Maybe that is unclear in the documentation? Or I missed something there.

**Comment by knirirr** [comment]
I've been having problems with this and would appreciate any assistance. At present my app, whether running on localhost or deployed to a server, will send out links such as:

    http://localhost:3000/#/reset-password/StuIn9bS-Tu-NYD-gOfO4LJf5BsG_Ul4T_p-ZPWR7FI

This simply directs to the home page with no further effect and removing the '#' results in a 404.

The thread above seems to suggest that in addition to:

    AccountsTemplates.configure({
        ...
        enablePasswordChange: true,
        ...
    })

...one should also have something like `AccountsTemplates.configureRoute('resetPwd')` on both the server and client. I've tried that, and variations, in locations such as:

    lib/config.js
    lib/routes.js 
    server/main.js

...all without the slightest effect. This is using Meteor 1.4.2.6.
I am using FlowRouter and and settings are in lib/config.js.

**Comment by dutu** [comment]
@knirirr are you using it with `{{> atForm}}`?

**Comment by knirirr** [comment]
@dutu I am indeed.
I found out yesterday that the fault is mine for not properly defining defaultLayout in AccountsTemplates.configure, so nothing was rendering when I did define the route and I got the problems mentioned above without the route definition. So, the problem has been resolved for me by something as simple as this:

    defaultLayoutType: 'blaze',
    defaultLayout: 'MainLayout',
    defaultLayoutRegions: { },
    defaultContentRegion: 'content'

**Comment by dpatte** [comment]
I am also having this issue. I am using useraccounts:bootstrap. I am using iron router as my router but have not added useraccounts:iron-routing as for now I have no custom forms. The link in the sent email simply redirects me to the home page. If I remove the extra /#/ iron router says it cannot find the route. 

Oops, looks like there's no route on the client or the server for url: "http://192.168.1.202:3012/reset-password/ABFkwK...."

Should I use useraccounts:iron-routing even if I have no custom forms, and what about the extra '#' in the url in the email?
