### ISSUE TITLE
Authorization form disappears if using accounts-guest package

### ISSUE THREAD

**Issue by buduguru** [meteor-useraccounts/core#280]
I use accounts-guest package so every non-registered user gets its Id and this way she can, for example, comment as guest etc. But if guest goes to sign page the login form is not shown, as it would be if the guest was normally loggedin. So, `useraccounts` considers guest users as loggedin users. 

I posted the same issue in `accounts-guest` repo https://github.com/artwells/meteor-accounts-guest/issues/17, so it could be solved from both.

**Comment by splendido** [comment]
Hi @buduguru,
this is a somehow a duplicate for #223.

Lets see if what I suggested there works fine for you.


This should be put as part of useraccounts@2.0 including a `useraccounts:guest` plugin-pacakge.
Before that time there's not support for this.

Luca

**Comment by buduguru** [comment]
thanks @splendido. Will wait for changes.

**Comment by splendido** [comment]
Ok, I'm glad the patch works!

Tnx!
