### ISSUE TITLE
Double click to register account

### ISSUE THREAD

**Issue by sergical** [meteor-useraccounts/core#281]
Just wondering if the issue ever came up when a user needs to click the register button twice in order to sign up when using the `{{> atForm state="signUp"}}` it's not consistent and I don't get any error messages but sometimes it does happen.

**Comment by splendido** [comment]
Yeah, I think it happend also to me recently.
But I had no time to investigate deeper... :(

Lets keep this open.
Let me know if you have a chance to dig it out ;-)

Tnx!

**Comment by elie222** [comment]
I had the double click error when clicking the forgot password link and also after entering my email and then clicking the reset button. Clicking send new password the first time, just gives a green arrow and clicking it again actually submits the form and sends the reset email.

**Comment by frankapimenta** [comment]
I have a similiar problem.
When logging in it logs out and I have to login in again to be logged in. Maybe this is related to what you specify here?
