### ISSUE TITLE
Improve link location and add _uihook animations?

### ISSUE THREAD

**Issue by Kestanous** [meteor-useraccounts/core#282]
@splendido we have talked about this a little already.

First I think the links should be in the same spot: (Sorry using custom T9n es, my en is broken)
![my_bus_app](https://cloud.githubusercontent.com/assets/1283884/6156634/b3bae74e-b209-11e4-9f4e-a05e3e17bada.png)
![my_bus_app](https://cloud.githubusercontent.com/assets/1283884/6156658/e8cb284a-b209-11e4-84be-a8a96a4b87bb.png)

Second when you click on "Necesita una nueva contraseña?" The password should fade out and the button and link should slide up. Maybe this will not be the default but there should be a way to easily plug animations.

Thoughts? From anyone.

**Comment by splendido** [comment]
Hi Silvi,
sorry for the late reply!

I reckon we should all agree about where each element should be placed to get the best layout and UX.

I'd have no problem to move stuff up and down once some more opinion will be collected :-)

@meteor-useraccounts/core-devs ?

as per the animation hooks it should already be possible to add some `Template.atPwdForm.rendered` callback adding the `_uihook` object to the correct dom element. This is something like what I did with the famous-wrapper: see [this line](https://github.com/meteor-useraccounts/famous-wrapper/blob/master/lib/at_pwd_form_btn.js#L8).

But I think a `useraccounts:animations` would be the best option!
...for v2.0 though ;-)

**Comment by splendido** [comment]
Not sure about how to officially support animations: for now the use of `_uihooks` should be enough?

...in any case module ordering is already possible in the `v2.0` branch.
