### ISSUE TITLE
Follow passwordSignupFields

### ISSUE THREAD

**Issue by benjick** [meteor-useraccounts/core#285]
Hi

Wouldn't it be great if this followed the ```passwordSignupFields``` in the accounts-ui package?

```javascript
Accounts.ui.config({
  passwordSignupFields: 'USERNAME_AND_EMAIL'
});
```

**Comment by splendido** [comment]
Well,
UserAccounts is an alternative to `accounts-ui` and there's no willing to ensure any compatibility among the two.
...I'd say `accounts-ui` should **not** be used together with UserAccounts and that it's probably overkilling adding `accounts-ui` to configure it like you're saying only to get UserAccounts (another, different, stand-alone package) behaving differently...
How mouch code and templates are you pulling in knowing you're not going to use (almost) anything?

This said, if you like to configure 'USERNAME_AND_EMAIL' for UserAccounts, all you need is explained in the [Login with Username or Email](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#login-with-username-or-email) section in the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)

You can also have a look at  at the configuration we're using for Telescope: see [these lines](https://github.com/TelescopeJS/Telescope/blob/devel/lib/config/at_config.js#L12-40).


Cheers,
Luca
