### ISSUE TITLE
Error message not showing after ensureSignedIn

### ISSUE THREAD

**Issue by Danilo-dk** [meteor-useraccounts/core#286]
Hello,

When I have configured a route  like this
```
Router.route('profile', {
    onBeforeAction: AccountsTemplates.ensureSignedIn
});
```
and try to access the page I get the sign-in page as expected. However, when I enter incorrect username or password, the original error message stays the same. So "Must be logged in" instead of "Login forbidden".

By testing it in the boilerplates provided [here](https://github.com/meteor-useraccounts/boilerplates) it seems that it is a bug introduced after those were made. When I clone that repo and log in after a ensureSignedIn has triggered, I get the appropriate message when entering the wrong information. But when I update the meteor packages and try again, I am stuck with the origional error.

**Comment by splendido** [comment]
Ha, I see!

This is a regression introduced with db59f14b5869bebc4cc5cc983b7f887ec3a0207e.

I'll revert back to a working status, but #278 remains unfixed!

I'm starting to realize we'd need to use both `onRun` and `onBeforeAction` to get this working properly...
This can be achieved by [creating an IR plugin](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#creating-plugins)

**Comment by splendido** [comment]
...I've eventually did it:

see e9ee6d27c23377f66badb55b9dc74824a012ed21 and [Content Protection](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#content-protection)
