### ISSUE TITLE
iron-router-progress with ensureSignedIn

### ISSUE THREAD

**Issue by doubletaketech** [meteor-useraccounts/core#287]
This is a compatibility issue with iron-router-progress https://github.com/Multiply/iron-router-progress

I'd like to use your default ensureSignedIn template, but I need to add progress:false to the route so iron-router-progress bar doesn't show up.
AccountsTemplates.configureRoute('ensureSignedIn', {
...
    progress: false
...
});

What should the other settings be to duplicate your defaults?

This is my attempt to force it off at the route level because the global progress: false in Router.config is not working with AccountsTemplates routes only.

Router.configure({
    layoutTemplate: 'masterLayout',
    loadingTemplate: 'loading',
    notFoundTemplate: 'pageNotFound',
    progress:false,
    yieldTemplates: {
        navbar: {to: 'navbar'},
        footer: {to: 'footer'},
        leftMenu: {to: 'leftMenu'},
        rightMenu: {to: 'rightMenu'}
    }
});

Thanks,
Don

**Comment by splendido** [comment]
Hi Don,
lets see [the docs](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#content-protection) for the new plugin version for `ensureSignedIn`.

You can now pass in route options as per the [plugin use documentation](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#plugins)

Might be that this is enough...

Differently you can always set up a custom hook for the routes with (**untested code**):

```javascript
Router.OnBeforeAction(function(){
  this.progress = false;
  this.next();
}, {
  only: ['myRoute1', 'myRoute2']
}
```

**Comment by doubletaketech** [comment]
I gave both options and try, but it did not remove the progress.  

```
Router.configure({
    layoutTemplate: 'masterLayout',
    loadingTemplate: 'loading',
    notFoundTemplate: 'pageNotFound',
    progress:false,
    yieldTemplates: {
        navbar: {to: 'navbar'},
        footer: {to: 'footer'},
        leftMenu: {to: 'leftMenu'},
        rightMenu: {to: 'rightMenu'}
    }
});

Router.onBeforeAction(function(){
    this.progress = false;
    this.next();
}, {
    only: ['app-storage','signIn','atSignIn', 'atSignUp', 'atForgotPassword']
});

if(Meteor.isClient){
    Router.plugin('ensureSignedIn', {progress:false,
        except: ['app-storage','signIn','atSignIn', 'atSignUp', 'atForgotPassword']
    });
}
```
Iron-router-progress ,progress:false, in the Router.configure is supposed to stop it on all routes.  Guess it doesn't see 'ensureSignedIn' at the time it sets this.  Don't know.

I didn't get any response yet from the iron-router-progress folks.

Appreciate the help.
Don

**Comment by splendido** [comment]
Hello there!

The following seems to work like a charm ;-)

```javascript
Router.map(function() {
    this.route('home', {
        path: '/',
    });

    this.route('private');
});

Router.plugin('ensureSignedIn', {
  only: ['private']
});
Router.routes.private.options.progress = false;

Meteor.startup(function(){
  _.each(AccountsTemplates.routes, function(route){
    Router.routes[route.name].options.progress = false;
  });
});
```

I've put this example also on the wiki. See [configurationExamples/iron-router-progress](https://github.com/meteor-useraccounts/wiki/blob/master/configurationExamples/iron-router-progress.md)

**Comment by doubletaketech** [comment]
@splendido , 
My real need is to use progress bar on 'private' routes, IF the user is logged in, ELSE hide it.  I don't want to disable the progress on 'private', I want to disable progress on 'ensureSignedIn' when it is visible. 


Once the user logs in, the the progress will start and show until the data is loaded via the route.


In your code here, you disable it on 'private' all the time.

Make sense?

**Comment by splendido** [comment]
I'll have a better look...

**Comment by splendido** [comment]
I've tried different solutions, including changing a bit the `iron-router-progress` code, but I wasn't able to get to a good solution.

Perhaps you should present to problem to the package maintainers and see whether there's room to adapt it to support your use case?
