### ISSUE TITLE
Feature Design: Select-multiple Field Type

### ISSUE THREAD

**Issue by etmarch** [meteor-useraccounts/core#289]
Would it be difficult to allow a field type of "select-multiple" to be used? Something like this: http://autoform.meteor.com/types. In my "Users" schema, I have 2 fields that are validating for arrays of strings (type: [String]), and it would be great if I could specify a multiple-select, instead of just select. Thanks.

**Comment by splendido** [comment]
Hei @etmarch,
could you please try to play around with the new `template` options for input fields?

Lets see #273 and [this](https://github.com/meteor-useraccounts/core/issues/273#issuecomment-73137378) and [this](https://github.com/meteor-useraccounts/core/issues/245#issuecomment-74470850)  examples.

Should be enough to change the select element in your custom template...

Let me know!

**Comment by etmarch** [comment]
Hi Splendido,

I will try to format the examples you linked in a way that can work for my needs, but I think it will be a bit more complicated than those. I'll give it a shot and let you know.
