### ISSUE TITLE
How to return a calculated value at validation?

### ISSUE THREAD

**Issue by GiraffeSlacks** [meteor-useraccounts/core#290]
Hello,

I'm new to Meteor and Javascript in general so forgive me if this question is very basic.

I've created the following `addfield()` statement using the documentation.

(Before I forget, I just want to thank all the contributors to this project because it is a really valuable one.)

```javascript
AccountsTemplates.addField({
  _id: "fulltimeAnniversary",
  type: "text",
  displayName: "Employment Hire Date",
  placeholder: {
    signUp: "[mm/dd/yyyy]"
  },
  required: true,
  func: function (value) {
    console.log(moment(value, 'MM-DD-YYYY', true).isValid());
    if(moment(value).isValid()) {
      return false;
    }
    return true;
  },
  errStr: 'Date must be in the format mm/dd/yyyy.',
});
```

What I want to do is return `moment()._d` (a well-formatted date string) when validation passes so that it is stored in the database rather than what the user typed.

Apologies if the documentation already covers this but I'm afraid I'm not seeing it.

**Comment by GiraffeSlacks** [comment]
How do I apply a label?

**Comment by splendido** [comment]
Hi @GiraffeSlacks!
It's not a noob question at all ;-)

for your use case, I guess the best option is to leverage the `transform` option with something like this (**untested code**):

```javascript
AccountsTemplates.addField({
  _id: "fulltimeAnniversary",
  type: "text",
  ...
  transform: function(value) {
    if(moment(value).isValid()) {
      return moment(value)._d;
    }
    else {
      return value;
    }
  }
});
```

the only thing is that the `transform` you specify will be applied also on field validation which means that the user will see the input field content changing...

Let me know if this suites your needs

**Comment by GiraffeSlacks** [comment]
Hi @splendido. Thanks for answering my question.

Now that you explained it, I don't think this will work in this case because I don't want the user to see it. But I can see this working in some other cases.

Then I guess I just have to do the transform when I insert/update, right?

**Comment by splendido** [comment]
Ha, I see...

might be some other option to consider to add...
But in general you can use [Accounts.onCreateUser](https://docs.meteor.com/#/full/accounts_oncreateuser) to do this kind of *transforms* plus other addition to a new user object.

The only problem is that `Accounts.onCreateUser` can be called noly once!
...and some packages abuse it. Not UserAccounts tough ;-)

Let me know if you manage to get it working

**Comment by GiraffeSlacks** [comment]
I haven't gotten it to work. Here's a different use case.

```javascript
AccountsTemplates.addField({
  _id: "etoBalance"
  , type: "text"
  , displayName: "Current ETO Balance"
  , placeholder: {
    signUp: "How many hours do you currently have?"
  }
  , required: true
  , transform: function (value) {
    return value * 60;
  }
  , func: function (value) {
    if (!(typeof value === 'number' && (value % 1) === 0)) {
      //// data is an integer
      //return true;
      return false;
    }
  }
  , errStr: 'Use whole numbers only.'
});
```

`etoBalance` is stored in minutes but I ask the user to enter hours because it's much easier for them. My intent is to do the multiplication for them when the validation passes. But instead of 600 in the db (for an entered value of 10) I get 10. The transform is not transforming. (More likely I'm doing something wrong.)

**Comment by splendido** [comment]
This is kind of a working version:

```javascript
AccountsTemplates.addField({
  _id: "etoBalance",
  type: "text",
  displayName: "Current ETO Balance",
  placeholder: {
    signUp: "How many hours do you currently have?"
  },
  required: true,
  transform: function (value) {
    return String(value * 60);
  },
  func: function (value) {
    value = Number(value);
    if (value !== parseInt(value, 10)) {
      return true;
    }
    return false;
  },
  errStr: 'Use whole numbers only.'
});
```


But as I expected, the input value is changed on validation, which is not a good UX.


I'd say the right way to do this is the following:

```javascript
AccountsTemplates.addField({
  _id: "etoBalance",
  type: "text",
  displayName: "Current ETO Balance",
  placeholder: {
    signUp: "How many hours do you currently have?"
  },
  required: true,
  func: function (value) {
    value = Number(value);
    if (value !== parseInt(value, 10)) {
      return true;
    }
    return false;
  },
  errStr: 'Use whole numbers only.'
});
```

and on the server-side:

```javascript
Accounts.onCreateUser(function(options, user) {
  if (options.profile) {
    user.profile = options.profile;
    if (user.profile.etoBalance) {
      // Transforms minutes to seconds...
      user.profile.etoBalance = user.profile.etoBalance * 60;
    }
  }
  return user;
});
```

This covers user registration, then you'll have to deal with further transforms in case you let the user update his ETO balance.

**Comment by GiraffeSlacks** [comment]
(I'm writing this before having a chance to try it.) Thank you very much!

**Comment by GiraffeSlacks** [comment]
@splendido Worked perfectly. :)

**Comment by splendido** [comment]
Good!
