### ISSUE TITLE
No plugin found named "ensureSignedIn" on server-side

### ISSUE THREAD

**Issue by thomasspiesser** [meteor-useraccounts/core#291]
Hi,
first of all, thanks for the great package! 
I have a small problem. When I tried to migrate to the new plugin version of ensureSignedIn, I got this:

    Error: No plugin found named "ensureSignedIn"

Do I need to load the plugin or am I missing something?

This is the function I used in at_config.js in /lib

```javascript
Router.plugin('ensureSignedIn', {
    only: [ 'here', 'there' ]
});
```

**Comment by splendido** [comment]
Hi @thomasspiesser,
there's a small big with it we already discussed with #278.

At the moment it is defined only for the client side, I'll publish a patch for this tomorrow!

**Comment by thomasspiesser** [comment]
oh alright. thanks for the quick reply.

**Comment by splendido** [comment]
for now simply wrap the call inside a 

```javascript
if (Meteor.isClient) {
  Router.plugin('ensureSignedIn', {
      only: [ 'here', 'there' ]
  });
}
```

**Comment by rdrey** [comment]
Hah, just ran into this issue, too. Thanks for reacting to these issues so quickly @splendido!

**Comment by rdrey** [comment]
I'm still getting this even when I wrap the call in `Meteor.isClient`:

    if Meteor.isClient
      console.log Iron.Router.plugins
      Router.plugin 'ensureSignedIn',
          only: [ 'reviewItemCreate' ]

this logs:

    > Object {loading: function, dataNotFound: function}

But the 'ensureSignedIn' plugin is missing. I just ran `meteor update` and am on 

    useraccounts:core     upgraded from 1.7.0 to 1.8.0
    useraccounts:polymer  upgraded from 1.7.0 to 1.8.0

Thanks!

**Comment by splendido** [comment]
See version `1.8.1`

thank you all for reporting!

**Comment by jhmacdon** [comment]
Hi,

I just cloned the boilerplate and I am still getting this issue, but only on MUp?

**Comment by splendido** [comment]
Ok, we'll have to dig it more... :(

**Comment by jhmacdon** [comment]
Actually I fixed it. I am not sure exactly what it was (I was trying many things) but I think it was wrapping in the Meteor.isClient

**Comment by jimmiebtlr** [comment]
I'm also experiencing this.  Same version, v1.8.1 instead of 1.8.0.  I've also tried putting it in a Meteor.startup call, which did not help.

**Comment by splendido** [comment]
Ok, I've deployed the lates version of the boilerplates on:
* http://useraccounts-bootstrap.meteor.com/
* http://useraccounts-materialize.meteor.com/
* http://useraccounts-semantic-ui.meteor.com/

and everything seems fine!

I'll try do deploy with MUP on a DO droplet and see what happens...

If you could make a very simple reproduction (with an empty app and without using useraccounts) with a very simple IR plugin, we might think to open an issue for IR!

just confirming this is the same as #294, right?

**Comment by jhmacdon** [comment]
I cloned this again and deployed to a brand new DO droplet, no errors and everything seems good. 

My meteor might have been outdated or something earlier, not sure.

**Comment by splendido** [comment]
good news then!
Let's still keep an eye on this...

**Comment by sagarjs** [comment]
I got this same error today. I am on the latest Meteor on Windows and all my packages are up to date.

It worked when i wrapped it in the Meteor.isClient block

**Comment by KrishnaPG** [comment]
Started getting the same error after latest meteor update on Windows
````
semantic:ui                upgraded from 2.0.7 to 2.0.8
semantic:ui-data           upgraded from 2.0.7 to 2.0.8
useraccounts:bootstrap     upgraded from 1.11.1 to 1.12.1
useraccounts:core          upgraded from 1.11.1 to 1.12.1
````
Getting this below error:
````
W20150812-18:40:06.912(5.5)? (STDERR) You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!

W20150812-18:40:06.943(5.5)? (STDERR)
W20150812-18:40:06.943(5.5)? (STDERR) C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150812-18:40:06.943(5.5)? (STDERR)
throw(ex);
W20150812-18:40:06.943(5.5)? (STDERR)
      ^
W20150812-18:40:06.943(5.5)? (STDERR) Error: No plugin found named "ensureSignedIn"
W20150812-18:40:06.943(5.5)? (STDERR)     at Function.Router.plugin (packages/iron:router/lib/router.js:394:1)
W20150812-18:40:06.943(5.5)? (STDERR)     at lib\_config/router.coffee:33:8
W20150812-18:40:06.943(5.5)? (STDERR)     at lib\_config/router.coffee:1:1
W20150812-18:40:06.943(5.5)? (STDERR)     at \.meteor\local\build\programs\server\boot.js:222:10
W20150812-18:40:06.943(5.5)? (STDERR)     at Array.forEach (native)
W20150812-18:40:06.943(5.5)? (STDERR)     at Function._.each._.forEach (\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150812-18:40:06.943(5.5)? (STDERR)     at \.meteor\local\build\programs\server\boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
````
It was working fine earlier before the update !

**Comment by bmx269** [comment]
I too am having this error. Thanks.

**Comment by eddieconk** [comment]
I just updated Meteor and am having the same error. ^

**Comment by KrishnaPG** [comment]
Instead, try doing `meteor add useraccounts:iron-routing` - it seems this new package is needed now

**Comment by eddieconk** [comment]
That got my project to build! Thank you, however semantic UI is visually much different and buggy now.

**Comment by bluepuma77** [comment]
`if (Meteor.isClient) {}` got my [meteor-boilerplate](https://github.com/Differential/meteor-boilerplate) working again after `meteor update`, as in not crashing, but `ensureSignedIn` wasn't working, letting me in without being signed in. @KrishnaPG's `meteor add useraccounts:iron-routing` fixed it for me.

**Comment by sebastianconcept** [comment]
Hare! @KrishnaPG 
thanks for that tip!
`meteor add useraccounts:iron-routing` fixed it for me too

**Comment by array-addu** [comment]
After updating my meteor to version 1.2.1, i'm not getting Meteor.user() however Meteor.userId() sill returning user ID.
