### ISSUE TITLE
Route protection doesn't work in case subscription without publishing

### ISSUE THREAD

**Issue by pronevich** [meteor-useraccounts/core#295]
Hi, I noticed a strange behavior, when we have subscription that hasn't been published. In my case in route waitOn hook:

```javascript
Router.route('/admin', {
  controller: 'SomeController',
  waitOn: function () { return Meteor.subscribe('notPublishedSubs'); },
  action: function() {
    this.render('admin');
  }
});
```

and all routes protected with

```javascript
Router.plugin('ensureSignedIn', {
    except: ['atSignIn', 'atSignUp', 'atForgotPassword']
});
```

in that case you have access to /admin page and it is not protected and route template will be rendered.

**Comment by splendido** [comment]
I'll try to invetigate this.
I would be great if you had a clonable repo reproducing this...

Thanks for the heads up!

**Comment by splendido** [comment]
any updates on this?
I had no chance to dig into this... :(

**Comment by pronevich** [comment]
Sorry, I forgot about this issue. I tried to reproduce, but didn't get the same result. I think this problem is not in useraccounts specifically, what I can see now is that iron-router shows only loading template because it's waiting for subscription and useraccounts can't show atForm template in this case. We don't have an error message from iron-router and meteor itself  "on not published subscription" and this stupid mistake should be found by developer.

**Comment by splendido** [comment]
Ok, so I'm going to close this.
Let me know if it pops up again and useraccounts could be blamed for it...

Tnx!
