### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by c316** [meteor-useraccounts/core#297]
Is it possible to save the URL that the user was on when they clicked the login button, then redirect them back to that URL when they finish logging in?

Also, do you have any advice for saving form inputs from before the login and after the redirection? 

Thanks

**Comment by splendido** [comment]
The redirect logic you're asking for should work out of the box...
isn't it working?
lets ahve a look at some live example you can find starting from [useraccounts.meteor.com](https://useraccounts.meteor.com)

To cache some form input, I'd try to use `onRun` and `onStop` IR hooks, but it mostly depends on where you wish to save them...

**Comment by c316** [comment]
Looks like I had a redirect statically set so that is why it wasn't working. Thanks

**Comment by splendido** [comment]
You're welcome!
