### ISSUE TITLE
Username validation message

### ISSUE THREAD

**Issue by nickw** [meteor-useraccounts/core#299]
This is a very user-unfriendly error message, and for the life of me I can't figure out how to change it:

> Username failed regular expression validation

This is what my config looks like:

```
AccountsTemplates.addFields([
  {
    _id: 'username',
    type: 'text',
    displayName: 'Username',
    placeholder: 'Choose a username',
    required: true,
    errStr: 'Username can only be one word.'
  },
  {
    _id: 'email',
    type: 'email',
    required: false,
    displayName: 'email',
    placeholder: 'Email (optional)',
    re: /.+@(.+){2,}\.(.+){2,}/,
    errStr: 'Please enter a valid email.'
  },
  {
    _id: 'username_and_email',
    type: 'text',
    displayName: 'usernameOrEmail',
    placeholder: 'usernameOrEmail',
    required: true,
  },
  passwordField
]);
```

**Comment by splendido** [comment]
mmm, I'm almost sure it's not coming from UserAccounts...
Let me dig a little more!

**Comment by splendido** [comment]
Where are yo getting it from, signIn or signUp?

**Comment by splendido** [comment]
...also, you might be interested in the new `lowercaseUsername` option which keeps the *original* username under `profile.username` but behind the scenes converts the actual username to lowercase and removes all spaces appearing inside it...

I'm trying to set this up for Telescope!

**Comment by nickw** [comment]
> mmm, I'm almost sure it's not coming from UserAccounts...

Yeah it's very strange that I couldn't find that string in any of the codebases

> Where are yo getting it from, signIn or signUp?

signUp

> Btw, I'm not seeing any RegExp in your username fields. Do you have any?

Nope, I assumed your package had a default regex for usernames?

**Comment by splendido** [comment]
No defaults for username....

I've searched among the account packages and there's nothing about it!

Do you have any other package among the installed ones that might be checking the username?

**Comment by nickw** [comment]
Found it - somebody had added a regex to our simple schema. Thanks for the heads up on `lowercaseUsername`, I'm going to look into that option.

**Comment by splendido** [comment]
Ok, good!
