### ISSUE TITLE
How rewrite a template like `at_form.html`?

### ISSUE THREAD

**Issue by bySabi** [meteor-useraccounts/core#300]
Hello. 
I was trying to customize `atForm` template, basicaly change layout and nested template order.
Testing with a local package. 
```
Package.describe({
  summary: "Add external login providers. Change! keys per project",
  version: "1.0.0",
  name: "external-login-providers"
});

Package.onUse(function (api) {
	api.use([
	"accounts-google",
	"accounts-facebook",
	"accounts-twitter",
	"service-configuration",
	"useraccounts:bootstrap"
	], ["client", "server"]);

	api.use([
		"less",
		"templating"
	], "client");

	api.addFiles([
		"lib/at_form.html",
		"lib/at_bootstrap.less"
	], ["client"]);

	api.addFiles([
		"server/accounts/config.js"
	], ["server"]);

});
```
We this aproach I can change CSS on atForm whith custom `at_bootstrap.less` but I can´t rewrite/customize `at_form.html`. 
What I do wrong??

**Comment by splendido** [comment]
Well, I don't think you need to roll up a new package to do this!
...btw, I guess it's not working because you're missing a lot of files.

If the main aim is to change [`atForm`](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_form.html) Template, lets try to have a look [here](https://github.com/meteor-useraccounts/core/issues/212#issuecomment-67810815).

define e new `myAtForm` template (e.g. moving error messages above social buttons):

```html
<template name="myAtForm">
  {{#unless hide}}
    <div class="at-form">
      {{#if showTitle}}
        {{> atTitle}}
      {{/if}}
      {{#if showError}}
        {{> atError}}
      {{/if}}
      {{#if showResult}}
        {{> atResult}}
      {{/if}}
      {{#if showOauthServices}}
        {{> atOauth}}
      {{/if}}
      {{#if showServicesSeparator}}
        {{> atSep}}
      {{/if}}
      {{#if showPwdForm}}
        {{> atPwdForm}}
      {{/if}}
      {{#if showTermsLink}}
        {{> atTermsLink}}
      {{/if}}
      {{#if showSignInLink}}
        {{> atSigninLink}}
      {{/if}}
      {{#if showSignUpLink}}
        {{> atSignupLink}}
      {{/if}}
    </div>
  {{/unless}}
</template>
```

and than replace the original one with:

```javascript
Template.myAtForm.replaces("atForm");
```

That's it!

...for the LESS/CSS it should be enough to define new rules to get them overwriting the original ones.


Cheers,
Luca

**Comment by bySabi** [comment]
Thanks @splendido, this work!!!
I need a package for reuse in other projects.
Now I have this:
```
Package.describe({
  summary: "Add external login providers. Change! keys per project",
  version: "1.0.0",
  name: "external-login-providers"
});

Package.onUse(function (api) {
	api.use([
		"accounts-google",
		"accounts-facebook",
		"accounts-twitter",
		"service-configuration",
		"useraccounts:bootstrap",
		"aldeed:template-extension"
	], ["client", "server"]);

	api.use([
		"less",
		"templating"
	], ["client"]);

	api.imply([
		"aldeed:template-extension@3.1.1"
	], ["client", "server"]);

	api.addFiles([
		"lib/my_at_form.html",
		"lib/my_at_form.js",
		"lib/at_bootstrap.less"
	], ["client"]);

	api.addFiles([
		"server/accounts/config.js"
	], ["server"]);

});
```
Thanks again for your time and hard word on  `meteor-useraccounts`

**Comment by splendido** [comment]
Glad it worked!

Thanks

**Comment by derwaldgeist** [comment]
Thanks a lot for this tip! I always wondered how I could replace the standard templates of the accounts system in an elegant way. Was not aware of the replaces() functionality.

**Comment by splendido** [comment]
well, `replaces` is actually added by [aldeed:template-extension](https://atmospherejs.com/aldeed/template-extension) , lets have a look at [this comment](https://github.com/meteor-useraccounts/core/issues/212#issuecomment-67810815) for the whole story.
