### ISSUE TITLE
Translate / Change "Login Forbidden"

### ISSUE THREAD

**Issue by Kestanous** [meteor-useraccounts/core#301]
Apologies if this has been solved already but is there any way to change the "login forbidden" error message? We need it to be more descriptive and available in multiple languages.

See: https://github.com/meteor-useraccounts/core/blob/f078f8cb81adeb83e23355f860c7e4ca0b910247/lib/server.js#L80

**Comment by splendido** [comment]
Hello there!

Yep, simply change the mapping on accounts-t9n! ;-)

lets have a look at [this comment](https://github.com/meteor-useraccounts/core/issues/216#issuecomment-68129224)

**Comment by splendido** [comment]
Btw, I appreciate this should be another error text to be possibly configured!

**Comment by splendido** [comment]
Ok, done! See c963bbb5fbeab88e9398404ab002360f48c47eec

Now you can choose whether to change T9n values associated to `error.accounts.Login forbidden` of to configure a new text with

```javascript
AccountsTemplates.configure({
  texts: {
    errors: {
      loginForbidden: "error.accounts.myDescriptiveError"
    }
  }
});
```

and then provide translations for other languages with:

```javascript

var myDescriptiveError = {
  en: 'EN text',
  es: 'ES text',
  it: 'IT text',
};
_.each(myDescriptiveError, function(value, key){
  T9n.map(key, {'error.accounts.myDescriptiveError': value});
});
```
