### ISSUE TITLE
Send email verification to an existing account

### ISSUE THREAD

**Issue by 416serg** [meteor-useraccounts/core#302]
We are trying to implement email verification for our users. I've enabled `sendVerificationEmail: true` and it works fine for new creating account. However, existing users that have signed up before get a `Please verify your email first. Check the email and follow the link!` Is there a way for me to send the verification link to those?

**Comment by splendido** [comment]
Lets have a look at [Accounts.sendVerificationEmail](https://docs.meteor.com/#/full/accounts_sendverificationemail

It should be enough to cycle over your users at server startup and send out a new verification email for each one...

You can also check whether an email address is already verified by looking at the `user.emails` field which is an array of objects like this:

```javascript
user: {
  emails: [
    {address: "pippo@example.com", verified: false},
    {address: "pluto@example.com", verified: true},
  ]
}

**Comment by 416serg** [comment]
@splendido worked fine, thanks :)
