### ISSUE TITLE
Adding translation to a addField

### ISSUE THREAD

**Issue by QuentinEliga** [meteor-useraccounts/core#303]
Hey, I have a question, I don't if it's doable but it worth the try to ask ^__^

I add field with the configuration of AccountsTemplates, and I'm confronting some issue about the translation.

I really want to keep the translation in english to this fields, but also have the ability to translate them in french. So I try to call the T9n.get in the placeholder, but it's not working. It display username every time when I'm want to display "Nom d'utilisateur" in french and "Username" in english. Same thing for password.

    //Fields
    AccountsTemplates.addField({
        _id: "username",
        type: "text",
        displayName: T9n.get('username'),
        placeholder: {
            signUp: T9n.get('username'),
            signIn: T9n.get('username'),
        },
        required: true,
        minLength: 3,
        trim: true,
        errStr: 'error.minChar'
    });

    AccountsTemplates.removeField('email');
    AccountsTemplates.addField({
        _id: 'email',
        type: 'email',
        required: true,
        re: /.+@(.+){2,}\.(.+){2,}/,
        errStr: 'error.accounts.Invalid email',
        trim: true,
        lowercase: true
    });

    AccountsTemplates.removeField('password');
    AccountsTemplates.addField({
        _id: 'password',
        type: 'password',
        displayName: T9n.get('password'),
        placeholder: {
            signUp: T9n.get('password')
            signIn: T9n.get('password'),
        },
        required: true,
        minLength: 4,
        errS
});

I don't know if I miss something, but I be very grateful if I you have a solution for me ^___^

Thanks, for your time

**Comment by splendido** [comment]
It should work out of the box! Isn't it?
See [I18n Support](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#i18n-support) and the note about `t9n` at the and of the parameters' table in [Form Fields Configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration)

Also, username is already defined for French [here](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/fr.coffee#L40)

So:

```javascript
AccountsTemplates.addField({
    _id: "username",
    displayName: 'username',
    placeholder: 'username',
    type: "text",
    required: true,
    minLength: 3,
    trim: true,
    errStr: 'error.minChar'
});
```

should be enough ;-)
Let me know!

**Comment by splendido** [comment]
...actually I've just realized that the default behaviour for `displayName` and `placeholder` (which is "fall back to capitalized _id in case not explicitely provided") might be breaking the translation stuff :(

See #304

**Comment by QuentinEliga** [comment]
Yes, I try your first solution. It's actually not working. 

I think you're right, the translation might be broken in the addField.

I didn't find any alternative, for now.

Hope, it will be fix someday. 

Thank you for your answer ^__^

**Comment by splendido** [comment]
Well, it's actually working for Telescope (see the [configuration for username](https://github.com/TelescopeJS/Telescope/blob/devel/lib/config/at_config.js#L13-20)).
So I guess it should be consistent also for the `placeholder`

To test it, go to [crater.io/register](http://crater.io/register) open the console and type `T9n.setLanguage('fr')`

**Comment by QuentinEliga** [comment]
The label on top of the input are translating, but not the placeholder, on crater.io.

I remove the label in the account. The only indication for my users it's the placeholder. 

Sorry, if I'm a bit annoying. But it's kind of important ^^

Anyway, thank you for taking the time to answer me

**Comment by splendido** [comment]
..yep, that's why I suppose that if you also set `placeholder: username` is should work as it is doing for `displayName`.

I'm sorry I have no time to test it myself at the moment... :(
Could you try to follow the two *paths* for `displayName` and `placeholder`: if I'm not wrong they should be (almost) identical...

**Comment by QuentinEliga** [comment]
It works ! Thank you very much.

Indeed, I just needed to set the placeholder to the same variable than the id and the DisplayName.

Here my final code, if anyone is interested

 //Fields
    AccountsTemplates.addField({
        _id: "username",
        type: "text",
        displayName: "username",
        placeholder: {
            signUp: "username",
            signIn: "username"
        },
        required: true,
        minLength: 3,
        trim: true,
        errStr: 'error.minChar'
    });

    AccountsTemplates.removeField('email');
    AccountsTemplates.addField({
        _id: 'email',
        type: 'email',
        required: true,
        re: /.+@(.+){2,}\.(.+){2,}/,
        errStr: 'error.accounts.Invalid email',
        trim: true,
        lowercase: true
    });

    AccountsTemplates.removeField('password');
    AccountsTemplates.addField({
        _id: 'password',
        type: 'password',
        displayName: "password",
        placeholder: {
            signUp: "password",
            signIn: "password",
            changePwd: "password"
        },
        required: true,
        minLength: 4,
        errStr: 'error.minChar'
    });

**Comment by splendido** [comment]
Ok, good!
...but hence we're confirming that #304 is actually a bug! :-(

I'm closing this to keep tacking on the other issue.

Thanks!

**Comment by guoyoujin** [comment]
"placeholder: {
        signUp: T9n.get('password')
        signIn: T9n.get('password'),
    },'

Less a comma

**Comment by splendido** [comment]
@guoyoujin, I'm not sure that solution would preserve reactivity wrt language change...
Is it working for you?

**Comment by guoyoujin** [comment]
@splendido Can the custom login, is all the login interface with your own custom

**Comment by splendido** [comment]
I'm sorry, I don't understand...
