### ISSUE TITLE
where are custom fields stored?

### ISSUE THREAD

**Issue by kevohagan** [meteor-useraccounts/core#305]
im having a problem where i cant track where the custom fields i defined are stored.
I have them on signup (required: true also) , and all works, its only that they dont seem to be attached to the user object.
Im probably missing something here.. 

Help @splendido ! :)

**Comment by splendido** [comment]
Hi Kevin!
custom fields are put into `user.profile` on registration.
Make sure your AT configuration is inside a client/server shared file and that you publish the profile field to the client (if needed).

For sure if you check the mongo document you should see everything under `user.profile`!

Let me know

**Comment by kevohagan** [comment]
Okay i see where the problem is:

basically im using core-selector with polymer for the ATSelectInput

problem is here on the Field.Prototype.getValue :

```javascript

if (Meteor.isClient)
    Field.prototype.getValue = function(tempalteInstance){
        if (this.type === "checkbox")
            return !!(tempalteInstance.$("#at-field-" + this._id + ":checked").val());
        if (this.type === "radio")
            return tempalteInstance.$("[name=at-field-"+ this._id + "]:checked").val();
        return tempalteInstance.$("#at-field-" + this._id).val();
    };

```

the ``` .$("#at-field-" + this._id).val()``` doesnt return the proper value because of core-selector.

unfortunately im not really sure on hwo to override this

**Comment by splendido** [comment]
How are you supposed to take the value from the polymer select?

**Comment by kevohagan** [comment]
element.selected

**Comment by kevohagan** [comment]
problem is this shouldnt go into core! i did a really horrible hack where i
listen to the change method on the polymer element and set the .val()
dynamically. like that validation doesnt fail

**Comment by splendido** [comment]
Is there any chance yoy can use jQuery `element.selected()` for all select inputs?
...don't even know if it exists ;-)

**Comment by splendido** [comment]
Hey Kevin,
lets have a look at #311!

I think [the proposed solution](https://github.com/meteor-useraccounts/core/issues/311#issuecomment-78856641) should work also for your usecase!
It's not that elegant, but nor that bad ;-)

**Comment by splendido** [comment]
...should we change the title?

**Comment by splendido** [comment]
Closing down...
