### ISSUE TITLE
Social login buttons take a long time to load

### ISSUE THREAD

**Issue by fardeemmunir** [meteor-useraccounts/core#306]
When the page loads, the normal form fields are there but it takes a while for the facebook button to appear. I think its something true for OAuth related services. Any ideas on how to fix this?

**Comment by splendido** [comment]
Yeah, that's it!
The thing is that the list of available/configured services come from a meteor collection which takes a bit of time to reach the client at first load...

The only solution I might suggest to investigate is about using [fast-render](https://atmospherejs.com/meteorhacks/fast-render)

Let me know how it goes!
