### ISSUE TITLE
Signups forbidden from client connected using DDP.connect()

### ISSUE THREAD

**Issue by PolGuixe** [meteor-useraccounts/core#309]
I am having problems to signup new users from a client that it is connected using DDP.connect(). No problem when login with existing users. I can even change the password from this client. 

This is the code I am using to make the DDP connection the Accounts connection: 

``` javascript
if (Meteor.isClient) {
 Meteor.connection = DDP.connect('http://localhost:3030/');
 Accounts.connection = Meteor.connection;
 Meteor.users = new Meteor.Collection('users');
 Meteor.connection.subscribe('users');
}
```

The test project is basically the one created with `meteor create 'project_name'`. I added the `accounts-password` and the `accounts-ui` packages. Then I am using {{> loginButtons}} for the interface. Nothing else has been modified. 

**any ideas why the new signups are forbidden?**

**Comment by PolGuixe** [comment]
Moved to https://github.com/meteor/meteor/issues/3909

**Comment by splendido** [comment]
so, where you using `useraccounts` packages in any way?

**Comment by PolGuixe** [comment]
Not in this project,yet. I just placed here and quickly realised that was the wrong place. That's why I moved. Sorry.

**Comment by splendido** [comment]
no worries!

tnx

**Comment by PolGuixe** [comment]
I may have a problem with this package. I am not using `usersaccounts` on the new client yet. However on the project that I am using as a host, and to which I am connecting, I am using `useraccounts:ionic`.

Between simple project the DDP connection and Accounts connection works perfectly fine: see https://github.com/meteor/meteor/issues/3909

Do you think that there might be a conflict between `accounts-ui` and `useraccounts`?

**Comment by PolGuixe** [comment]
I have added the `useraccounts:bootstrap` into the client project. And now the error message is "login forbidden" when I try to register a new user.

**Comment by splendido** [comment]
Hei @PolGuixe, about any kind of compatibility with `accounts-ui` read this [post](https://github.com/meteor-useraccounts/core/issues/285#issuecomment-74865309). May sounds a bit rude, but that's it ;-)

**Comment by splendido** [comment]
I've never tried the packages with a DDP connection, so I cannot be of much help here...
The only think might be that to create new accounts UA calls a server method which is [ATCreateUserServer](https://github.com/meteor-useraccounts/core/blob/master/lib/methods.js#L20): lets try to make sure you can access this method through the DDP connecction.

for the rest, it's all about standard calls to `Accounts` methods, like `Accounts.loginWithPassword`, etc.

**Comment by PolGuixe** [comment]
@splendido I am not looking for compatibility. I just want to link two projects with DDP and get the users working with `useraccounts`. I have set-up two basic projects:
* Client: https://github.com/PolGuixe/DDP_test
* Host: https://github.com/PolGuixe/DDP_test_host

*In both projects the master branch uses `accounts-ui` and the useraccounts branch uses `useraccounts`.*

Do you mind having a look? Surely you can identify the errors quicker than I do. I can provide support if required. 

Many thanks,

**Comment by splendido** [comment]
I had a quick look at it... and I managed to get it working :-)

The problem was that `Meteor.call` was calling methods on the client server (the one listening on port 3000), and not on the host server (the one on port 3030). So the new user was created on the wrong database and subsequent `Meteor.loginWithPassword` was not finding any user (on the host server db...).


This is because you're supposed to user `.call` on the remote connection to get methods called down there...

So I ended up with this super hack:

```javascript
if (Meteor.isClient) {
  remote = DDP.connect('http://localhost:3030/');
  Meteor.call = function(){
    return remote.call.apply(remote, arguments);
  };

  Accounts.connection = remote;
  Meteor.users = new Meteor.Collection('users', remote);
  remote.subscribe('users');
}
```

which seems to be working correctly!
I guess this is work a post somewhere ;-)

**Comment by PolGuixe** [comment]
@splendido Amazing!!! 

Right now I am away from my computer, but this afternoon I'll give it a try. ;)

**Comment by PolGuixe** [comment]
Ok I can confirmed that it works like a charm. ;)

**Comment by splendido** [comment]
A new meteor hack has been learned! ;-)

...do you feel any smell of a bug?
Hacking on `Meteor.connection` or trying `Meteor.connect` didn't worked....

**Comment by PolGuixe** [comment]
... its a good point. I also opened an issue here: https://github.com/meteor/meteor/issues/3909

I´ll raise this observation.
