### ISSUE TITLE
Use two useraccounts package in one app: Choose form version

### ISSUE THREAD

**Issue by AndreasGalster** [meteor-useraccounts/core#312]
I have an app which has a route for android (which is a webview in an android .apk app) and other routes for the web browser based part of the web. When I go to my android route I want to login with the polymer package, when I go to any other non-android routes I want to use the bootstrap package. I don't think this is possible right now?

**Comment by splendido** [comment]
Hello @AndreasGalster!

this is not supported out of the box, but there might be a very tricky solution. This is my idea:

* first, forget about using `AccountsTemplates.configureRoute` to set up your routes!
* set up the Android route 'by hands' with a custom template using `{{>atForm}}': this should make the signIn/Up states available on the very same route.
* copy by hands the code for the other UI framework and rename all templates to eventually get a `atForm2` or whatever and use it inside the template for the route you set up for the web browser
* ...good luck! ;-)

Let me know!

**Comment by AndreasGalster** [comment]
This sounds confusing but I could try it :P However, I think there are problems with two different packages being used in general. This seems to be logging the user out sometimes right after being logged in.

**Comment by splendido** [comment]
What you mean with:
> there are problems with two different packages being used in general

which two packages?
I'm almost sure you cannot install two useraccounts packages without getting an error about having duplicate template names...

**Comment by AndreasGalster** [comment]
Exactly. There were templating issues and also some error with logging.js I think. I installed useraccounts:bootstrap and useraccounts:polymer. Didn't exactly work flawless sadly. I'd love to have the possibility to have 2 userpackages installed at once in the future though.

**Comment by splendido** [comment]
Right now this is not possible because all different frontend templates actually use the same names...

But I'll try to consider this for v2.0! It might make sense... ;-)

**Comment by splendido** [comment]
if you set up a public repo to play a bit with this, I can try to make a PR to get you started off...

**Comment by AndreasGalster** [comment]
Hi splendido, thanks for the offer but right now that project has no priority. I'm ok with just using the bootstrap login for now. It's a long term side project, so I'm hoping v2.0 will be there when I really need it :).

**Comment by splendido** [comment]
Ok, so I'll close this for now.
But I'll take this into consideration for v2.0!

Tnx
