### ISSUE TITLE
Change ensureSignedIn message?

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/core#314]
The login page that is shown with ensureSignedIn has an error message that is not always relevant in my app. Many times it is too harsh to show the user, but preferably, I would like to show a custom message.

How can this be achieved?

**Comment by splendido** [comment]
Hi @dalgard,
`ensureSignedIn` uses `AccountsTemplates.texts.errors.mustBeLoggedIn` ad the error to be displayed.
So you can do:

```javascript
AccountsTemplates.configure({
    texts: {
        errors: {
            mustBeLoggedIn: "Your custom message",
        }
    }
});
```

But be aware that this would break any internationalization support.

See [Configuring Errors Text](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#errors-text)

**Comment by splendido** [comment]
Do you think it could be useful to have the `ensureSignedIn` plugin take an additional option to allow for the the error message to be set on a per route basis?

```javascript
Router.plugin('ensureSignedIn', {
    errorText: 'This is private stuff!',
    only: ['privateRoute']
});

Router.plugin('ensureSignedIn', {
    errorText: 'Login first!',
    only: ['anotherPrivateRoute']
});
```

This should be easy to achieve...

**Comment by dalgard** [comment]
I'm looking into this a bit more. The real problem is in presenting an `error` message, when it would seem much more pleasant with a nudging explanation of why the user should sign up or log in.

I can quite conveniently change the message with `AccountsTemplates.state.form.set("error", [err])` – or set a success message with `"result"` – but really, I need a third option that is neutral.

Guess I'll go on and override the messages template within my UI of choice (Semantic UI) to include a neutral `"message"`.

Would be nice, if it was built in ;)

**Comment by splendido** [comment]
HA! I see, so the problem is the `error box` itself not the message contained therein...
Might make sense...

For now a great hack could be adding some special CSS rule to style the error box differently...
...perhaps with a custom layout to be used for pages to be protected which wraps everything within a `<div class="protected">...</div>` and with a rule like (not tested):

```css
.protected .at-error {
   // some tweak here...
}
```

**Comment by dalgard** [comment]
Your first suggestion with an `errorMessage` option was okay, although for my use case it would have to be a `message` option outputting a neutral message.

The CSS hack is not perfect, but I admit I didn't consider changing the appearance of the Semantic UI error message. I do very much prefer not to change anything in a rendered hook, though.

Still going to add a neutral message option, I think.
