### ISSUE TITLE
missing call to this.next on redirect after signIn

### ISSUE THREAD

**Issue by welelay** [meteor-useraccounts/core#315]
I see

    Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?

in the console after login.

My route is configured like this:

    AccountsTemplates.configureRoute("signIn", {
        name: "signIn",
        path: "/fo/user/sign-in",
        layoutTemplate: "foLayout",
        redirect: function() {
            some code...
            if(some condition){
                   Router.go("there");
            }else{
                   Router.go("elsewhere");
            }
        }
    });

After adding this.next() at [core.js:652](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L652) the message goes away.
I don't think I can call this.next() in the redirect function so it has to be added there.

What do you think?

**Comment by splendido** [comment]
`this.stop()` might be more appropriate...

**Comment by splendido** [comment]
Tnx!

**Comment by welelay** [comment]
It works!
Many thanks,
