### ISSUE TITLE
How can I validate whether or not a 3rd party permission was granted?

### ISSUE THREAD

**Issue by adrianmc** [meteor-useraccounts/core#318]
For example, I want to provide the user with the ability to register via Facebook. But I *need* to make sure that I get their e-mail from Facebook. 

However, when a user registers via Facebook, they have the option to deny giving away their e-mail. Is there a way for us to handle that in this package?

**Comment by splendido** [comment]
Hi @adrianmc,
although you can get Facebook login integrated with useraccounts, all the permissions management and dataflows are to be dealt with separately (for example using some package like [biasport:facebook-sdk](https://atmospherejs.com/biasport/facebook-sdk), which I never used though...)

What you could do is leveraging the [Accounts.validateLoginAttempt](https://docs.meteor.com/#/full/accounts_validateloginattempt) hook to check whether needed permissions where granted or not. But still you'll have to use your own code to *ask* Facebook which permission were granted and which not...

**Comment by adrianmc** [comment]
Thanks for the informative reply!
