### ISSUE TITLE
Infinite invalidation with release 1.8.1

### ISSUE THREAD

**Issue by richsilv** [meteor-useraccounts/core#322]
Not sure why, but I'm getting what appears to be an infinite invalidation loop with the 1.8.1 release, on both Meteor 1.3.2 and 1.4.1.  The first login on a given browser goes fine, but subsequent visits to the page result in 100% CPU usage and nothing constructive.

Rolling back to useraccounts:core@1.6.1 and useraccounts:bootstrap:1.3.2 resolves this.

It's probably relevant that I've got this in my router:

```
AccountsTemplates.configureRoute('signIn', {
   template: 'signInPage'
});

Router.onBeforeAction(function() {
  if (!Meteor.user()) this.redirect('atSignIn');
  this.next();
}, {
  except: ['stream', 'atSignIn']
});
```

**Comment by splendido** [comment]
This does not answer to your problem, but have you tried the `ensureSignedIn` plugin?
Lets have a look at [Content Protection](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#content-protection)
