### ISSUE TITLE
customization limited?

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/core#325]
If I have  my own design for signin form, can useraccounts be customized this much? 
target design
http://screencast.com/t/BHqBHpZZDxI

**Comment by splendido** [comment]
I'd say yes!

...in case you could accept a link in place of the *Register* button you could get very close using `useraccounts:unstyled` together with your own CSS styles.

The other possibility would be to create your own templates cloning useraccounts:unstyled

**Comment by Maxhodges** [comment]
ah OK so I'm using the wrong package? we are using bootstrap, but I can't find a way to simply change at-signin to use btn-success instead of btn-default class. So I should add the unstyle package instead?

Cheers!

**Comment by splendido** [comment]
...you didn't mention you're using bootstrap ;-)

If you need to change elements' classes you have to clone `useraccounts:bootstrap` and start off it

**Comment by Maxhodges** [comment]
OK i forked it, but when I search for "btn-default" I don't get any results. Strange. Is the github search broken?

**Comment by Maxhodges** [comment]
OK I found this

`<template name="atPwdFormBtn">
  <button type="submit" class="at-btn submit btn btn-lg btn-block btn-success {{submitDisabled}}" id="at-btn">
    {{buttonText}}
  </button>
</template>

but after changing btn-default to btn-primary it's still btn-default in my browser. 

Do I need to also fork these projects too?
        "useraccounts:bootstrap",
        "useraccounts:core@1.8.1",

**Comment by Maxhodges** [comment]
you know any good articles on how to fork a meteor package? I forked it, added the files to my packages folder and changed the name and git values
    name: "whiterabbit:meteor-useraccounts-bootstrap",
    git: "https://github.com/white-rabbit-japan/meteor-useraccounts-bootstrap",

but I get no such template: atForm

**Comment by Maxhodges** [comment]
damn forking a package looks a bit too complicated for me:
http://stackoverflow.com/a/26568387/861010

No plans to create a json file or options extension where button classes could be configured?

**Comment by splendido** [comment]
See [Contributing](https://github.com/meteor-useraccounts/core/blob/master/README.md#contributing) for some details about how to work with lical packages.

You might also be intetested to read #212 about how to replace a template.

Also, please don't publish forked packages unless they provide sensible improvements we cannot include in the official ones.

**Comment by splendido** [comment]
Leaving the possibility to configure elements' classes is somethong we might think to introduce in some future release!

But perhaps giving a simpler way to specify custom templates would be enough?

**Comment by Maxhodges** [comment]
OK yes, thanks. I was able to override the template to change the class.

One more question: so this package doesn't actually register and login users right? I tried to sign up but it didn't create a new account. That is something we need to do manually? Do I need to override the  some template in order to setup a signin button handler?

CHeers!

**Comment by splendido** [comment]
Well, with useraccounts you actually get all the meal already cooked!
it's wear you didn't manage to register a new user.

Lets try to get started with the [boilerplates](https://github.com/meteor-useraccounts/boilerplates)!

**Comment by splendido** [comment]
my last reply was for your original last comment...

I think there's no way to integrate `autoform` schrmas into `atForm`.
Honestly I never used it but I see it hard for the two packages to play nice together.

Let me know if you manage to use `autoform`, it would be something interesting to add to the guide!
