### ISSUE TITLE
[question] Attach service instead of login 

### ISSUE THREAD

**Issue by H1D** [meteor-useraccounts/core#326]
Hi! I have following use case:
0) App have `accounts-password` and `accounts-google`
1) User have account created via email+password
2) On a certain page I have `{{> atForm}}` which evaluates to "Add google" for him
3) When user clicks "Add google" App actually logs him as new user! With different userId =(

How to really attach new service instead of creating new login?
![](http://dl.dropboxusercontent.com/u/880075/gifs/30773.gif)

**Comment by athenawisdoms** [comment]
Off topic, how did u create the animated gif?

**Comment by H1D** [comment]
http://www.cockos.com/licecap/

**Comment by splendido** [comment]
Hello there!

You need [splendido:accounts-meld](https://atmospherejs.com/splendido/accounts-meld) to deal with this.
Please read carefully the [docs](https://github.com/splendido/meteor-accounts-meld/blob/master/README.md) and the description for the parameter `showAddRemoveServices` under [Configuration Options](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options)


There are plans to integrate `accounts-meld` directly into useraccounts@2.0.

Let me know about any feedback!
Luca

**Comment by splendido** [comment]
@athenawisdoms, I use [silentcast](https://github.com/colinkeenan/silentcast) on linux to grab the screen

**Comment by H1D** [comment]
@splendido cool! Thx. I'll try soon
