### ISSUE TITLE
Populating Select from Mongodb

### ISSUE THREAD

**Issue by meteorjs3000** [meteor-useraccounts/core#328]
While trying to create a `select` field with values from a Mongo collection `countries`, the following code causes the field to be missing in the sign up form.

What is the correct way to populate the select field?

	AccountsTemplates.addField({
		_id: 'country',
		type: 'select',
		displayName: 'Country',
		placeholder: {
			signUp: "Country"
		},
		select: {
			countries = _.map(Countries.find().fetch(), function(country) {
				return {label: country.name, value: country.name}
			})
		},
		required: true
	});

**Comment by splendido** [comment]
@meteorjs3000 lets have a look at the [select example](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#checkboxes-selects-radios-and-hidden): `select` takes a list of objects as value.

But my bet would be that at the time your code is executed on the client the `Countries` collection is still empty... If this is the case lets try to create a custom template for your select (see [this example](https://github.com/meteor-useraccounts/wiki/blob/master/customInputFields/select2/select2.md) on the wiki) and have a custom template helpers `items` used to populate the select with an `{{#each items}}`

**Comment by meteorjs3000** [comment]
Awesome!

**Comment by gVolop** [comment]
in your way - provide a custom template, you lose all atInput default behaviors
https://github.com/meteor-useraccounts/core/issues/613

**Comment by andrewmartz-af** [comment]
I just used the example in the wiki, and it populates the list fine, but it won't pass that select value on to the sign up process and thus gives a "required" error. Is there a way to make this work without Select2?

**Comment by bordalix** [comment]
This works with any select, not only Select2.

What you need to do:

    AccountsTemplates.addField({
      _id: 'country',
      type: 'text', // not a typo, is text, not select
      displayName: 'Country',
      template: 'countries',
      required: true
    });

First of all, you define the field as a text, not as a select. That means useraccounts will search for a input field with the id as 'at-field-country' and grab the respective value to insert in the user profile. So, in our template, we have to add a input type with that id, hidden, and then insert our select, as this (note the fourth line):

    <template name="countries">
      <div class="at-input">
        <label for="country">{{displayName}}</label>
        <input id="at-field-country" type="hidden">
        <select id="country" class="countries" style="width: 100%">
          <option selected disabled>Choose country</option>
        {{# each countriesAndIso }}
          <option value="{{ this.iso }}">{{ this.name }}</option>
        {{/ each }}
        </select>
        {{#if hasError}}
          <span class='red-text'>{{errorText}}</span>
        {{/if}}
      </div>
    </template>

Now, every time we change the select dropdown, we have to add the selected value to the input field 'at-field-country'. For that, we'll use a Meteor event, like so:

    Template.countries.events({
      'change select': (event) => {
        $('#at-field-country').val(event.currentTarget.value);
      }
    })

So, every time the user selects something in the select dropdown, we put that value on the input field (which is hidden), and when submit, useraccounts will fetch the value from that input field and insert it on the user profile, as intended.
