### ISSUE TITLE
on logout redirect to sign in page

### ISSUE THREAD

**Issue by Kestanous** [meteor-useraccounts/core#329]
Maybe I am doing this wrong but I have an issue where I can not redirect to my sign in page when a user logs out. 

I have:
```js
AccountsTemplates.configure({
  ...
  homeRoutePath: '/example',
  onLogoutHook: function () {
   Router.go('atSignIn')
 },
});
AccountsTemplates.configureRoute('signIn', {
  path: '/'
});
```

When ever I call `Meteor.logout()` the user ends up on `/example` not `/` and they get the forbidden route error.

**Comment by splendido** [comment]
@Kestanous, `onLogoutHook` is called in case you use `AccountsTemplates.logout()` ;-)

**Comment by Kestanous** [comment]
Hmm still no good. I did not know about `AccountsTemplates.logout()`, is that new? Regardless I am using that now. The redirect works when I am on `/example` but now when I am on any other route. It is possible this a bug with my code though. I am refactoring my app so if its on my end I should find it if that is the case. 

Thanks!

**Comment by Kestanous** [comment]
@splendido it was a mix of things. I was on my end with a crazy redirect that was assuming the user was logged in. Additionally using `AccountsTemplates.logout()` redirects to root properly. Thanks!

**Comment by splendido** [comment]
:+1:
