### ISSUE TITLE
Unable to hide Social buttons

### ISSUE THREAD

**Issue by vertangelx** [meteor-useraccounts/core#332]
I tried to hide social buttons using the following, but why does it still show up?

	AccountsTemplates.configure({
		allowSocialRegistration: false,
		showServicesSignIn: false,
		showServicesSignUp: false
	})

**Comment by splendido** [comment]
Hey @vertangelx, non of those options exists!

I had some proposals/ideas within [this post](https://github.com/meteor-useraccounts/core/issues/111#issuecomment-61325747) as something to be possibly added to v2.0, but that's it!

**Comment by meteorjs3000** [comment]
Looking forward for this feature!
