### ISSUE TITLE
changePwd route logs out user without loading the Change Password Template

### ISSUE THREAD

**Issue by KyleKing** [meteor-useraccounts/core#333]
I have:
```js
// in both/accounts/config.js:
AccountsTemplates.configureRoute('changePwd');
...
enablePasswordChange: true,
```
```html
<!-- in client/templates/home/home.html  and client/templates/dashboard/dashboard.html -->
<a href="{{ pathFor 'atChangePwd' }}" data-action="logout">Change Password</a>
```

Yet when the link element is clicked, the user is logged out. The nav bar quickly goes to http://localhost:3000/change-password, but immediately flips back to http://localhost:3000/. I've configured the login, register, and forgot password pages, but this one escapes me. What am I missing?

For reference, the rest of my codebase is essentially the [Differential/meteor-boilerplate](https://github.com/Differential/meteor-boilerplate)
If you want to run my meteor app, I have it [here](https://github.com/KyleKing/TeamBIKES/tree/develop/TeamBIKES)

**Comment by KyleKing** [comment]
Update: adding a jade template causes a password form to appear momentarily then quickly dissapear again. Anyone have any ideas why this isn't working with the above code?
```jade
template(name="change-password")
  +fullPageAtForm
```

**Comment by KyleKing** [comment]
Woops, did not see the most obvious error: 
```html
<!-- in client/templates/home/home.html  and client/templates/dashboard/dashboard.html -->
<a href="{{ pathFor 'atChangePwd' }}" data-action="logout">Change Password</a>

<!-- becomes.... -->
<a href="{{ pathFor 'atChangePwd' }}">Change Password</a>
```
And it magically stops logging me out!

Hope this helps someone else

**Comment by splendido** [comment]
:+1:
