### ISSUE TITLE
[question] Where to find users in mongo?

### ISSUE THREAD

**Issue by SturmDrangAltaar** [meteor-useraccounts/core#336]
Hi there, 

Brand new to meteor, so I apologize if this is an extremely noob question.
Basically, I've set up my site to use the semantic-ui userAccounts module and it's working fine, can register and login. However, when I list collections in mongo I don't see a users collection, what am I missing here?

Thanks in advance.

Edit: The deployed version on a separate server seems to be correct, was deployed with mup. So I guess my issue must be a local config issue. Any environment vars that I possibly forgot to set up?

Edit nr2: Figured it out. Seems meteor on local was running a mongo instance on a different port (3001) than my default one (27017). All sorted now.

**Comment by splendido** [comment]
Hi there!
you can access the mongo db used by your app running `meteor mongo` from your app's folder (while your app is running...)

you can also use `meteor mongo url` to access a deployed app's db.
See [meteor mongo](http://docs.meteor.com/#/full/meteormongo)

And the way to access users' collection from code is `Meteor.users`.


Sorry for the late reply!
