### ISSUE TITLE
Materialize (additional fields) radio buttons are broken

### ISSUE THREAD

**Issue by itsdeluxe** [meteor-useraccounts/core#337]
Looks like adding radio fields in the Materialize theme is broken due to a missing 'for' attribute on the label tag.  In other words, you can't select the radio buttons.  Here is an example:  

AccountsTemplates.addField({
  _id: "account",
  type: "radio",
  displayName: "Choose account type",
  select: [
    {
      text: "Type 1",
      value: "t1",
    },
    {
      text: "Type 2",
      value: "t2",
    },
  ],
});

This is the html generated:

<div class="at-input">
    <input id="at-field-account-choice-t1" type="radio" name="at-field-account" value="t1">
    <label>Type 1</label>
</div>
<div class="at-input">
    <input id="at-field-account-choice-t2" type="radio" name="at-field-account" value="t2">
    <label>Type 2</label>
</div>

Notice there is no 'for' attribute on the label tag.  I believe it should look like this:
<div class="at-input">
    <input id="at-field-account-choice-t1" type="radio" name="at-field-account" value="t1">
    <label for="at-field-account-choice-t1">Type 1</label>
</div>
<div class="at-input">
    <input id="at-field-account-choice-t2" type="radio" name="at-field-account" value="t2">
    <label for="at-field-account-choice-t2">Type 2</label>
</div>

Please let me know if I am missing something and thank you for this awesome package!

**Comment by splendido** [comment]
Hi @itsdeluxe,
did you solve this?

**Comment by garysxn** [comment]
Hi @itsdeluxe 
I have same problem, unable to select radio buttons because 'for' attribute on label tag is missing.
are you resolve this problem?

my code:
{
        _id: 'gender',
        type: 'radio',
        placeholder:'Gender',
        displayName: 'Gender',
        select:[{
                    text: "Male",
                    value: "male"                   
                },
                {
                    text: "Female",
                    value: "female"
                }]
    }

**Comment by splendido** [comment]
@garysxn this should be solved right now...
See [this line](https://github.com/meteor-useraccounts/materialize/blob/master/lib/at_input.html#L47) which was fixed by https://github.com/meteor-useraccounts/materialize/commit/bfc239e30da34266ffa0887d1b7c27924c182db6
The same issue was reported also on the core repo: https://github.com/meteor-useraccounts/core/issues/421

Are you sure you're running on the latest version?
