### ISSUE TITLE
enroll route not working

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/core#339]
I got signIn and changePwd working but for the life of me I cannot get enrollAccount working. Is there some trick to it?

    Oops, looks like there's no route on the client or the server for url:     "http://localhost:3000/enroll-account."

//code

    AccountsTemplates.configureRoute('signIn', {
    name: 'Login',
    path: '/signin',
    template: 'login',
     layoutTemplate: 'masterLayout',
    });

    AccountsTemplates.configureRoute('enrollAccount');

    AccountsTemplates.configureRoute('changePwd');

**Comment by splendido** [comment]
Try out something like `http://localhost:3000/enroll-account/akjhfcsalkdfhlae827ljasgdku`! ;-)

...this is the kind of link you get with an enroll email.
