### ISSUE TITLE
Support for guest accounts

### ISSUE THREAD

**Issue by rdrey** [meteor-useraccounts/core#340]
I'd love it if these packages supported https://github.com/artwells/meteor-accounts-guest/ 

I will probably roll my own "upgrade from guest account" form so long.

**Comment by rdrey** [comment]
Ah, I've found references to your own guest plugin in #223 

How is that getting along? Are you working on a branch on which I can help out?

**Comment by splendido** [comment]
Yeah, it's on the *roadmap*...

I've started working on v2.0 but still haven't pushed anything to github.

Thanks for the offer! I'I'll get back to you when there's something to work on ;-)
