### ISSUE TITLE
Suggest adding index for field order

### ISSUE THREAD

**Issue by chazsolo** [meteor-useraccounts/core#341]
When removing the `email` field and adding in `username`

    AccountsTemplates.removeField('email');
    AccountsTemplates.addField({
        _id: 'username',
        type: 'text',
        required: true,
        minLength: 3,
        func: function( value ) {
        if ( Meteor.isClient ) {
            //...
        }
    });

The `password` field is rendered first, followed by the `username`, which is backwards and not good for user experience.  It would be nice to see an optional `index` when adding fields.  For example:

    AccountsTemplates.addField({
        _id: 'username',
        type: 'text',
        required: true,
        index: 'first' // or 1...
    });

**Comment by splendido** [comment]
See #141.
