### ISSUE TITLE
replacing hardcoded messages from server.js methods

### ISSUE THREAD

**Issue by TheRedDevil** [meteor-useraccounts/core#342]
Some error messages in server.js are hardcoded, like for example: "Please verify your email first. Check the email and follow the link!" - line 112, but they could be parametrized through  AccountsTemplates.texts like many other messages.

**Comment by splendido** [comment]
I'll try to give them a corresponding configuration parameter for the next release...

Tnx

**Comment by TheRedDevil** [comment]
Thank you very much :)
