### ISSUE TITLE
Ability to show/hide items when including the template, not just globally [Feature Request]

### ISSUE THREAD

**Issue by todda00** [meteor-useraccounts/core#344]
I am showing both the register and login form on the same page when a user reaches a page and needs to be registered to access. This is working, but there are a few things appearing which are less than ideal. 

I would like to hide the "Must be logged in" message (appearing on both forms). Also remove the link to login and like to register. 
I realize I can hide the links globally, but would like to keep them available for the main login and register forms when showed on a page by themselves.
 
This is what it looks like currently:
![login_or_register](https://cloud.githubusercontent.com/assets/8363924/7071271/56f9f268-deb2-11e4-8854-35348b28a571.png)

I can hide the register and login links via CSS, but hiding the Must be logged in would then hide other errors if they happen. I did figure out a different way to hide the initial error though, see code at the end of this post.

I think it would be helpful to be able to do something like this:

```
<template name='loginOrRegister'>
<div class="loginOrRegister">
  <div class='col-xs-12 col-sm-6'>
    {{> atForm state='signUp' showSignInLink=false}}
  </div>
  <div class='col-xs-12 col-sm-6'>
    {{> atForm state='signIn' showSignUpLink=false}}
  </div>
</div>
</template>
```

I can hide the initial error by doing this: 
```
Template.loginOrRegister.rendered = ->
  AccountsTemplates.state.form.set('error',false)
```
Perhaps an option when defining the 'ensureSignedIn' plugin to not show this initial error would be good.

**Comment by splendido** [comment]
Hello @todda00,
lets continue this discussion on #345!

Tnx
