### ISSUE TITLE
How could I support zh_cn language?

### ISSUE THREAD

**Issue by FrankyYang** [meteor-useraccounts/core#346]
zh_cn already in t9n, but seems that not supported in meteor-useraccounts now, how could I update that?

**Comment by splendido** [comment]
could you please check which version of accounts-t9n you get installed?
if I run `meteor update` I get the latest softwarerero:accounts-t9n@1.1.0...

**Comment by FrankyYang** [comment]
I've updated that package to the latest version, but the code like T9n.setLanguage('zh_cn') still doesn't work, meanwhile T9n.setLanguage('zh_tw') works fine.

**Comment by FrankyYang** [comment]
I fix that with code like this:  T9n.map('zh_cn', { add: "添加"} ... ) before I set the language to zh_cn. When I use grep to scan my meteor directory, no map files that contains zh_cn characters found.

**Comment by splendido** [comment]
Ok, I've found the problem.

The reason is the language cose is now `zn-ch` and not `zn_ch`.

I've already proposed a fix: see [this PR](https://github.com/softwarerero/meteor-accounts-t9n/pull/100)

**Comment by splendido** [comment]
For now you can use `zn-ch`, but keep an eye on the next release of `accounts-t9n`: at that time you'll have to switch to `zn_ch`.

Thanks!

**Comment by FrankyYang** [comment]
Many thx! zh-cn works. But some words like 'Email' missed, how could I add more properties of translation into zn-ch?

**Comment by splendido** [comment]
*email* seems to be present: see [this line](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/zh_cn.coffee#L16)

To add new kyes/translations see [this section](https://github.com/softwarerero/meteor-accounts-t9n#define-translations)
