### ISSUE TITLE
How to enable validation of input fields on signIn page?

### ISSUE THREAD

**Issue by iclear** [meteor-useraccounts/core#350]
i want to check the text password on the client side before i submit, is it possiable?

**Comment by iclear** [comment]
Q2: how to fetch the field value(e.g. username,password) inside onSubmitHook function?

**Comment by splendido** [comment]
@iclear if you're interested in validating fields' value lets have a look at [Form Fields Configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration) and the [Custom validation](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#custom-validation) subsection.

**Comment by iclear** [comment]
@splendido thanks for your reply.
But i find 'AccountsTemplates.addField' doesn't work in the login page where i want to validate the password.  is there a way to do this?

**Comment by splendido** [comment]
validations on login were removed by purpose to prevent possible attackers to see the rules you're enforcing for passwords and usernames!

[This line](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_input.js#L75) and [this one](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_input.js#L96) are those preventing validation on login: if you really want to enable it, just overwrite the two corresponding event handlers:

```javascript
AccountsTemplates.atInputEvents["focusout input"] = function(event, t){
        var fieldId = this._id;
        var rawValue = this.getValue(t);
        var value = this.fixValue(rawValue);
        // Possibly updates the input value
        if (value !== rawValue) {
            this.setValue(t, value);
        }

        // Client-side only validation
        if (!this.validation)
            return;
        var parentData = Template.parentData();
        var state = (parentData && parentData.state) || AccountsTemplates.getState();
        // No validation during signIn
        // if (state === "signIn")
        //     return;
        // Special case for password confirmation
        if (value && fieldId === "password_again"){
            if (value !== $("#at-field-password").val())
                return this.setError(AccountsTemplates.texts.errors.pwdMismatch);
        }
        this.validate(value);
    };
AccountsTemplates.atInputEvents["keyup input"] = function(event, t){
        // Client-side only continuous validation
        if (!this.continuousValidation)
            return;
        var parentData = Template.parentData();
        var state = (parentData && parentData.state) || AccountsTemplates.getState();
        // No validation during signIn
        // if (state === "signIn")
        //     return;
        var fieldId = this._id;
        var rawValue = this.getValue(t);
        var value = this.fixValue(rawValue);
        // Possibly updates the input value
        if (value !== rawValue) {
            this.setValue(t, value);
        }
        // Special case for password confirmation
        if (value && fieldId === "password_again"){
            if (value !== $("#at-field-password").val())
                return this.setError(AccountsTemplates.texts.errors.pwdMismatch);
        }
        this.validate(value);
    };
```

**Comment by splendido** [comment]
...mmm, it might be that you have to do it directly on the templates, since at the time your code is loaded all templates' events handlers are already set up...

Lets try something like above but with:

```javascript
Template.atInput.events({
  "focusout input": function() {...},
  "keyup input": function() {...}
})

**Comment by iclear** [comment]
@splendido  ok...thx.... this works!
i have another little question. how to define the placeholder in input fields on login page?

**Comment by splendido** [comment]
See [this old[example](https://github.com/meteor-useraccounts/core/issues/109#issue-45311600)
