### ISSUE TITLE
Hide SignUp Link without completely disabling client side registration

### ISSUE THREAD

**Issue by chiester** [meteor-useraccounts/core#355]
Is it possible to only hide the "Register" link on the SignIn template with setting forbidClientAccountCreation: true ? 

I want a logged in admin to register accounts with SignUp, but I want them to be able to use the default SignUp form.

**Comment by splendido** [comment]
I see it difficult for a logged in admin to create new users with the singUp form: in case in worked the current user would switch to the newly registered one.

What about using a custom server-side method which checks the user *role* and permit admins to call `Accounts.createUser`?
...something on the lines of [ATCreateUserServer](https://github.com/meteor-useraccounts/core/blob/master/lib/methods.js#L20), but possibly a little leaner.

What do you think?

**Comment by chiester** [comment]
Thanks for your suggestion. I did end up creating a custom account creation service calling Accounts.createUser directly.

**Comment by splendido** [comment]
:+1:
