### ISSUE TITLE
How to populate a select in the registration screen with data from a collection?

### ISSUE THREAD

**Issue by hamoid** [meteor-useraccounts/core#356]
While registering, I need to let the user choose an option from a select. The select should be populated from a collection.
When I call AccountTemplates.addFields() to add the select, collections are not yet available, so I tried populating it afterwards, by doing this:

    if(Meteor.isClient) {
      Template.atForm.onRendered(function() {
        Coll.find().forEach(function(item) {
          $('#select').append('<option value="'+item._id+'">'+item.name+'</option>');
        })

That's as far as I got with my hack. The issue now is that atForm is only rendered once, and when it is first rendered it is showing the login screen, not the registration screen. So my append() calls get lost in ether (the select does not exist on the login screen, only in the registration screen).

Is there a less twisted way I could populate a select on the registration screen with data coming from a collection? Actually, I don't care how twisted. Is there a way to do it? :)

**Comment by hamoid** [comment]
For the Ugliest Hack Awards. Works perfectly.

```javascript
var waitForRegistrationScreen;
if(Meteor.isClient) {
  // When login template is rendered
  Template.atForm.onRendered(function() {
    // Start waiting for registration screen
    waitForRegistrationScreen = Meteor.setInterval(function() {
      // Keep checking if registration is shown
      if(AccountsTemplates.getState() == 'signUp') {
        // If it is shown, and select is empty, populate it
        if($('#at-field-group option').length == 0) {
          Groups.find().forEach(function(item) {
            $('#at-field-group').append('<option value="' + 
              item._id + '">' + item.group_name + '</option>'
            );
          });
        }
      }
    }, 500);

  });
  Template.atForm.onDestroyed(function() {
    Meteor.clearInterval(waitForRegistrationScreen);
  });
}
```

**Comment by splendido** [comment]
See #328

**Comment by hamoid** [comment]
Oops. Sorry for asking the same question again. I searched in the documentation and didn't find any mention of the word 'collection' or 'mongo', and there was no example of ```template```.

The good thing about doing an ugly hack is that when you replace it with the right thing it feels so good :) Thanks!

**Comment by splendido** [comment]
you're welcome, no worries!

...sooner or later we should organize all this examples in some consistent way.

If you'd like to add something to the [wiki](https://github.com/meteor-useraccounts/wiki/tree/master/customInputFields) feel free to open a PR.

**Comment by hamoid** [comment]
Maybe there could be a link from the guide to the wiki?

I didn't know there was a wiki.

**Comment by splendido** [comment]
me neider ;-)

**Comment by splendido** [comment]
kidding apart, I should add one, seriously :(
