### ISSUE TITLE
Return to previous url after login doesn't work?

### ISSUE THREAD

**Issue by obiwarn** [meteor-useraccounts/core#357]
Since the last update the router always returns to the root after login.

When I do:

   AccountsTemplates.setPrevPath(Router.current().url)

manually before I login, it works. 
However, in this case it always reloads the whole page (like if you press reload button in chrome).

**Comment by splendido** [comment]
I'll try to have a look at this...

tnx for reporting!

**Comment by splendido** [comment]
Just tested it by adding a `random` route to the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) this way:

```javascript
    this.route('random', {
        path: 'random',
        template: 'home'
    });
```

going to the `random` page and then clicking `Sign In` brought me back to the random page after successful login.

In case this is still an issue for you, please let me know how to reproduce the problem and I'll be happy to reopen this.
