### ISSUE TITLE
How to have two separate form with two different structures

### ISSUE THREAD

**Issue by ngducthanh** [meteor-useraccounts/core#358]
I have 2 different signup forms in my app. The structure of the forms are different from each other.I want to customize the fields on one form, but this change affect the other form. How to have two separate form with two separate fields structure?

**Comment by ngducthanh** [comment]
I have 2 different signup forms in my app. The structure of the forms are different from each other.I want to customize the fields on one form, but this change affect the other form. How to have two separate form with two separate fields structure?

**Comment by splendido** [comment]
> I want to customize the fields on one form
What do you mean wth this?

is the number/type of fields or simply stylings?

**Comment by ngducthanh** [comment]
I want to add one more field in this form but leave the other form intact.

**Comment by splendido** [comment]
The only tricky solution I'd think of would be palying with some `onRun` (or `onBeforeAction`) hook when the page is loaded to change the [AccountsTempltates._fields](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L392) array.

Something like saving the whole list at startup with

```javascript
AccountsTemplates.allFields = AccountsTemplates._fields
AccountsTemplates.someFields = _.filter(AccountsTemplates._fields, function(field){
  return field._id !== 'someFiledName';
})
```

and then 

```javascript
Router.route('someRoute', {
  onRun: function(){
    AccountsTemplates._fields = AccountsTemplates.allFields;
  }
});
Router.route('anotherRoute', {
  onRun: function(){
    AccountsTemplates._fields = AccountsTemplates.someFields;
  }
});
```

(*untested code*)

**Comment by ngducthanh** [comment]
Thanks a lot!

**Comment by splendido** [comment]
Let me know!

**Comment by ngducthanh** [comment]
I worked fine. Thanks!

**Comment by splendido** [comment]
:+1:

**Comment by ngducthanh** [comment]
@splendido 
The functionality of signUp form which contains all fields works very well. And the signUp form which contains less-than-full fields doesn't show the field I don't want to show. This is very good but when I try to sign up from this form, there is error:
```
 Exception in delivering result of invoking 'ATCreateUserServer': TypeError: Cannot read property 'setError' of undefined
    at http://localhost:3000/packages/useraccounts_core.js?04e5315e9523adb6a057f684c0d241993ae4dc50:1562:52
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:164:22)
    at AT.submitCallback (http://localhost:3000/packages/useraccounts_core.js?04e5315e9523adb6a057f684c0d241993ae4dc50:1561:15)
    at http://localhost:3000/packages/useraccounts_core.js?04e5315e9523adb6a057f684c0d241993ae4dc50:2131:35
    at null._callback (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:22)
    at _.extend._maybeInvokeCallback (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3860:12)
    at _.extend.receiveResult (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3880:10)
    at _.extend._livedata_result (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4964:9)
    at onMessage (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3725:12)
    at http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:2717:11 
```
And my two sign up forms look like this:
Form A: ['email', 'password']
Form B: ['organization', 'email', 'password']
Form A has error.

**Comment by splendido** [comment]
Is this error on the client or on the server?

...I'm realizing right now there might be some problems on the server side if you set the `organization` field required: the server still wants to get an `organization` field!

**Comment by ngducthanh** [comment]
The error is on client. When I set the `organization` field not required, I can sign up from form B. But `organization` field in form A is a required field. How can I fix this?

**Comment by splendido** [comment]
I'd say there's no easy solution for this at the moment :(

Could you better explain your use case so that we can judge whether this aspect should be considered while designing `useracccounts@2.0`?

**Comment by splendido** [comment]
The thing is that the server won't be satisfied unless it gets a value for the `organization` field (in case you set it as *required*): this is one of the selling points of `useraccounts] ;-)

**Comment by ngducthanh** [comment]
Thanks for helping me.

**Comment by AbdelBa** [comment]
@splendido please add this to the v2.0 milestone. I think this use case is worth it.
