### ISSUE TITLE
How to customize the login page size, background and social buttons?

### ISSUE THREAD

**Issue by mervynteo** [meteor-useraccounts/core#362]
2 main issues: 

1) I did not build the signin/signup page via boilerplate and installed via dependency and added in html as `{{> atForm}}`. Instead of a small box in the middle, the authentication page spans across the whole screen. I managed to change it by tweaking the html and css but is there an easier way?

2) For social button edits, I installed the `aldeed:template-extension`. In config.js, I added: `Template.customAtSocial.replaces("atSocial");`. Now error says "cannot call method of 'replaces' of 'undefined' which means 'atSocial' template is not recognised?

I suppose the line for the social buttons. 
https://github.com/meteor-useraccounts/semantic-ui/blob/master/lib/at_social.html
I hope to have the social icons as buttons, lined up in a row. Which parts should I edit?
 
![signin v2](https://cloud.githubusercontent.com/assets/5101947/7335916/e0269552-ec11-11e4-9d77-8640e50a1dd3.JPG)

**Comment by splendido** [comment]
hello there!

`atForm` template is designed to take up all the space you let to it ;-)
so simply wrap it inside some other html: perhaps some SUI grid or segment, message, etc.
That's really up to you, depending on how you'd like to design your page.
For example [fullPageAtForm](https://github.com/meteor-useraccounts/semantic-ui/blob/master/lib/full_page_at_form.html) is the default template used when you configure a route with `AccountsTemplates.configureRoute`.

**Comment by splendido** [comment]
for your second issue, I'd say it's a load order problem: it seems that `Template.customAtSocial` is not defined and so it results impossible to call `replaces` on it.
But this is better discussed in another issue...

**Comment by mervynteo** [comment]
@splendido  thanks for the reply. 

Will set up the 2nd query in a new issue.
