### ISSUE TITLE
Show redirect URL

### ISSUE THREAD

**Issue by c316** [meteor-useraccounts/core#363]
Is there a way to print to the console the URL that will be redirected after login? I'm using a redirect to the app running on a mobile for the verify-email url and I'm getting prompted to login. I'd like to see if this is an issue with my link not pointing to the correct route or an issue with the login prompting when it shouldn't.

**Comment by splendido** [comment]
I'd say that making a local clone of `useraccounts:core` could allow to add some `console.log` here and there to trace what's going on...

The first place where I'd look at is [here](https://github.com/meteor-useraccounts/core/blob/ae234f05999b2f3c3934c03a12dc2ba4aeddfecc/lib/client.js#L483-504)
