### ISSUE TITLE
How to make radio inline and hide the displayName?

### ISSUE THREAD

**Issue by ligacihoya** [meteor-useraccounts/core#364]
I use the code from Guide.

```Javascript
AccountsTemplates.addField({
    _id: "gender",
    type: "select",
    displayName: "Gender",
    select: [
        {
            text: "Male",
            value: "male",
        },
        {
            text: "Female",
            value: "female",
        },
    ],
});

AccountsTemplates.addField({
    _id: "fruit",
    type: "radio",
    displayName: "Preferred Fruit",
    select: [
        {
        text: "Apple",
        value: "aa",
      }, {
        text: "Banana",
        value: "bb",
      }, {
        text: "Carrot",
        value: "cc",
      },
    ],
});
```

And have set     showLabels: false,

But 
    displayName: "Gender",
    displayName: "Preferred Fruit",

are still displayed.

And second, How to made radio box inline?

**Comment by splendido** [comment]
[Here](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_input.html#L27-50) are the templates used to display selects and radios (for bootstrap though...).

As you've already discovered, the labels is always shown... perhaps there's little point in hiding it? Without the label you won't get the *subject* for the choice...

In any case, feel free to try overriding them following [this post](https://github.com/meteor-useraccounts/core/issues/212#issuecomment-67810815).
