### ISSUE TITLE
verifyEmail doesn't work with custom url if I have configured the route

### ISSUE THREAD

**Issue by c316** [meteor-useraccounts/core#373]
If I setup the configure route like this

```
AccountsTemplates.configureRoute('verifyEmail', {
    name: 'verifyEmail',
    path: '/verify-email',
    redirect: 'accounts'
});
```

Then setup my url like this

```
Accounts.urls.verifyEmail = function(token){
    return "http://mycustomdomain.com/" + token;
};
```

I get a localhost url instead

If I remove this part

```
AccountsTemplates.configureRoute('verifyEmail', {
    name: 'verifyEmail',
    path: '/verify-email',
    redirect: 'accounts'
});
```

Then my custom url comes through just fine. Of course I can't use the url unless I add the above code back in to define that route. 

Any idea what I might do to resolve this problem?

**Comment by c316** [comment]
I had to add this

```
Accounts.emailTemplates.verifyEmail.html = function (user, url) {
    url = url.replace("localhost:3000/verify-email", "mycustomdomain.com");
    then configure the html email here with that url variable as a button href
};
```

Even if I leave this

```
Accounts.urls.verifyEmail = function(token){
    return "http://mycustomdomain.com/" + token;
};
```

it doesn't seem to do anything. However, this work around is working for me.

**Comment by splendido** [comment]
Hello @c316,
I'm sorry I don't understand why you need to override the url for email verification.
Doesn't it work for your deployed app?

All this is based on `ROOT_URL` and [Meteor.absoluteUrl](https://docs.meteor.com/#/full/meteor_absoluteurl).
To see how the url is set up see [these lines](https://github.com/meteor-useraccounts/core/blob/3862dd2ffee16902c9c94cc015cc0bbea3546c34/lib/core.js#L649-651).

If you want to test the *final* result while still in local development, you could try to set the env variable `ROOT_URL` to `http://mycustomdomain.com/`

**Comment by c316** [comment]
The reason I want to override the default domain is to use deeplinking for my mobile app. I need to send the user to a url, which will redirect to a custom domain scheme, like "mygreatapp://verify-email". 

The mobile app will see this custom scheme and open the app automatically. I could use my app to do this redirection, but then the user has to wait for the whole Meteor app to load in the browser before being redirected...

I think the best solution might be to use the redirection after the email verification to try to open the mobile app. This way the email gets verified even if they open from a computer. I need to look at the docs and see how I can make this redirection work in this way. 

Thanks

**Comment by splendido** [comment]
Ok, I see.
So this is related to #240, as you already now ;-)

**Comment by c316** [comment]
Yes, that is correct. I suppose this issue could be closed.

On Mon, May 4, 2015 at 2:24 PM, Luca Mussi <notifications@github.com> wrote:

> Ok, I see.
> So this is related to #240
> <https://github.com/meteor-useraccounts/core/issues/240>, as you already
> now ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/core/issues/373#issuecomment-98824411>
> .
>



-- 
Joshua Bechard
--
Learn to do right! Seek justice, encourage the oppressed.
Defend the cause of the fatherless,
plead the case of the widow.
Isaiah 1:17
--
