### ISSUE TITLE
User not recognised by system after installing UserAccounts

### ISSUE THREAD

**Issue by mervynteo** [meteor-useraccounts/core#375]
Hi all, 

When I submit a post, the current user does not seem to be recognised and username appears as `blank` wherever I write a post, which has the `{{author}}` in html. 

Also when I type in the console this: `Meteor users findOne()`, the below error is produced.

![error3](https://cloud.githubusercontent.com/assets/5101947/7445680/c7a4a918-f1ef-11e4-882a-6491fa543c2d.JPG)

When I type {{author}] in the console, it returns 
`Uncaught, Reference Error: author is not defined`

This issue occurred after I set up the UserAccounts but not too sure.

**Comment by splendido** [comment]
I think you should provide a bit more context for your issue to be understood and reproduced.
Do you have a public repo for this?

In any case, useraccounts modifies user objects on the server side only, so I'd say it's not its falut ;-)
The only line where an user object is updates is [this one](https://github.com/meteor-useraccounts/core/blob/3862dd2ffee16902c9c94cc015cc0bbea3546c34/lib/methods.js#L12)

**Comment by splendido** [comment]
I cannot understand which is your problem, really.

From the screenshot above, you should type `Meteor.users.findOne()` with the two `.` dots to get one *random* object from the `users` collection.

Furthermore, the Spacebar's syntax `{{author}]` is not supported in the console...
