### ISSUE TITLE
Multiple configuration addField

### ISSUE THREAD

**Issue by QuentinEliga** [meteor-useraccounts/core#377]
Is it possible to configure the different fields for specific use ?

For instance, 

I want two different configuration in two different pages, one with the fields city, phone ect. and a another one without them.

Is it possible ?

**Comment by splendido** [comment]
No, that's not possible unless the fields are not required.
Once you set a required field, the server won't validate the data unsledd the field value is there...

See #358 for a more detailed discussion.
