### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by MrDunne** [meteor-useraccounts/core#381]
Just been having a dig about, how would I go about logging the user out if they are redirected to a page in iron-router?

**Comment by MrDunne** [comment]
Or a standardized logout button, either way

**Comment by splendido** [comment]
there's `AccountsTemplates.logout` you can use together with `onLogoutHook` configuration option to create custom redirects (see the *hooks* section within the [Configuration Options](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options)).
This if you wish to create a logout button...

Alternatively you can setup a logout page which is what Telescope is doing for example: lets have a look [here](https://github.com/TelescopeJS/Telescope/blob/bbf9fb9666cf07299c29e4e96d5fc37474bec1cc/lib/router/users.js#L62-70)

Let me know if you need further help.

**Comment by FranGM75** [comment]
I made a small application that uses:

meteor add accounts-base
meteor add accounts-password
i can register a new user with username, email and pass fields but when I logout, meteor delete the email field. why ? .


my code to register ....

  var user=template.find('#regnombre').value;
    var email=template.find('#regemail').value;
    var pass1=template.find('#regpass1').value;
    var pass2=template.find('#regpass2').value;

    var userObject = {
      username: user,
      email: email,
      password: pass1
    };

    Accounts.createUser(userObject, function (err) {


my code to logout ...

  "submit #logout-form":function(event,template){
      Meteor.logout(function(){
        event.preventDefault();
        Modal.hide(template);
      });
  }

**Comment by splendido** [comment]
@FranGM75 it seems your not using `useraccounts` packages in your example so maybe this is not the right place where to ask?
