### ISSUE TITLE
Meteor.loginWithFacebook() not working (nore button)

### ISSUE THREAD

**Issue by MrDunne** [meteor-useraccounts/core#382]
Attempting to get working with the facebook login, for some reason not working.

When I login, it returns internal server error, and when I do 
Meteor.loginWithFacebook()

The popup opens, and then the console says undefined.

**Comment by MrDunne** [comment]
Console says:

Exception while invoking method 'login' undefined

Which is odd, because the password login works

**Comment by splendido** [comment]
have you properly setup the facebook configuration?

to get social loging working you should at least do the following (for example):
1) create an app on [developers.facebook.com/apps](https://developers.facebook.com/apps)
1) `meteor add useraccounts:bootstrap accounts-facebook service-configuration`
2) create a configuration file under the `server` folder like [this one](https://github.com/meteor-useraccounts/boilerplates/blob/master/bootstrap/server/lib/config/accounts.js)

and you should get something like [this](http://useraccounts-bootstrap.meteor.com/sign-in)

**Comment by splendido** [comment]
any updates on this?

**Comment by f31n** [comment]
the same problem here
"Exception while invoking method 'login' undefined"
after i try to click on register with facebook

i'm working on windows with this installed packages:

accounts-facebook               1.0.4  Login service for Facebook accounts
accounts-oauth                  1.1.5  Common code for OAuth-based login services
accounts-password               1.1.1  Password support for accounts
alanning:roles                  1.2.13  Role-based authorization
aldeed:autoform                 4.2.2* Easily create forms with automatic insert and update, and automatic react...
aldeed:collection2              2.3.3  Automatic validation of insert and update operations on the client and se...
aldeed:tabular                  1.2.0  Datatables for large or small datasets in Meteor
aldeed:template-extension       3.4.3  Adds template features currently missing from the templating package
anti:fake                       0.4.1  Random text and data generator
appmill:animation-hooks         0.1.2  Helpers for animation hooks, including SVG
cmather:handlebars-server       2.0.0  Allows handlebars templates to be defined on the server in .handlebars files
cunneen:mailgun                 0.9.1  Easily send emails using Mailgun as your email provider.
dburles:collection-helpers      1.0.3  Transform your collections with helpers that you define
dburles:factory                 0.3.10  Factories for Meteor
iron:router                     1.0.9  Routing specifically designed for Meteor
less                            1.0.14  The dynamic stylesheet language
matb33:collection-hooks         0.7.13  Extends Mongo.Collection with before/after hooks for insert/update/remov...
meteor-platform                 1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:kadira              2.22.0  Performance Monitoring for Meteor
meteorhacks:kadira-binary-deps  1.4.0  Binary Dependencies for Kadira
meteorhacks:kadira-profiler     1.1.0  CPU Profiler for Kadira
meteorhacks:meteorx             1.3.1  Exposing Internal Meteor Apis to Hack Meteor Easily
meteorhacks:unblock             1.1.0  a way to use this.unblock inside publications
momentjs:moment                 2.10.3  Moment.js (official): parse, validate, manipulate, and display dates - o...
mongo-livedata                  1.0.8  Moved to the 'mongo' package
mrt:underscore-string-latest    2.3.3  underscore.string repackaged for Meteor
msavin:mongol                   1.0.97  The insanely handy development package for Meteor.
raix:handlebar-helpers          0.2.4  Handlebar helpers
reywood:publish-composite       1.3.6  Publish a set of related documents from multiple collections with a react...
service-configuration           1.0.4  Manage the configuration for third-party services
useraccounts:bootstrap          1.11.1  Accounts Templates styled for Twitter Bootstrap.
yasinuslu:blaze-meta            0.3.1  Blaze-meta makes it super simple to manage SEO data.
yogiben:admin                   1.1.2  A complete admin dashboard solution
yogiben:admin-settings          1.0.1  Key value store for yogiben:admin
zimme:iron-router-active        2.0.1  Deprecated! Use zimme:active-route


normal register / login is working
