### ISSUE TITLE
don't show "Must be logged in"

### ISSUE THREAD

**Issue by steveodom** [meteor-useraccounts/core#383]
When an unauthenticated user visits a ensureSignedIn page, and get's redirected to login, I'd like to not show "Must be logged in" error message. I know I can change the text to "" and have not text show up, but with padding of .at-error and a background-color, the user can still see the error message box. 

One option would be to hide the .at-error box and just use the text-field error messages. 

What's a good way to not show "Must be logged in" but show other .at-error messages?

**Comment by splendido** [comment]
We've been discussing about this with @dalgard in #314...
He eventually added the possibility to show a neutral message with #317.

Is this what you're looking for?
Or are you simply trying to remove the *error* for good?
...in this latter case you sould have a look at [these lines](https://github.com/meteor-useraccounts/core/blob/ae234f05999b2f3c3934c03a12dc2ba4aeddfecc/lib/client.js#L121-122) and possibly run your own version of the `ensureSignedIn` message.

**Comment by steveodom** [comment]
Thanks. I ended up specifying a custom layoutTemplate for the ensureSignedIn route.  This layout simply wraps the .at-form layout with a .no-error div. I then used css to display: none the .no-error .at-error element.

AccountsTemplates.configureRoute('ensureSignedIn', {
    layoutTemplate: 'noErrorWrapper',
});

**Comment by JohnSmith0602** [comment]
Hi @steveodom , I wanna try your solution. Here is my code:

``` javascript
AccountsTemplates.configureRoute('ensureSignedIn', {
  layoutTemplate: 'noErrorAtForm'
});

AccountsTemplates.configureRoute('signIn', {
  name: 'signIn',
  path: '/sign-in'
});

FlowRouter.route('/create', {
  name: 'create',
  triggersEnter: [AccountsTemplates.ensureSignedIn],
  action: function() {}
});
```

Yet the route always directs to 'signIn' page, do you know how to fix it? Thx!

**Comment by JohnSmith0602** [comment]
Besides, when in this no-error page, if the user submits wrong info, the error block won't be shown?

**Comment by JohnSmith0602** [comment]
It seems that in this [commit](https://github.com/meteor-useraccounts/core/commit/0ce0305d07614637181f24061f88a628b5f1f382#diff-50cfa59973c04321b5da0c6da0fdf4fe), relevant code has been removed...

so this hack is useless now?

**Comment by JohnSmith0602** [comment]
At last, I chose to fork the useraccounts:flow-routing project and remove this in AccountsTemplates.ensureSignedIn.

``` javascript
var err = AccountsTemplates.texts.errors.mustBeLoggedIn;
AccountsTemplates.state.form.set("error", [err]);
```

Hope whether showing the error can be an option later in the configurations. @splendido
