### ISSUE TITLE
Prevent redirect to previous page - Modal signup / Signin

### ISSUE THREAD

**Issue by niranjans** [meteor-useraccounts/core#386]
Hi, 

I am using a modal signUp / signIn workflow and so when a user signs up, all that needs to happen is close the signUp modal on that page and not redirect. Currently, after the signup, the user is redirected to one page back. 
This is my `onSubmitHook`:
```
var submitFunc = function(error, state){
  if (!error) {
    if (state === "signIn") {
      $('#modalSignIn').modal('hide');
    }
    if (state === "signUp") {
      $('#modalSignUp').modal('hide');
    }
    // Router.go(Router.current().url); -- This does not work either
  }
};
```

**Comment by splendido** [comment]
Hello @niranjans!
Lets have a look at [this thread](https://github.com/meteor-useraccounts/bootstrap/issues/25) by @Maxhodges. He also provided a condensed example [here](https://github.com/meteor-useraccounts/wiki/blob/master/modal-form-bootstrap-3) in the wiki.

See also [this other solution](https://github.com/meteor-useraccounts/core/issues/180#issuecomment-82487432) proposed by @BradRyan

We'll than have to converge to a common solution so tu put it inside v2.0 which is under development...

Let me know!

**Comment by niranjans** [comment]
Hi @splendido , Thanks for your reply and for the resources. It really helped. I also found out about `AccountsTemplates.avoidRedirect = true;`  which stopped the redirection.

**Comment by splendido** [comment]
:+1:
