### ISSUE TITLE
How to add some custom data to user when sign up?

### ISSUE THREAD

**Issue by xois** [meteor-useraccounts/core#387]
I need user has a `{profile: {expect: false}}` field after sign up, and I cannot do it by using a `<input type=hidden>`,  How can I do that?

maybe something like onAfterSignUp hooks?

**Comment by splendido** [comment]
perhaps using the [Accounts.onCreateUser](https://docs.meteor.com/#/full/accounts_oncreateuser) callback?

**Comment by xois** [comment]
Thank you, I'll try.
