### ISSUE TITLE
profile.username vs profile.name

### ISSUE THREAD

**Issue by SachaG** [meteor-useraccounts/core#388]
If I'm not mistaken, it seems like if someone logs in with username/password their username gets copied to `profile.username`, while if they use Twitter it gets copied to `profile.name`. Maybe it'd be better to harmonize both?

**Comment by splendido** [comment]
Yeah, absolutely!
If this is actually what's happening, we need to fix it!
I'll have a look

**Comment by SachaG** [comment]
I can also confirm that logging in via Facebook creates a `profile.name` field.

**Comment by splendido** [comment]
I'd say [this line](https://github.com/meteor/meteor/blob/devel/packages/facebook/facebook_server.js#L27) is the one causing the `profile.name` to be set after facebook signup...

And [this](https://github.com/meteor/meteor/blob/devel/packages/google/google_server.js#L32) is the one for google, [twitter](https://github.com/meteor/meteor/blob/devel/packages/twitter/twitter_server.js#L32), etc.


So we'd need to change [this line](https://github.com/meteor-useraccounts/core/blob/3862dd2ffee16902c9c94cc015cc0bbea3546c34/lib/methods.js#L37) to be:

```javascript
options.profile.name = signupInfo.username;
```

but this would be somehow break retro compatibility?

**Comment by etmarch** [comment]
+1, as this makes integrating with a package like simple schema more of a hassle

**Comment by splendido** [comment]
This won't be a retro-compatible change...
But since I don't think many people is using this, lets close an eye ;-)
v2 will be for something else...
