### ISSUE TITLE
how to custom forgot password action?

### ISSUE THREAD

**Issue by iclear** [meteor-useraccounts/core#389]
i want to let the user retrieve their password through sms, is there a way to custom forgot password action?

**Comment by splendido** [comment]
at the moment useraccounts relies on the `Accounts` API: to send out the email to reset the password [Accounts.sendResetPasswordEmail](https://docs.meteor.com/#/full/accounts_sendresetpasswordemail) is called.

Though, there was some intention to hook into this process: see #240
But until https://github.com/meteor/meteor/issues/3538 will be solved there's little to do I guess...


FYI, [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L247-259) are the lines used at the moment to trigger the process.

Then I'd guess to have something usable from sms, the current token should be shortened ;-)

Another possibility is to by-pass `Accounts` API and roll your own mechanism providing some server side method to deal with this.

**Comment by iclear** [comment]
AccountsTemplates.configureRoute('forgotPwd', {
    layoutTemplate: 'appLayout',
    template: 'userCustomTemp'
});

**Comment by splendido** [comment]
I'd be happy to get more details about your implementation!
...it might be something to conside to have for `useraccounts@2.0` :-)

**Comment by sasikanth513** [comment]
Is there any way to this?

**Comment by sasikanth513** [comment]
@iclear Can you please tell how did you added custom action for `forgot password` action?
