### ISSUE TITLE
How to better validate the email address?

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/core#390]
the form allows a user to register with an email address which lacks a domain i.e. `cobbledick@mailinator` is permitted by the validation rule, but surely that email address is invalid right?

**Comment by splendido** [comment]
yeah!
the reason is there's a default check which is very basic: see [here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L408-410)
This is exactly what the `Accounts` package does though...

you can ask to use a stronger regexp this way:

```javascript
AccountsTemplates.removeField('email');
AccountsTemplates.addField({
    _id: 'email',
    type: 'email',
    required: true,
    displayName: "email",
    re: /.+@(.+){2,}\.(.+){2,}/,
    errStr: 'Invalid email',
});
```
