### ISSUE TITLE
How to require a strong password?

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/core#391]
are there provisions in this package to require a strong password? i.e. mix of upperCase, lowerCase, numbers and symbol? I found that I can require a minLength, but we are handling money so would prefer to raise the bar on customer passwords.

**Comment by splendido** [comment]
you can put whatever rexexp you wish! :-)

this is an example:

```
AccountsTemplates.removeField('password');
AccountsTemplates.addField({
    _id: 'password',
    type: 'password',
    required: true,
    re: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/,
    errStr: 'your custom description for your regexp',
});
```

Lets have a look [here](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration)
