### ISSUE TITLE
Custom / Change HTML -elements

### ISSUE THREAD

**Issue by majka-meteor** [meteor-useraccounts/core#394]
Hi, I wanna remove for example this string from the button "sign in with facebook", I wanna keep just an icon! I would like to do a lot of small changes like that, so I would like to be able to access whole html code, is it possible or there is some other solution? I know I can remove or add fields but thats not what I need!
thank a lot for your help,
Majka

**Comment by splendido** [comment]
Hi there!
I'd say the best way is to write your own templates to be used in place of the current ones.
I's not difficult actually, the only thing you need is the [aldeed:template-extension](https://atmospherejs.com/aldeed/template-extension) package.

[This](https://github.com/meteor-useraccounts/core/issues/366#issuecomment-96380408) is the latest comment about this, but you can also have a look at #212.

I hope this can help!
Let me know if you need more pointers

**Comment by splendido** [comment]
I guess you have enough information now.
Let me know!

**Comment by majka-meteor** [comment]
Hi Splendido, thanks a lot for your help! :) 
I am gonna try it soon. I'll let u know how it's going. 
Have a nice day!
