### ISSUE TITLE
Best place for password requirements text

### ISSUE THREAD

**Issue by c316** [meteor-useraccounts/core#396]
How can I display the password requirements to my user before the first password failure? I want to show both the length requirement and the least strong password requirements (1 digit, 1 uppercase and 1 lowercase). I see these error message dialogs when I don't meet the requirements, but I'd prefer that the users know what is expected of them before they try to come up with a password (that doesn't work). 

Thanks

**Comment by splendido** [comment]
what about using the placeholder?

alternatively you could wrap your custom template for the password field and a paragraph with your description: lets have a look at [this](https://github.com/meteor-useraccounts/core/issues/273#issuecomment-73137378)

**Comment by splendido** [comment]
I guess you have enough information now...
Let me know!
