### ISSUE TITLE
showResendVerificationEmailLink does not exist

### ISSUE THREAD

**Issue by rclai** [meteor-useraccounts/core#397]
Is this something that doesn't exist in the flow-router-integration branch?

**Comment by splendido** [comment]
...it's something recent. I have to check but it might be latest additions to master are still to be merged into `flow-router-integration`

**Comment by splendido** [comment]
There were no updates from `master` to `flow-router-integration` since the last stable commit 90b947d1d605085d7bafb6eb2c0d6a2fa9a9e4e0.

I've now merged all newer modifications into `flow-router-integration`.
Let me know if all works fine!

**Comment by rclai** [comment]
Okay thanks will let you know.
