### ISSUE TITLE
New in 1.10.0: annoying server-side error message

### ISSUE THREAD

**Issue by steph643** [meteor-useraccounts/core#398]
I don't define routes because I use `{{> atForm}}` in a modal. Since v1.10.0, I get the following server-side error:
```
WARNING: showForgotPasswordLink set to true, but forgotPwd route is not configured!
```

**Comment by steph643** [comment]
I don't know if there is a relationship, but I also get this new Iron Router client-side warning:
```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?
```

**Comment by jaskinn** [comment]
I am also receiving that Iron Router client-side warning.

**Comment by jaskinn** [comment]
For me, the issue was meteorhacks:fast-render. Removed that and all working as expected.

**Comment by splendido** [comment]
...the best solution would probably be removing all warnings ;-)
I'm trying to add a serious logger to v2.0 so that people can turn it on during development in case it need be.
