### ISSUE TITLE
signIn/signUp callbacks that include the password

### ISSUE THREAD

**Issue by PhilippSpo** [meteor-useraccounts/core#400]
As I am working on a encryption package that encrypts/decrypts everything on the client side (like mylar) I need to have the users password (not the hash) in order to encrypt/decrypt his private key.  
I'd need this once the user signs up (in order to encrypt the private key) and once the user signs in (in order to decrypt the private key).  
I looked around a bit in the code and tried some Meteor Accounts stuff aswell, but there currently seems to be no callback that gives me the users password.  
The only place in the package where the password is available is in `at_pwd_form.js` in the submit event.  
I propose a option `extendProfile` that gets called before the `ATCreateUserServer` server method and lets you extend the users profile and gives you the users password (This would also allow for easily appending the private key or any addition/manipulation to the users profile).  
What are your thoughts on this?

**Comment by barboni** [comment]
:+1:

**Comment by splendido** [comment]
See `preSignUpHook` within the *Hooks* section within the [configuration options table](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options) in the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)
