### ISSUE TITLE
onLogoutHook doesn't seem to work

### ISSUE THREAD

**Issue by steph643** [meteor-useraccounts/core#402]
I don't need this hook, but while testing I had the feeling it is never called (and I cannot find it in the code).

**Comment by splendido** [comment]
it's actually called [here](https://github.com/meteor-useraccounts/core/blob/db20c0170aa776eb058ab6cac062356f40ebacbd/lib/client.js#L480) after succesfull logout.
Obviously you should have logged the user out calling `AccountsTemplates.logout()` and not `Meteor.logout()`.

Please see the *Hooks* section within the [configuration options table](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options) in the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)

**Comment by steph643** [comment]
Thanks. I was using `Meteor.logout()`...

**Comment by splendido** [comment]
you're welcome!
