### ISSUE TITLE
Router plugin ensureSignedIn not working 

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#406]
The router plugin ensureSignedIn is not working for me, all my routes still render 

This is what I have in router.js file 

Router.plugin('ensureSignedIn', {
    except: ['home', 'atSignIn', 'atSignUp', 'atForgotPassword']
});

**Comment by splendido** [comment]
A bit more of context?
...it's working great for me!

In any case this would be more general:

```javascript
Router.plugin('ensureSignedIn', {
  except: _.pluck(AccountsTemplates.routes, 'name').concat(['home'])
});
```

...I sould add it to the guide ;-)

**Comment by almogdesign** [comment]
If have to router notification or dashboard it renders the template I was expecting it not to as the user is not logged in. I redirect back to the set home route.

**Comment by splendido** [comment]
I'm not following, sorry.
Could you explain better?

**Comment by almogdesign** [comment]
If I understand it correctly the "ensureSignedIn" plugin stops users that are not signed in from accessing certain parts of the app IE routes. Basically if I have except on 'home" then all other routes should not allow a user access unless their signed in. This is not working

**Comment by splendido** [comment]
Lets try to land [here](http://useraccounts-semantic-ui.meteor.com/private)
[Here](https://github.com/meteor-useraccounts/boilerplates/blob/master/semantic-ui/lib/router.js#L19-21) is where I set up the `ensureSignedIn` plugin.

I've also tried with the above example getting the same result.

**Comment by splendido** [comment]
Do you have some public repo reproducing the problem?

**Comment by almogdesign** [comment]
I'm not using router map and don't have private setup, I have like so 
```javascript
Router.route('/dashboard', {
    name: 'dashboard',
    layoutTemplate: 'layoutApp',
    waitOn: function(){
        if(getConnectionStatus()) {
            return [Meteor.subscribe('organizations'), Meteor.subscribe('notifications'), Meteor.subscribe('producersList'), Meteor.subscribe('blocksList'), Meteor.subscribe('forms')];
        } else {
            this.render();
        }
    },

    //TODO: add some kind of limits
    data: function() {
        return {
            organization: Organizations.findOne(),
            user: Meteor.users.findOne(),
            producers: Producers.find(),
            blocks: Blocks.find(),
            forms: Forms.find()
        };
    }
});

Router.plugin('ensureSignedIn', {
    only: ['dashboard']
});
```

**Comment by almogdesign** [comment]
This does not work as you can see 
![screen shot 2015-05-31 at 9 55 53 am](https://cloud.githubusercontent.com/assets/169507/7900965/f16eb666-077b-11e5-9081-62fd901c3643.png)

**Comment by almogdesign** [comment]
Got it working seems to be an issue with iron-router and waitOn firing before the onBeforeAction when accessing route via address bar - https://github.com/iron-meteor/iron-router/issues/1353

**Comment by splendido** [comment]
in any case, I won't put `this.render()` within a `waitOn` callback...

**Comment by almogdesign** [comment]
To fix it I added Meteor.user() to the if check. I need this render for offline mode

**Comment by splendido** [comment]
I'd say that without the else part you'll have your route `ready` in case no connection is available...
To my best knowledge, `this.render()` causes the rendering of the layout/template associated to the route and in case `waitOn` gets called before `onBeforeAction` (which should be true...) you're asking to render the route bypassing any check you might have in `onBeforeAction` callbacks...

Have you tried to use the following?

```javascript
Router.route('/dashboard', {
  name: 'dashboard',
  layoutTemplate: 'layoutApp',
  waitOn: function(){
    if(getConnectionStatus()) {
      return [Meteor.subscribe('organizations'), Meteor.subscribe('notifications'), Meteor.subscribe('producersList'), Meteor.subscribe('blocksList'), Meteor.subscribe('forms')];
    }
    return [];
  },
});
```

**Comment by almogdesign** [comment]
No that might be better, let me try that

**Comment by almogdesign** [comment]
No having the return []; does noting you still run into the same issue, but thanks for the suggestion
