### ISSUE TITLE
not found showing on useraccounts routes 

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#408]
I have the following code which was fine with accounts entry howevery I just switched to meteor-useraccounts (great package) but now I get the 404 page for all the useracconts routes 

```javascript
/* 404 page */
Router.route('/(.*)', function() {//regex for every route, must be last
  if (this.ready()) {
    document.title = "404";
    this.render('notFound');
  } else this.render('loading');
}); 
```

**Comment by splendido** [comment]
This is a problem connected with file load order.
...it's also written in your comment ;-)

I usually suggest to put an `at_config.js` file containing all AT configuration code under `/lib/config` so to have it loaded both on the client and on the server.
If you put your routes definition under `lib`, for example, I expect everything to work as expexted...

**Comment by almogdesign** [comment]
Yes that's what I have 
lib/config/ -  useraccounts_config.js
lib - router.js

**Comment by splendido** [comment]
Wooops, sorry.

This one works:

```javascript
Meteor.startup(function(){  
  /* 404 page */
  Router.route('/(.*)', function() {//regex for every route, must be last
    if (this.ready()) {
      document.title = "404";
      this.render('notFound');
    } else this.render('loading');
  });
});
```

...actually UA routes are set up at startup time, so you should run it later

**Comment by splendido** [comment]
What about the official way to do this woth IR?

```javascript
Router.configure({
    notFoundTemplate: 'pageNotFound',
});
```

**Comment by splendido** [comment]
See also the [waiton option](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#the-waiton-option)

**Comment by almogdesign** [comment]
Official way has a number of issues, there is already an open bug report / thread about this. WaitOn option will not work. 

If UA routes are setup to start on startup then I don't think it's possible unless US accounts also adds this as an option. Or have the option to run something before the UA routes

**Comment by splendido** [comment]
I'm not aware of the issues you're referring to.
But configuring global options before UA sets up his routes seems working for the boilerplates: see [here](https://github.com/meteor-useraccounts/boilerplates/blob/master/semantic-ui/lib/router.js#L1-9).

I've never dig into this, btw...

I hope the `Meteor.startup` trick works for you

**Comment by almogdesign** [comment]
Thanks putting it in a startup function works great, appreciate the help
