### ISSUE TITLE
Make compatible with monbro:iron-router-breadcrumb package

### ISSUE THREAD

**Issue by Asparagirl** [meteor-useraccounts/core#409]
This works...

```javascript
AccountsTemplates.configureRoute('signIn', {
    name: 'signin',
    path: '/login',
    template: 'useraccounts',
    redirect: function(){
        var user = Meteor.user();
        if (user)
          Router.go('/player/' + user._id);
    }
});
```

...but adding a 'parent' field like this doesn't...

```javascript
AccountsTemplates.configureRoute('signIn', {
    name: 'signin',
    path: '/login',
    template: 'useraccounts',
    parent: 'home',
    redirect: function(){
        var user = Meteor.user();
        if (user)
          Router.go('/player/' + user._id);
    }
});
```

Without the ability to list a parent, the various user accounts pages can't work with breadcrumbs.

I know this isn't a super-important feature, but it would be nice to have.  :smiley:

**Comment by splendido** [comment]
This is definitely something to consider for the upcoming package `useraccounts:iron-routing` which will be providing IR configuration support for `useraccounts@2.0`.

I've changed the code to let the developer pass in additional options!

**Comment by splendido** [comment]
Tnx!

**Comment by Asparagirl** [comment]
Thanks!
