### ISSUE TITLE
Verify  Email Link Not Working 

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#410]
Everything was fine when testing in local host however in production the verify link which is sent in the email does not noting, I'm not seeing the verified set to true in the database. 

Here is the link 
https://xstaging.goplatfarm.com/#!verify-email/UrDdu0RuG0eYAXnZrNtFw3AYEg-s9EG5wxT9bYL_nN2

I also set AccountsTemplates.configureRoute('verifyEmail'); 

Maybe I'm missing  something?

**Comment by splendido** [comment]
I'd say it should be

https://xstaging.goplatfarm.com/verify-email/UrDdu0RuG0eYAXnZrNtFw3AYEg-s9EG5wxT9bYL_nN2

without the `#!` after `.com/`

Have you correctly set up the `MAIL_URL` environment variable for production?

**Comment by splendido** [comment]
...mmm, actually `#!` is automatically added even if I head to the correct URL...
...any package you're using doing this?

**Comment by almogdesign** [comment]
Yes this is done by the Meteor AppCache package

**Comment by almogdesign** [comment]
I don't have the MAIL_URL setup I'm using mandrill SMPT

**Comment by splendido** [comment]
so that's the problem! (I recalled now about #405)
...why is it adding it there?

Do you think there could be a way to set the route with IR to match also that address?

**Comment by almogdesign** [comment]
Not sure 405 was the issue, I never had AccountsTemplates.configure setup which was casing the issue. 

AppCache requires it, do you think you can support this in package routes?

**Comment by splendido** [comment]
I'd have to reason a bit about how to specify the route path...
See [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L692)

**Comment by almogdesign** [comment]
I would just keep it simple and maybe add something like this (un tested code) 
 path += "/:paramToken" ||  path += "/#!:paramToken";

**Comment by almogdesign** [comment]
Bye the way I'm not sure this is the issue, because the reset password page loads. Maybe I'm missing something

**Comment by almogdesign** [comment]
I take it I only need the following 

AccountsTemplates.configureRoute('signIn');
AccountsTemplates.configureRoute('signUp');
AccountsTemplates.configureRoute('forgotPwd');
AccountsTemplates.configureRoute('changePwd');
AccountsTemplates.configureRoute('resetPwd');
AccountsTemplates.configureRoute('verifyEmail');

**Comment by splendido** [comment]
![ensuresignedin](https://cloud.githubusercontent.com/assets/6148980/7902242/ec5541fe-07b2-11e5-8f65-ad44b27c577a.png)

This is what I'm getting with the above link...
While in case it works good you should find yourself logged in or get some errror message...

**Comment by splendido** [comment]
Like here: https://useraccounts-bootstrap.meteor.com/verify-email/UrDdu0RuG0eYAXnZrNtFw3AYEg-s9EG5wxT9bYL_nN2

**Comment by splendido** [comment]
The curious thing is that this one works the same:
https://useraccounts-bootstrap.meteor.com/#!verify-email/UrDdu0RuG0eYAXnZrNtFw3AYEg-s9EG5wxT9bYL_nN2
(with the `#!`)

could you please post all your AT configuration file?
...plus the set up of `ensureSignedIn` plugin?

**Comment by almogdesign** [comment]
Woops wrong version deployed, deploying now and testing

**Comment by almogdesign** [comment]
lib/config/useraccounts.js
```javascript
var myLogoutFunc = function(error){
    if (!error) {
        Router.go('atSignIn');
    }
};

AccountsTemplates.configure({
    // Behaviour
    confirmPassword: true,
    enablePasswordChange: true,
    forbidClientAccountCreation: false,
    overrideLoginErrors: true,
    sendVerificationEmail: true,
    lowercaseUsername: false,

    // Appearance
    showAddRemoveServices: false,
    showForgotPasswordLink: true,
    showLabels: true,
    showPlaceholders: false,
    showResendVerificationEmailLink: false,

    // Client-side Validation
    continuousValidation: false,
    negativeFeedback: false,
    negativeValidation: true,
    positiveValidation: true,
    positiveFeedback: true,
    showValidating: true,

    // Privacy Policy and Terms of Use
    privacyUrl: 'privacy',
    termsUrl: 'terms-of-use',

    // Redirects
    homeRoutePath: '/dashboard',
    redirectTimeout: 5000,

    // Hooks
    onLogoutHook: myLogoutFunc,

    // Texts
    texts: {
        button: {
            signUp: "Register"
        },
        title: {
            forgotPwd: "Recover Your Password"
        }
    }
});

var pwd = AccountsTemplates.removeField('password');
AccountsTemplates.removeField('email');

AccountsTemplates.addFields([
    {
        _id: "username",
        type: "text",
        displayName: "username",
        required: true,
        minLength: 5
    },
    {
        _id: 'email',
        type: 'email',
        required: true,
        displayName: "email",
        re: /.+@(.+){2,}\.(.+){2,}/,
        errStr: 'Invalid email'
    },
    pwd,
    {
        _id: 'firstName',
        type: 'text',
        displayName: "First Name",
        required: true
    },
    {
        _id: 'lastName',
        type: 'text',
        displayName: "Last Name",
        required: true
    }
]);

AccountsTemplates.configureRoute('signIn');
AccountsTemplates.configureRoute('signUp');
AccountsTemplates.configureRoute('forgotPwd');
AccountsTemplates.configureRoute('changePwd');
AccountsTemplates.configureRoute('resetPwd');
AccountsTemplates.configureRoute('verifyEmail');
```

lib/router.js
```javascript
var redirectToDashboard = function(){
    if (Meteor.user()) {
        Router.go('dashboard');
    } else {
        this.next();
    }
};

var requireAdminUser = function() {
    var user = Meteor.user();
    if(user){
        if (!Roles.userIsInRole(user._id, ['administrator', 'manager'])) {
            this.render('accessDenied');
        } else {
            this.next();
        }
    }
};

/* 404 page */
Meteor.startup(function(){
    Router.route('/(.*)', function() {//regex for every route, must be last
        if (this.ready()) {
            document.title = "404";
            this.render('notFound');
        } else this.render('loading');
    });
});

Router.plugin('ensureSignedIn', {
    except: ['homeSite', 'atSignIn', 'atSignUp', 'atForgotPwd', 'atResetPwd', 'atVerifyEmail']
});

Router.onBeforeAction(redirectToDashboard, {only: ['homeSite', 'atSignIn', 'atSignUp', 'atForgotPwd', 'atResetPwd', 'atVerifyEmail']});
Router.onBeforeAction(requireAdminUser, {only: ['createOrganization', 'organization' , 'editOrganization', 'usersPage', 'addUser', 'editUser',  'addProducer', 'editProducer', 'addBlock' , 'editBlock', 'settings']});
```

**Comment by almogdesign** [comment]
You can test it now, noting happens - https://xstaging.goplatfarm.com/#!verify-email/UrDdu0RuG0eYAXnZrNtFw3AYEg-s9EG5wxT9bYL_nN2

not verified and not getting the expired message

**Comment by almogdesign** [comment]
I think for some reason $("#at-field-email").val("") is always empty

**Comment by splendido** [comment]
Tested it locally with:

```javascript

var redirectToDashboard = function(){
  if (Meteor.userId() && !Meteor.isLoggingIn()) {
      Router.go('dashboard');
  } else {
      this.next();
  }
};

var requireAdminUser = function() {
  if (Meteor.isLoggingIn()) {
    this.render('loading');
  }
  else {
    var user = Meteor.user();
    if (!user || !Roles.userIsInRole(user._id, ['administrator', 'manager'])) {
        this.render('accessDenied');
    } else {
        this.next();
    }
  }
};

// ...

Router.plugin('ensureSignedIn', {
  except: _.pluck(AccountsTemplates.routes, 'name').concat(['homeSite'])
});
Router.onBeforeAction(redirectToDashboard, {only: ['homeSite']});
```

Everything seems fine.
Lets try to deploy the above code and see whether you still get problems...

**Comment by almogdesign** [comment]
I don't have this, mine is a bit different 
```javascript
Router.plugin('ensureSignedIn', {
  except: _.pluck(AccountsTemplates.routes, 'name').concat(['homeSite'])
});
Router.onBeforeAction(redirectToDashboard, {only: ['homeSite']});
```

I also have the following which might be casing the issue 

```javascript
/* 404 page */
Meteor.startup(function(){
    Router.route('/(.*)', function() {//regex for every route, must be last
        if (this.ready()) {
            document.title = "404";
            this.render('notFound');
        } else this.render('loading');
    });
});
```

**Comment by almogdesign** [comment]
Just tested the code still getting verified: false here is the url -  https://xstaging.goplatfarm.com/verify-email/2ORWK-ezjPeKJAg_yUq520QSyO2NxfwOiH_mJUZtqK3

**Comment by almogdesign** [comment]
Same issue with Reset your password not working

**Comment by almogdesign** [comment]
Tested this out this is the same issue as password reset the onRun function hook never runs. core.js line 698

**Comment by almogdesign** [comment]
onRun: Called when the route is first run. It is not called again if the route reruns because of a computation invalidation. Note that this hook won't run again if the route is reloaded via hot code push. -- This might be casing the issue 

I changed onRun to onRerun and everything works, this might be better approach. But it does run twice. 

Reference following issues iron-router issues
https://github.com/iron-meteor/iron-router/issues/1219 
https://github.com/iron-meteor/iron-router/issues/1268

**Comment by almogdesign** [comment]
@splendido wanted to see if you had a chance to see this, and is there going to be a patch for this

**Comment by almogdesign** [comment]
I pretty sure this will not will not fix the verify email link issue, this code is in a different place it's here - https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L698-L707 

like I said the onRun hook does not execute. I chaned it to onRerun and that works but might be better to adjust it to onBefore as onRerun will run more then once

**Comment by splendido** [comment]
Please try to trace this down a little more.
Starting from [this comment](https://github.com/meteor-useraccounts/core/issues/173#issuecomment-70666032) which lead to [this PR](https://github.com/meteor-useraccounts/core/pull/241).

What I'm seeing now clicking on your link above, it the login form: this is quite weird.
I'd check your IR configuration and `onBeforeAction` hooks to better understand what's going on there.
...the only way I can suggest is to run a local version of `useraccounts:core` and debug the code in the browser, possibly adding some `console.log` at every IR callback you've registered.

Let me know

**Comment by almogdesign** [comment]
@splendido I went ahead and already debugged the code as I stated in the above comments because I have a global waitOn function setup none of the useraccounts:core onRun hooks are being executed. 

I tested out a fix which was changing onRun to onRerun or onBeforeAction which is what I would recommend doing. I'm seeing I'm not the only one having this issue. 

You can see my global router here 
```javascript
Router.configure({
    layoutTemplate: 'layoutSite',
    progress : true,
    progressSpinner : false,
    loadingTemplate: 'loading',
    waitOn: function(){
        if(getConnectionStatus() && Meteor.user()){
            return [Meteor.subscribe('user')];
        } else {
            this.render();
        }
    },
    data: function() {
        return Meteor.user();
    }
}); 
```

Created a change https://github.com/meteor-useraccounts/core/compare/master...almogdesign:patch-1

**Comment by splendido** [comment]
The `onBeforeAction` hook is definitely not the right place!
It can run more than once and from the second time one, you'd get an error saying that the token is expired...

I'm still convinced that your global configuration has something weird.
I've never seen a `this.render()` within a `waitOn` hook: I think it could by-pass any other rule possibly set within `onBeforeAction` hooks to stop rendering the current page for some reasons...

Why don't you try to set the `waitOn` on all routes but AT ones?

```javascript
Router.waitOn(function(){
  if(getConnectionStatus() && Meteor.user()){
    return [Meteor.subscribe('user')];
  } else {
    this.render();
  }
}, {
  except: _.pluck(AccountsTemplates.routes, 'name')
});
```


or even try to deal with the subscription outside IR?
untested code...

```javascript
var userSubscr = null;
Tracker.autorun(function(){
  if(getConnectionStatus() && Meteor.user()){
    userSubscr = Meteor.subscribe('user');
  }
  else {
    if (userSubscr) {
      userSubscr.stop();
    }
    userSubscr = null;
  }
});
```

**Comment by almogdesign** [comment]
No that's not it I just tested it without this.render and the verify email link still does not work, I pretty sure that's it the waitOn function. Same issue here https://github.com/meteor-useraccounts/core/issues/173#issuecomment-70666032 

Here is my router that I just tested 
```javascript
Router.configure({
    layoutTemplate: 'layoutSite',
    progress : true,
    progressSpinner : false,
    loadingTemplate: 'loading',
    waitOn: function(){
        if(getConnectionStatus() && Meteor.user()){
            return [Meteor.subscribe('user')];
        } 
    },
    data: function() {
        return Meteor.user();
    }
});
```

**Comment by splendido** [comment]
Could you please try also with this:

```javascript
Router.configure({
    layoutTemplate: 'layoutSite',
    progress : true,
    progressSpinner : false,
    loadingTemplate: 'loading',
    data: function() {
        return Meteor.user();
    }
});

Router.waitOn(function(){
  if(getConnectionStatus() && Meteor.userId()){
    return [Meteor.subscribe('user')];
  }
}, {
  except: _.pluck(AccountsTemplates.routes, 'name')
});
```

**Comment by almogdesign** [comment]
@splendido I just tested this, did not work I also doubled checked the DB to see if the user was verified

**Comment by almogdesign** [comment]
@splendido any news about this, suggestions?

**Comment by splendido** [comment]
@almogdesign, unfortunately I have no time right now to dig further into this problem.

Could you try to start form a [boilerplate](https://github.com/meteor-useraccounts/boilerplates) of your choice and add part of your app piece by piece?
I'm really curious to understand what the problem is, but if you could be so kind to try this approach that would be great!

**Comment by DavidSichau** [comment]
I had the same issue. It was caused by an onRun hook in iron router. As soon as I removed it everything worked again.

**Comment by rjayako** [comment]
@DavidSichau Can you tell me where exactly you removed this?

**Comment by DavidSichau** [comment]
@rjayako I used a `onRun` handler for my piwik analytics. Now instead of using a `onRun` handler I use `onBeforeAction` and everything works fine.

```
var oldRoute = ""; //fix for onRun Problem of ironRouter
Router.onBeforeAction(function(){
    if(Meteor.isClient) {
        var route = Router.current().url;
        if(route !== oldRoute) {
            console.log(route);
            Meteor.Piwik.trackPage(route);
            oldRoute = route;
        }
    }
    this.next();
});
```

**Comment by kylepierce** [comment]
I am having this issue as well except its sending an email with /#/verify-email/

**Comment by brylie** [comment]
Are these currently the AccountsTemplates routes?

```
'atSignIn', 'atSignUp', 'atForgotPwd', 'atResetPwd', 'atVerifyEmail'
```

**Comment by brylie** [comment]
I am getting an error that says 'must be logged in' when viewing a password reset route. I have the following configuration:

```js
// in /client/routes/_config.js
var anonymousRoutes = [
  'login',
  'atChangePwd',
  'atEnrollAccount',
  'atForgotPwd',
  'atResetPwd',
  'atSignIn',
  'atSignUp',
  'atVerifyEmail',
  'atresendVerificationEmail'
];

// User login required for all areas of site
//Router.plugin('ensureSignedIn', {except: anonymousRoutes});
```

```js
// in /lib/accounts.js
AccountsTemplates.configure({
  // Behavior
  enablePasswordChange: true,
  showForgotPasswordLink: true
});

// Configure AccountsTemplates routes
AccountsTemplates.configureRoute('signIn');
AccountsTemplates.configureRoute('signUp');
AccountsTemplates.configureRoute('forgotPwd');
AccountsTemplates.configureRoute('changePwd');
AccountsTemplates.configureRoute('resetPwd');
AccountsTemplates.configureRoute('verifyEmail');
```

I am using iron-router, and have installed useraccounts:iron-router package.
