### ISSUE TITLE
Reset password error - Uncaught Error: Match error: Expected string, got object

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#411]
I'm getting the following error message when testing out the reset password 

Uncaught Error: Match error: Expected string, got objectn @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:21e.resetPassword @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:72E.atPwdFormEvents.submit #at-pwd-form @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:212(anonymous function) @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:64e._withTemplateInstanceFunc @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:64(anonymous function) @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:64(anonymous function) @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:63c._withCurrentView @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:63(anonymous function) @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:63(anonymous function) @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:63ie.event.dispatch @ 1b6d362a6b5cf33ccf07ab04bb45f2a3d5320a98.js:50g.handle

**Comment by splendido** [comment]
A bit more of context, please?
...when do you get the error?
After doing what?

**Comment by almogdesign** [comment]
I land on the change password route, I fill in new password (twice) and click the button that's when I get the error

**Comment by splendido** [comment]
Lets try to debug [this block of code](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L273-286) in your browser (put a bearkpoint on the first line...).
And try to see what you get on [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L274) for `AccountsTemplates.paramToken` and `password`...

**Comment by splendido** [comment]
[Accounts.resetPassword](https://docs.meteor.com/#/full/accounts_resetpassword) requires two strings

**Comment by almogdesign** [comment]
You can see the issue here - https://xstaging.goplatfarm.com/#!forgot-password 
almog[@]scoreoid.net

**Comment by almogdesign** [comment]
I'm having no luck debugging this, you can see the error here  - https://xstaging.goplatfarm.com/#!reset-password/lVAjYl5iqapjQipWFWMok85CPwWifUu7H8sziI9h3HS

**Comment by splendido** [comment]
I've just tried with your link...
...and it worked! :-)
I was able to see the `Email sent!` message for a couple of seconds then a redirect to `/dashboard` took place.
...I'd suggest to redirect to `/` thereafter, so to show the normal login form without the `Must be logged in!` error message.

```javascript
AccountsTemplates.configureRoute('forgotPwd', {
    redirect: '/',
});
```

**Comment by almogdesign** [comment]
That's not the issue, it sends the reset password email but once you get the email click on the link, go to the change password page you can't change the password you get that error in the console

**Comment by almogdesign** [comment]
Attached gif, not sure how to make it any clearer 
![password_issue](https://cloud.githubusercontent.com/assets/169507/7912335/36db00da-086f-11e5-8b77-8319161f1e5e.gif)

**Comment by splendido** [comment]
Sorry I got lost...

**Comment by splendido** [comment]
the problem is `AccountsTemplates.paramToken` is `undefined`!

if you head to https://useraccounts-bootstrap.meteor.com/reset-password/lVAjYl5iqapjQipWFWMok85CPwWifUu7H8sziI9h3HS open up browser's console and type `AccountsTemplates.paramToken` you'll see to token taken from the URL.

if instead you head to https://xstaging.goplatfarm.com/#!reset-password/lVAjYl5iqapjQipWFWMok85CPwWifUu7H8sziI9h3HS and do the same, you'll get undefined...

**Comment by splendido** [comment]
this must be a problem with the route path which is defined [here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L692) as `/reset-password/:paramToken`.
The `paramToken` value is the picked up [here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L721).
...the curious thing is that `Router.current().params.paramToken` works fine in both cases...

Please try to debug this considering you're using `appcache` which changes the URLs...

**Comment by splendido** [comment]
I tried [your settings](https://github.com/meteor-useraccounts/core/issues/410#issuecomment-107200253) with [my changes](https://github.com/meteor-useraccounts/core/issues/410#issuecomment-107381145) within a local app, also adding `appcache`.
And everything seems to work for me...

**Comment by almogdesign** [comment]
Just tested your changes still not working you can test it  https://xstaging.goplatfarm.com/

**Comment by almogdesign** [comment]
Just tested it locally again still getting the same console error 

Uncaught Error: Match error: Expected string, got object

**Comment by almogdesign** [comment]
When I test it by AccountsTemplates.paramToken I'm getting null

**Comment by almogdesign** [comment]
I'm thinking it might be better to use "Router.current().params.paramToken" as this seems to work on my end when I test. 

I think something is causing a conflict with the URL not sure what it is maybe a package I checked all the routes I don't have reset-password router set anywhere. 

Is there way for me to hardcode or set a workaround that would use "Router.current().params.paramToken"

**Comment by splendido** [comment]
Lets try this:
1. go to your app folder
2. `mkdir packages && cd packages`
3. `git clone https://github.com/meteor-useraccounts/core.git`
4. ` cd..`
5. put a `console.log('setting paramToken to ' + this.params.paramToken);` just before [this line](https://github.com/meteor-useraccounts/core/blob/98aa2a8471dfb25bbc70e38288ac427ea3e95a19/lib/core.js#L721)
6. put a `console.log('clearing paramToken!!!');` just before [this line](https://github.com/meteor-useraccounts/core/blob/98aa2a8471dfb25bbc70e38288ac427ea3e95a19/lib/core.js#L730)
7. meteor
8. test the reset-password form...

I bet there's something with your IR configuration that causes the `onStop` callback to be called...

**Comment by almogdesign** [comment]
I did the following and run meteor add useraccounts:core and run meteor remove useraccounts:bootsstrap 

But now I get - 
Couldn't find a template named "fullPageAtForm" or "fullPageAtForm". Are you sure you defined it?

If I leave useraccounts:bootstrap I'm not seeing the console logs

**Comment by almogdesign** [comment]
I added the bootstrap package locally, and tested still getting the console log. It seems the error hits before the log.

**Comment by almogdesign** [comment]
I'm running a test before the error hits, at at_pwd_forms.js 

before 
return Accounts.resetPassword(AccountsTemplates.paramToken, password, function(error) {

I'm seeing that console.log(AccountsTemplates); has no object or paramToken or anything with hash

**Comment by almogdesign** [comment]
Been testing it some more it seems that the onRun in core.js (https://github.com/meteor-useraccounts/core/blob/98aa2a8471dfb25bbc70e38288ac427ea3e95a19/lib/core.js#L721) 

is never being run, if I move / add  AccountsTemplates.paramToken = this.params.paramToken; to the onBefore hook it's fine and works. Still not sure why it's happing. Will do a pull request

**Comment by almogdesign** [comment]
Never mind can't create a pull request, it's not open. Here is a gist with the fix https://gist.github.com/almogdesign/15d770ee2873f2d525b2

**Comment by almogdesign** [comment]
Same issue as here - https://github.com/meteor-useraccounts/core/issues/410#issuecomment-107200253 onRun hook not firing

**Comment by almogdesign** [comment]
@splendido hi have you had a chance to check the onRun hook issue?

**Comment by splendido** [comment]
pushing out 1.11.1 right now, let me know if it works!

tnx!

**Comment by almogdesign** [comment]
Tested works perfect thanks for the great support
