### ISSUE TITLE
Useraccounts 1.11.0 - login TypeError Exception

### ISSUE THREAD

**Issue by ctaloi** [meteor-useraccounts/core#413]
Hello,

Updated to 1.11.0 and am now seeing an Exception thrown when logging in.
I reviewed the breaking change (#388) but I'm not sure if this is my issue.

Here is the exception:

```
I20150602-17:00:59.016(-4)? Exception while invoking method 'login' TypeError: Cannot read property 'type' of undefined
I20150602-17:00:59.017(-4)?     at packages/useraccounts:core/lib/server.js:95:1
I20150602-17:00:59.017(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150602-17:00:59.017(-4)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150602-17:00:59.017(-4)?     at packages/accounts-base/accounts_server.js:62:1
I20150602-17:00:59.017(-4)?     at [object Object]._.extend.each (packages/callback-hook/hook.js:102:1)
I20150602-17:00:59.017(-4)?     at validateLogin (packages/accounts-base/accounts_server.js:59:1)
I20150602-17:00:59.017(-4)?     at attemptLogin (packages/accounts-base/accounts_server.js:251:1)
I20150602-17:00:59.017(-4)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:411:1)
I20150602-17:00:59.017(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
I20150602-17:00:59.017(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
```

What else can I provide you that would assist in determining the issue?

My configuration is [here](https://gist.github.com/ctaloi/3ed0348b11a2dbda5fb0)

If I roll back to 1.10.0 I no longer throw the Exception

```
meteor remove useraccounts:materialize
meteor add useraccounts:materialize@=1.10.0
```

**Comment by splendido** [comment]
Hello @ctaloi 
Thanks for reporting!
It seems to be a typo on [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/server.js#L95)

Could you pelase try to turn it into:

```javascript
 if (!attempt.type !== "password" || attempt.methodName !== "login") {
```

I'll publish a patch as soon as you confirm this fixes the problem.

tnx!

**Comment by outaTiME** [comment]
Same stack trace here guys =(

I try to update this line and it works, we are waiting the official patch ...

**Comment by splendido** [comment]
Ok, I'll push it out in a few minutes!
Thanks for confirming the fix @outaTiME!

**Comment by outaTiME** [comment]
yay !!! awesome package pal :+1:
