### ISSUE TITLE
Form submit button always disabled when audit-argument-checks added.

### ISSUE THREAD

**Issue by TomomiSawako** [meteor-useraccounts/core#416]
Form submit button always disabled when meteor's audit-argument-checks added.

More about audit-argument-checks package.
http://docs.meteor.com/#/full/auditargumentchecks

**Comment by splendido** [comment]
@TomomiSawako is this still an issue?
I've just checked with the `audit-argument-checks` package and everything seems fine.
There are only two medhods and one publish within all useraccounts packages and all are currently checking arguments with `check`.

Please open again if it's not solved.
