### ISSUE TITLE
How should I translate the default error msgs that haven't been covered by t9n?

### ISSUE THREAD

**Issue by sunaiwen** [meteor-useraccounts/core#418]
![image](https://cloud.githubusercontent.com/assets/3401641/8002079/52e91438-0b9e-11e5-8d05-c15dd747158f.png)

It seams like that t9n doesn't cover those warning msgs. So I want to replace the default 'Required Field' msgs with Chinese.

But I cannot find the certain property key of `texts.error` object in document.

**Comment by splendido** [comment]
you could define the translation by yourself using something like:

```javascript
T9n.map({
  "zh_cn": {
    "Required Field": "chinese translation"
  }
});
```

See [docs](https://github.com/softwarerero/meteor-accounts-t9n#define-translations)

**Comment by sunaiwen** [comment]
Thank you very much. I should have read the docs more carefully. :pensive:

**Comment by zhaoyao91** [comment]
@sunaiwen does this work for you? I've tried but it didn't work. I put these code in ·lib/config/t9n.js·

**Comment by sunaiwen** [comment]
@zhaoyao91 I have left that meteor project for a while. Looking back to the code, I found that I just made configuration for every individual meteor package using the way the package provides. Let's take the _[autoform](https://github.com/aldeed/meteor-autoform)_ package for a example, I found some code like this:

```js
SimpleSchema.messages({
    required: "「[label]」不能是空白",
    minString: "「[label]」最少 [min] 个字符",
    maxString: "「[label]」最多只能有 [max] 个字符",
    minNumber: "「[label]」最小长度为 [min]",
    maxNumber: "「[label]」最大长度为 [max]",
    minDate: "「[label]」必须在 [min] 当天或之后",
    maxDate: "「[label]」不能在 [max] 之后",
    badDate: "「[label]」日期格式不对"
});
```

So maybe you should try to checkout the document of the package that you are using.
