### ISSUE TITLE
Question about email address

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#420]
Hi, 
I'm seeing that user accounts package creates (which is great bye the way) creates the following in the database 
```javascript
email: {
      verificationTokens: [
        {
          token: "MdMadUAQNcpEv05JK58mP1O3RE-kEuOQSD75gr6lD5d",
          address: "banelinoorganico@gmail.com",
          when: ISODate("2015-06-08T10:03:49.949Z")
        }
      ]
    },  

emails: [
    {
      address: "banelinoorganico@gmail.com",
      verified: false
    }
  ],
```

Is this correct and if I want to update a users email address which one is correct to use? 
Also how will this work with http://docs.meteor.com/#/full/accounts_createuser when creating a user on the client

**Comment by splendido** [comment]
Hello @almogdesign,
actually `useraccounts` is using [the regular API from the accounts](https://docs.meteor.com/#/full/accounts_api) package and does not directly modify the DB in any way.

I guess the email stuff is mainly connected to the password login so lets have a look also at the [password API](https://docs.meteor.com/#/full/accounts_passwords) and in particular to [Accounts.changePassword](https://docs.meteor.com/#/full/accounts_changepassword) which you can call from a method or wherever you need it to update a user's password.
In case you'd like to set a new password form the server-side [Accounts.setPassword](https://docs.meteor.com/#/full/accounts_setpassword) is what you're looking for.

About the creation of new users from the client-side, I suggest you to call a server-side method which check all permissions and the likes and eventually calls [Accounts.createUser](https://docs.meteor.com/#/full/accounts_createuser) in a safe side...

Let me know if you need more pointers!
