### ISSUE TITLE
Materialize (addFields) radio buttons are broken

### ISSUE THREAD

**Issue by mohsin-rafii** [meteor-useraccounts/core#421]
You can't select radio buttons because 'for' attribute on label tag is missing. If you go through generated html of below code there will be no 'for' attribute on label tag.

AccountsTemplates.addField({
    _id: "fruit",
    type: "radio",
    displayName: "Preferred Fruit",
    select: [
        {
        text: "Apple",
        value: "aa",
      }, {
        text: "Banana",
        value: "bb",
      }, {
        text: "Carrot",
        value: "cc",
      },
    ],
});

**Comment by garysxn** [comment]
I have same problem, unable to select radio buttons because 'for' attribute on label tag is missing.
{
        _id: 'gender',
        type: 'radio',
        placeholder:'Gender',
        displayName: 'Gender',
        select:[{
                    text: "Male",
                    value: "male",
                    //label: "male",
                },
                {
                    text: "Female",
                    value: "female",
                    //label: (for="email"),
                }]
    }

**Comment by splendido** [comment]
Should be fine now.
Tnx!

**Comment by garysxn** [comment]
Thanks @splendido
