### ISSUE TITLE
Issue with Form Template being blank

### ISSUE THREAD

**Issue by logitimate** [meteor-useraccounts/core#423]
Hello, I just started a meteoric project and was wanting to drop useraccounts in it. I tried putting in the blank template {{> atForm}} and it shows up blank. Nothing shows up on the screen where the form should be. However, if I add a state like {{> atForm state='signUp'}} it will work. Just curious as to why this might be happening. Fairly new to Meteor.

**Comment by splendido** [comment]
That's weird!
If you can see something for the sign-up state, I guess you correctly added `accounts-passowrd` ore some other 3rd party login service...

Have you had a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates)?

**Comment by bluxu** [comment]
I'm also suffering this problem. I've copied one of the boilerplates and have accounts-password added. Does anyone have an idea why this might happen?

**Comment by bluxu** [comment]
Don't worry - I've worked it out myself! The form is deliberately blank when you are signed in. I was already signed in, hence my confusion.

**Comment by splendido** [comment]
@bluxu: Yes, that might be confusing...
It's not empy in case you're using OAuth services and you set `showAddRemoveServices`, but this will be definitely changed in v2.0

@logitimate have you figured out the problem? Was the same as @bluxu's one?
Please let me know if you need more help!
