### ISSUE TITLE
Is there a way to embed change password template 

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#424]
I wanted to know if it's possible to embed the change password form into my own template like a users profile template

**Comment by splendido** [comment]
That's should be easily duable, what about:

```
<template name="userProfile">
  ...
  {{> atForm state='changePwd'}}
  ...
</template>
```
See [Templates](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#templates) and [Internal States](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#internal-states).

Let me know whether this answers your question.
