### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joetm** [meteor-useraccounts/core#426]
Can you please extend the documentation with pointers on how to use the packages?
Or add a sample app that shows how to use it.

**Comment by splendido** [comment]
Hi @joetm,
I know the current documentation is getting a mess (and would need a bug refactor..), but I'm wondering whether you really didn't found anything useful to answer your questions.
So I'm interested to hear your point of view on it :-)

Let's have a look at [The Useraccounts Guide](https://github.com/meteor-useraccounts/core#the-useraccounts-guide) paragraph in the main `README.md` and then at the [Quick Start](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#quick-start) section in the Guide. Whitin this latter section you should also find a [Boilerplates](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#boilerplates) section with a pointer to the [boilerplates repository](https://github.com/meteor-useraccounts/boilerplates) where you can find the code for the sample applications I deployed on `meteor.com` you can find listed [here](https://github.com/meteor-useraccounts/core#some-details).

Please let me know how you would like the documentation structured, and feel free to chime in the [Trello Board](https://trello.com/b/NWHVV4ZA/useraccounts-2-0-roadmap) to discuss about it.

Cheers,
Luca

**Comment by joetm** [comment]
Sorry, I must have overlooked the link to the Guide. Scanning through it, I see it should give me all the info that I need.
I was mainly using the way to show the login in the templates, but I see it can be done with
        {{> atForm}}

The "quickstart guide" might be helpful in the main readme. Just a short sample on how to set it up and integrate it in an existing app. The stuff about working locally on the other hand is not too interesting for me.

**Comment by splendido** [comment]
Yes, makes sense!
Thanks for the feedback, I'll start a fresh new Readme for v2.0 soon...
