### ISSUE TITLE
Logout feature with useraccounts:unstyled

### ISSUE THREAD

**Issue by tylerzika** [meteor-useraccounts/core#429]
I can't find a way to logout with this package. Can someone show me where in the documentation it tells you how to do so?

**Comment by tylerzika** [comment]
Figured it out. This would do it.

    Template.layout.events({  
      'click a.logout': function() {
        Meteor.logout(function() {
          // Redirect to login
          Router.go('/account');
        });

        return;
      }
     });

**Comment by splendido** [comment]
You might want to use `AccountsTemplates.logout()` which let you benefit from the `onLogoutHook` configuration.
You can find a description how to configure it [among the options](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options).

But you couldn't have found `AccountsTemplates.logout()` easilt: I realized right now it's not documented yet :(

Tnx!

**Comment by tylerzika** [comment]
No problem! I skimmed the docs 2x trying to find something on logout. Nothing really.
