### ISSUE TITLE
Document AccountsTemplates.logout()

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#430]

**Comment by harellevy** [comment]
+1

**Comment by jxm262** [comment]
+1 , a little confused how to use this myself

**Comment by splendido** [comment]
It should be used in place of the regular `Meteor.logout()` to be able to leverage the `onLogoutHook` [option](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options).

See the [code](https://github.com/meteor-useraccounts/core/blob/master/lib/client.js#L479-L488)

**Comment by splendido** [comment]
Anyone willing to create a PR to add a few lines to the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)?

**Comment by jxm262** [comment]
@splendido  sure, i'll work on this now :)

**Comment by splendido** [comment]
Tnx!
