### ISSUE TITLE
Even more route options

### ISSUE THREAD

**Issue by Asparagirl** [meteor-useraccounts/core#432]
Thanks for your work closing #409, but I'm back with more requests for route options.

This works...

```javascript
AccountsTemplates.configureRoute('signIn', {
    name: 'signin',
    path: '/login',
    template: 'useraccounts',
    title: 'Sign In',
    parent: 'home',
    // Where to redirect after a successful sign-in?
    redirect: function() {
        var user = Meteor.user();
        if (user)
          Router.go('/player/id/' + user._id);
    }
});
```

...but this (adding an action, so I can set the page title) doesn't...

```javascript
AccountsTemplates.configureRoute('signIn', {
    name: 'signin',
    path: '/login',
    template: 'useraccounts',
    title: 'Sign In',
    parent: 'home',
    action: function () {
        SEO.set({ title: 'Sign In - ' + Meteor.App.NAME });
    },
    // Where to redirect after a successful sign-in?
    redirect: function() {
        var user = Meteor.user();
        if (user)
          Router.go('/player/id/' + user._id);
    }
});
```

Thanks!

**Comment by splendido** [comment]
Do you have any suggestion to support this?

**Comment by Asparagirl** [comment]
Do you mean, do I personally know how to modify the code to support this?

Nope.  :-)

**Comment by maksimkurb** [comment]
+1

**Comment by splendido** [comment]
well, actually this is a problem with your `action` method.
I've just checked it and with:

```javascript
AccountsTemplates.configureRoute('signIn', {
  action: function () {
    console.log('SEO action!');
    this.render();
    this.renderRegions();
  },
});
```

it works like a charm ;-)

Lets have a look at the iron-router guide, especially the section about [route options](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#route-specific-options)

**Comment by splendido** [comment]
@jshimko would you mind adding a mention about this within the `useraccounts:iron-routing` docs?
[These lines](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/core.js#L129-L131) pick up any additional option to `AccountsTemplates.configureRoute` which is then passed to `Router.route` (see e.g. [this line](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/core.js#L177))
