### ISSUE TITLE
No redirect after reset password

### ISSUE THREAD

**Issue by fabyeah** [meteor-useraccounts/core#436]
I guess this is related to #173.

I used @timothyarmes solution and put a
`if (Router.current().route.getName() !== 'resetPassword') {`

in the waitOn function of my global Router.configure, Without that it won't redirect after hitting the reset password button. I guess it is because I have a `if (Meteor.user())`subscription in it.

I don't really want to clutter my global router config with these route exceptions. Don't know if there is a better way, or if this can be fixed in the package...?

**Comment by steve-ross** [comment]
I also had an issue with this and it was a huge pain to figure out.

Im using ensureSignedIn with an 'except' as well.

Here is my solution: 

```
AccountsTemplates.configureRoute('resetPwd', {
  waitOn: function(){
    return Meteor.subscribe('enrolledUser',this.params.paramToken);
  },
  data: function(){
    if(Meteor.userId())  Router.go('root');
    else return Meteor.users.findOne();
  }
});
```

**Comment by splendido** [comment]
@fabyeah @steve-ross is this still an issue with the new [`useraccounts:iron-routing`](https://github.com/meteor-useraccounts/iron-routing) package?

If yes, please open ai issue [here](https://github.com/meteor-useraccounts/iron-routing/issues)

**Comment by fabyeah** [comment]
@splendido I have since switched to flow-router, removed the workaround and haven't had the issue after that.
