### ISSUE TITLE
Add Page For Configuring Options Set On Signup

### ISSUE THREAD

**Issue by davidjaenisch** [meteor-useraccounts/core#437]
Please add a template for configuring options that are set on the signup page. You can add fields to the signup page, but there doesn't appear to be any way to modify them after creation except by making your own page.

An option should be added to access a similar page as a second step after OAuth so that users can specify needed fields, such as birthday or location.

**Comment by splendido** [comment]
Do you mean something like a user profile page?
...if this is the case, I'm not sure we could be general enough to be good for everyone.

Why don't you create your profile page with `aldeed:autoform` or similar?
I think Telescope is doing it like that...
