### ISSUE TITLE
Version 2.0, next SF DevShop, weddings, honeymoons, and the like....

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/core#438]
Dear all,

while in the last couple months `useraccounts` packages got some good traction and `useraccounts:bootstrap` is not reacing the top 50s of the most used packages during the last year, I unfortunately had very little time to work on the project...

This is partially because I got quite much involved with [autopublish.meteor.com](https://autopublish.meteor.com/) which seems a very good option to keep wrapper packages up to date with upstream repositories...

...but, the real reason is I'm getting married on Saturday!
You can imagine I had a number of things to be sorted out and I'm a bit tired a the moment ;-)

But the good news is I'll be around in California from 6/22 to 7/17 to chilout and relax with Serena (my **awesome future wife**) and our children!

This means both I'll be (not quite by chance though...) at the next June DevShop in SF giving a [lightning talk](http://lightning-talks.meteor.com/) about `useraccounts` and I'll be quite well re-charged to continue on v2.0 of this project when I'll be back home!

So please, lets have a bit of patience with those issues that won't get an answer with the usual timing...
I hope already experienced useraccounts users will be available to help sort them out, in case it's just a matter of understanding how to use the packages ;-)

Thanks everyone who has contributed to useraccounts, or is simply using it, for making it a so great package!

Talk to you soon, cheers!
Luca

**Comment by gussandy** [comment]
Luca wishing you the very best in your marriage

**Comment by dandv** [comment]
Congratulations!

[Looking forward to seeing you at DevShop](http://lightning-talks.meteor.com)!

**Comment by MarcioAntonioRezende** [comment]
Congratulations for u.... i has a error in accounts...
I has installed Semantic-ui and his install router... but now, app can't login, the message s
login forbbiden

**Comment by splendido** [comment]
I'm now back home and I'll try to get back to useraccounts asap.

Thank you all for your patience!

P.S. California is an awesome place and Meteor HQs as well as people from MDG are even more fantastic! :-)
