### ISSUE TITLE
"Unkown key" error using preSignUpHook

### ISSUE THREAD

**Issue by wlundgren** [meteor-useraccounts/core#442]
Hello
I can't seem to get hook "preSignUpHook" to work.

If I add the hook to my otherwise working configuration I get the following error:
*=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20150623-08:34:03.273(2)? (STDERR) Error: Match error: Unknown key in field preSignUpHook
W20150623-08:34:03.274(2)? (STDERR)     at packages/check/match.js:299:1
W20150623-08:34:03.274(2)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150623-08:34:03.274(2)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20150623-08:34:03.274(2)? (STDERR)     at check (packages/check/match.js:32:1)
W20150623-08:34:03.274(2)? (STDERR)     at [object Object].AT.configure (packages/useraccounts:core/lib/core.js:490:1)
W20150623-08:34:03.277(2)? (STDERR)     at app/lib/accountstbConfig.js:4:19
W20150623-08:34:03.277(2)? (STDERR)     at app/lib/accountstbConfig.js:182:3
W20150623-08:34:03.278(2)? (STDERR)     at /home/elliott/Documents/profes/business ideas/lifeHopping/dev/HeadHopping/.meteor/local/build/programs/server/boot.js:222:10
W20150623-08:34:03.278(2)? (STDERR)     at Array.forEach (native)
W20150623-08:34:03.279(2)? (STDERR)     at Function._.each._.forEach (/home/elliott/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)*

I add the hook like this:
```javascript
AccountsTemplates.configure({
	// ... other configurations
  preSignUpHook: function(password, info) {
    // do nothing
  },
  // ... other configurations
});
```

I have useraccounts:bootstrap 1.11.1 and meteor update does not make any upgrade so I assume it is the latest version.

For what Ive been able to work out, it looks like there exists no such hook (I use onSubmitHook and it works perfectly fine, by the way).
Does anyone know what's happening?

Thanks

**Comment by splendido** [comment]
[Here](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L132) is where the `preSignUpHook` is defined for the check pattern...

Have you found the problem meanwhile?

**Comment by splendido** [comment]
Just tried that and worked without problems....
