### ISSUE TITLE
flow-router-integration / It worked. But now it has an error.

### ISSUE THREAD

**Issue by candicom** [meteor-useraccounts/core#443]
It has now this error.

 Error: changePwd route configured but enablePasswordChange set to false!
W20150627-16:18:49.984(9)? (STDERR)     at [object Object].AT.setupRoute (packages/useraccounts:core/lib/core.js:658:1)
W20150627-16:18:49.984(9)? (STDERR)     at [object Object].AT.configureRoute (packages/useraccounts:core/lib/core.js:559:1)

----------

From this commit,

commit 1e357cb73052f245b390e1132175ae68ac6d9f37
Merge: 8695664 25504ec
Author: philippspo <philipp.sporrer@planifica.de>
Date: Tue Jun 9 14:25:55 2015 +0200

Merge branch 'flow-router-integration' of https://github.com/PhilippSpo/core into flow-router-integration
Conflicts:
lib/field.js

The error is,

 Error: Match error: Unknown key in field placeholder
W20150627-16:26:20.613(9)? (STDERR)     at packages/check/match.js:299:1
W20150627-16:26:20.613(9)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)

------------

From this commit,

commit bef7d8770931ec33e7301b0791def08673c42722
Author: philippspo <philipp.sporrer@planifica.de>
Date: Tue Jun 9 14:24:19 2015 +0200

added route names

It doesn't have an error.

---------------

So I guess...

commit 8695664f7c70bc3b12e2825c12c72fdc8bfc47d6
Author: philippspo <philipp.sporrer@planifica.de>
Date: Tue Jun 9 14:24:45 2015 +0200

displayName now can also be a function (for i18n)

>>This commit is making this error. ( Error: Match error: Unknown key in field placeholder)

And

commit 24a4a6d3a3e28520997dbb6049686c5b35d59ee3
Author: philippspo <philipp.sporrer@planifica.de>
Date: Wed Jun 10 23:32:42 2015 +0200

flow router update
moved from middlewares to triggers
    moved setupRoutes call to the configureRoutes methos
moved setupRoutes call to the configureRoutes methos

>>This commit is making this error. (Error: changePwd route configured but enablePasswordChange set to false!)

**Comment by splendido** [comment]
@candicom could you please check if it is any better now with the latest update #490?

**Comment by splendido** [comment]
The routing parts are no more part of the core package.
Please check the `flow-routing` package (not yet published...)
