### ISSUE TITLE
Having an error when try to connect url page with requiredSignIn middleware directly browser 

### ISSUE THREAD

**Issue by candicom** [meteor-useraccounts/core#444]
Having an error when try to connect url page with requiredSignIn middleware directly browser 

'middleware' is deprecated. Use 'triggers' instead
Exception from Tracker recompute function:
TypeError: Cannot read property 'form' of undefined
    at AT.setState (client.js:79)
    at ensureSignedIn (client.js:120)
    at AT.ensureSignedIn (client.js:154)
    at runMiddleware (utils.js:191)
    at Route._processMiddlewares (utils.js:191)
    at Route.callAction (utils.js:191)
    at utils.js:191
    at Object.Tracker.nonreactive (tracker.js:560)
    at utils.js:191
    at Tracker.Computation._compute (tracker.js:294)

And shows me blank page.

But first connect to home page and move to that requiredSignIn page, then It shows up.

I don't know the reason, But I think it's a bug.

I like flowRouter, But useraccounts not yet support flowRouter. So I think i have to move on IronRouter...

**Comment by splendido** [comment]
@candicom now you can also use FR with UserAccounts!
See [useraccounts:flow-routing](https://github.com/meteor-useraccounts/flow-routing)

In any case the error you're reporting is weird. Lets have a look a the [content protection](https://github.com/meteor-useraccounts/iron-routing#content-protection) section for the [useraccounts:iron-routing](https://github.com/meteor-useraccounts/iron-routing) package
