### ISSUE TITLE
latest flow-router 1.16+ breaks flow integration

### ISSUE THREAD

**Issue by benjamin79** [meteor-useraccounts/core#445]
Cannot read property 'form' of undefined

at useraccounts_core.js:1149 when i click on a pw reset link.
No error with flow-router 1.15.0

thank you for looking into it.

**Comment by nikhildaga** [comment]
I am experiencing the same issue.

**Comment by levid** [comment]
Same here, had to roll back to 1.15.0

**Comment by splendido** [comment]
use with flow-router@2.0 should now be fixed via #490.
