### ISSUE TITLE
change config on the fly

### ISSUE THREAD

**Issue by thomasspiesser** [meteor-useraccounts/core#449]
hey,
is it possible to change e.g. the title of the register form on the fly? i wanna use your template in 2 different location in my app and it should look different depending on where it is shown. for example, in one place i would like to hide the link to sign-in, cause i want to display (my own) sign in form and your register form side by side.
any thoughts on that?

**Comment by splendido** [comment]
in case you're using IronRouter you can play on the AccountsTemplates object within a `onBeforeAction` hook.
So I guess it should be enough to do something like:

`AccountsTemplates.texts.title.signIn = 'myTitle'`

...while to be able to show two different forms side by side you'll have to wait for v2.0 ;-)

Let me know if it works!
