### ISSUE TITLE
Flow Router - Social strategies

### ISSUE THREAD

**Issue by niallobrien** [meteor-useraccounts/core#450]
Hi, would be nice to know if social login strategies are on the way for Flow Router integration?

**Comment by splendido** [comment]
what do you mean with *strategies*?

...I'm back to work on v2.0 and the OAuth flow with *social* button is on its way for an alpha release or something.

**Comment by niallobrien** [comment]
Sorry, strategies comes from using passport.js.
Glad to hear oauth2.0 support is on the way.

**Comment by splendido** [comment]
well, with meteor you don't need `passport.js` and OAuth2.0 flows are already implemented by a number of packages, including `accounts-google`, `accounts-facebook`, etc.

Lets have a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) (the two using materialize CSS are the most up to date...) and you'll see a beautiful *Login with Google* button ;-)

for more details about configuring OAuth services, lets have a look at the official documentation about [Meteor.loginWith<ExternalService>](https://docs.meteor.com/#/full/meteor_loginwithexternalservice)

**Comment by niallobrien** [comment]
Thanks, I was simply under the impression that they only worked with Iron Router.
