### ISSUE TITLE
Social Buttons Load way too slow ( deploying to meteor.com servers)

### ISSUE THREAD

**Issue by abhisheksoni27** [meteor-useraccounts/core#454]
I am using the **user-account:core** package, and the login works fine using third party services. The only problem is that on initial load, that every time the page is loaded, it takes a while for the login buttons to appear. How can this be avoided? Maybe a certain loading theme, or something? The text appears btw, like, `Sign in` and register. But the social buttons appear after some time.

Here's my `account-config.js`

```
if (Meteor.isServer) {
    Meteor.startup(function() {
        // code to run on server at startup
        Accounts.loginServiceConfiguration.remove({
            service: "google"
        })
        Accounts.loginServiceConfiguration.insert({
            service: "google",
            clientId: "",
            secret: ""
        });
        Accounts.loginServiceConfiguration.remove({
            service: "github"
        })
        Accounts.loginServiceConfiguration.insert({
            service: "github",
            clientId: "",
            secret: "",
            requestPermission:'avatar_url'
        });
        Accounts.loginServiceConfiguration.remove({
            service: "twitter"
        })
        Accounts.loginServiceConfiguration.insert({
            service: "twitter",
            clientId: "",
            secret: ""
        });
        Accounts.loginServiceConfiguration.remove({
            service: "facebook"
        })
        Accounts.loginServiceConfiguration.insert({
            service: "facebook",
            appId: "",
            secret: ""
        });


    });
}
```

`Is it because of the remove()  function being called everytime?`

Here's the thread on [Meteor Forums](https://forums.meteor.com/t/social-buttons-load-way-too-slow/6563)

**Comment by splendido** [comment]
The problem is the list of configure OAuth services resides on a collection on the DB and its sbscription takes time to get ready...

If we don't want to show a spinner or something, the only solution might be using [`meteorhaks:fast-render`](https://atmospherejs.com/meteorhacks/fast-render)...

**Comment by splendido** [comment]
The thing is that the list of OAuth services comes from `Accounts.loginServiceConfiguration` which in turn picks it up from a [collection](https://github.com/meteor/meteor/blob/832e6fe44f3635cae060415d6150c0105f2bf0f6/packages/service-configuration/service_configuration_common.js#L6-L12).
That content is published [here](https://github.com/meteor/meteor/blob/587e02a692da86eaed03a8ff7a2c5010cda17ba3/packages/accounts-base/accounts_server.js#L662)  and subscribed to at client startup [here](https://github.com/meteor/meteor/blob/d8bedef10d07000f018c1d5948569ee28250f07f/packages/accounts-base/accounts_client.js#L15).

So its really a matter of the accounts management and the only option we have is to rely on [fast-render](https://atmospherejs.com/meteorhacks/fast-render) to send all the collection content on first page load.
