### ISSUE TITLE
'A field called username already exists!' - or does it?

### ISSUE THREAD

**Issue by mvanio** [meteor-useraccounts/core#456]
var user=AccountsTemplates.removeField('username');
    
    //AccountsTemplates.addField(
    //{
    //   _id: 'username',
    //   type: 'text',
    //   displayName: 'Preferred Name',
    //   minLength: 3,
    //   required: true
    // });

gives the error 'A field called username does not exist!', but the following code...

    //var user=AccountsTemplates.removeField('username');
     
    AccountsTemplates.addField(
    {
       _id: 'username',
       type: 'text',
       displayName: 'Preferred Name',
       minLength: 3,
       required: true
     });

gives 'A field called username already exists!'.

Does it exist or doesn't it? How can I remove the 'username' field? I'd like to just use email.

**Comment by mvanio** [comment]
OMG! How dumb. I just found a clash with another package. Closing issue.

**Comment by nicooprat** [comment]
Which one? Having the same issue right now...
