### ISSUE TITLE
how to load template after signin ??

### ISSUE THREAD

**Issue by devarashetty** [meteor-useraccounts/core#457]
i want to load completely a new template after signing in ( done by {{>loginButtons}} ) , can some one give me idea how to pass event on a signin button, thanks

**Comment by Tim-W** [comment]
have you tried using `homeRoutePath` in https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options

**Comment by splendido** [comment]
this is not the place to get help for `{{>loginButtons}}` ;-)

if you're using `accounts-ui` package and would like to switch to full-page templates, you're welcome to switch to the [useraccounts suite](https://atmospherejs.com/useraccounts)
