### ISSUE TITLE
Please remove onehanders.com from the "who's using it" list

### ISSUE THREAD

**Issue by bobmonsour** [meteor-useraccounts/core#459]
Hi Luca,

I have decided to remove login capability from the OneHanders.com site/app. You should probably remove it from the list of who is using the package.

It's no reflection on the package; it's just that requiring a login was posing an issue for people using the site and the value of requiring the login was lower than the value of increasing traffic.

I hope all is well with you.

Regards,
-Bob

**Comment by splendido** [comment]
np, I'll remove it right now!

I'm fine thanks, just got back from my honeymoon in California ;-)

**Comment by bobmonsour** [comment]
Congratulazioni per il tuo matrimonio!
 
I watched the dev shop video and saw you. Nice job!

I used to attend the San Francisco dev shops until recently. We moved to a place near Seattle, Washington. We just moved into a new house. Lots of unpacking to do.

Stay well.

Regards,
-Bob

**Comment by splendido** [comment]
Thank you Bob!
...so you're going to be busy too during the next days ;-)
My best wishes for your new house!
