### ISSUE TITLE
lib/methods.js sending unnecessary code to the client

### ISSUE THREAD

**Issue by elie222** [meteor-useraccounts/core#464]
The following code in lib/methods.js doesn't need to be sent to the client:
```
if (Meteor.isServer) {
    Meteor.methods({
        ATCreateUserServer: function(options){
```

Most of that file is server only code.

**Comment by splendido** [comment]
That's a good point!
we could save a few bytes but that's still an improovement...

**Comment by splendido** [comment]
Methods are now separated into two different files.
Thanks for the pointer!
