### ISSUE TITLE
Future: Add postSignup hook (for analytics)

### ISSUE THREAD

**Issue by elie222** [meteor-useraccounts/core#467]
I'd like to see this so that I can send an analytics event saying that the user has signed up

**Comment by splendido** [comment]
You can use the [onsubmithook](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#onsubmithook) I guess.

**Comment by elie222** [comment]
What if the submit isn't successful? I don't think this is a good solution

**Comment by splendido** [comment]
the hook is executed after the submission process completes and in case of errors you get them as the first argument.
Thath's why the first line of the example is

```javascript
  if (!error) {
    // ...
  }
```

**Comment by elie222** [comment]
Ah. Slightly confusing name in that case. Thanks!

Is it also possible to distinguish between sign up and sign in? I assume
this is easy to get around anyway

**Comment by splendido** [comment]
Have you looked at the link I posted?

> You can use the [onsubmithook](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#onsubmithook) I guess.
