### ISSUE TITLE
No link from forgot password to login

### ISSUE THREAD

**Issue by 57even** [meteor-useraccounts/core#469]
Why is there no link from the "forgot password" page to the login page? It can happen that the user suddenly remembers his/her password and will log in instead of reset their password.

Isn't it bad UI to deadlock the user.

**Comment by sferoze** [comment]
I have been looking for an option to add a back to login link from the forgot password page! How can I do this. I was going to edit the template but I can' t even find the forgot password template. 

Please update so we can show back to login from the forgot password page!

**Comment by splendido** [comment]
The choice was to prevent having too much stuff at the same time within the form...
It seemd more logical to go back ti sign-up and then, possibly back again to sign-in.

Feel free to modify [this line](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_form.js#L52) by overriding the template helper like this:

```javascript
AccountsTemplates.atFormHelpers['showSignInLink'] = function(next_state){
  if (AccountsTemplates.options.hideSignInLink)
    return false;
  var state = next_state || this.state || AccountsTemplates.getState();
  if (AccountsTemplates.options.forbidClientAccountCreation && state === "forgotPwd")
    return true;
  return (state === "forgotPwd") || (state === "signUp");
}
```

this should get easier and much more straightforward in v2.0 though...
