### ISSUE TITLE
Adding some text to the change password field

### ISSUE THREAD

**Issue by chiester** [meteor-useraccounts/core#470]
How do I add some text to the change password field? I would like to add a paragraph of text above the email input field.

**Comment by splendido** [comment]
I guess the only way is to specify your own template for that field:

```javascript
AccountsTemplates.addField({
  _id: 'password_again',
  // ...
  template: 'myChangePwd',
});
```

...be careful that the `_id` could also be `password` or `current_password`: it depends on which page you'd like to add the text.

You can start from [here](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_input.html#L5-L16) (for example) to define your custom template but I'd say you'll need some condition to show the text only on a certain state...
