### ISSUE TITLE
Reset form errors on render

### ISSUE THREAD

**Issue by gwendall** [meteor-useraccounts/core#471]
It seems form errors / messages persist even after their parent templates get destroyed. For example, if I submit a login form and get "value required" errors for its fields, navigate to another page, then come back to the login form, the errors are still visible. Is there a way to reset the form state whenever templates get rendered?

**Comment by splendido** [comment]
yes, it might happen if you're not using custom routes I guess.
Differently, [this is the code](https://github.com/meteor-useraccounts/core/blob/master/lib/core.js#L755-L757) to be used with IronRouter to clear the internal status.

Let me know if you need more help!
