### ISSUE TITLE
this.clearStatus is not a function/Uncaught TypeError: this.getValue is not a function

### ISSUE THREAD

**Issue by Neobii** [meteor-useraccounts/core#473]
I put the bootstrap accounts ui into famous DOMElement and now there is an error that prevents logging in on mobile.

AT.atInputEvents.focusin input	@	at_input.js:72
(anonymous function)	@	template.js:463
Template._withTemplateInstanceFunc	@	template.js:437
(anonymous function)	@	template.js:462
(anonymous function)	@	view.js:869
Blaze._withCurrentView	@	view.js:523
(anonymous function)	@	view.js:868
(anonymous function)	@	events.js:47
jQuery.event.dispatch	@	jquery.js:4665
elemData.handle	@	jquery.js:4333
jQuery.event.trigger	@	jquery.js:4574
jQuery.event.simulate	@	jquery.js:4901
handler	@	jquery.js:5164

**Comment by Neobii** [comment]
Putting this in package.js fixed the regular form fields  and submit:
```javascript
  api.export([
    'Field',
  ], ['client']);
```

I'm still having issues on the radio buttons.

**Comment by Neobii** [comment]
For the radio buttons, the context of `this` is the data context for the radio button instead of the `Field` object.

**Comment by Neobii** [comment]
This is going to be close to the solution
`(this instanceof Field)?this.clearStatus():console.log(Template.parentData(1));`

**Comment by MartinBucko** [comment]
I have same issue with radio field:

```javasscript
AccountsTemplates.addFields({
		_id: 'gender'
		type: 'radio'
		displayName: 'Gender'
		placeholder: {}
		required: true
		trim: true
		minLength: 4
		maxLength: 6
		required: true
		re: /^male|female$/
		errStr: 'Bad gender format'
		select: [
			{ text: '- Male', value: 'male' }
			{ text: '- Female', value: 'female' }
		]
	});
````

Packages:
```
accounts-facebook           1.0.4  
accounts-google               1.0.4   
accounts-password           1.1.1   
accounts-ui-unstyled         1.1.7  
useraccounts:core            1.12.1
useraccounts:ionic            1.12.1
```
- after upgrading useraccounts:core  i get same errors)
- its happend after select radio button

```
Error: this.clearStatus is not a function
TypeError: this.clearStatus is not a function
    at Object.AT.atInputEvents.focusin input (http://localhost:3000/packages/useraccounts_core.js?1f5377e9e013360a8f3723d49949c072e45c80b5:1696:14)..
```

```
Error: this.getValue is not a function
TypeError: this.getValue is not a function
    at Object.AT.atInputEvents.focusout input (http://localhost:3000/packages/useraccounts_core.js?1f5377e9e013360a8f3723d49949c072e45c80b5:1700:29)
```

**Comment by splendido** [comment]
@MartinBucko why do you have `accounts-ui-unstyled` among your packages?! ;-)

**Comment by splendido** [comment]
@Neobii this is an interesting error... Have you got to a final solution?

...in particular:
* have you understood what is changing the scope for `this`?
* was it only for radio buttons?

**Comment by splendido** [comment]
This might be due to the `each` used to render radio buttons: see [these lines](https://github.com/meteor-useraccounts/materialize/blob/master/lib/at_input.html#L44-L49)
At that point the data context for each radio button is no more the *radio field* object but the object for the current option passed to the field configuration (e.g. `{ text: '- Male', value: 'male' }` in the above example from @MartinBucko ...)

**Comment by splendido** [comment]
...even if with regular boilerplates I'm not getting any error while testing with radio buttons

**Comment by xyx2011** [comment]
has the same issue, using AtFromReact and using prop to control what form to display. on the radio button has the error.

**Comment by ziarno7** [comment]
getting the same errors on radio buttons:

`at_input.js:72 Uncaught TypeError: this.clearStatus is not a function`
`at_input.js:76 Uncaught TypeError: this.getValue is not a function`

does this have any impact on functionality?

**Comment by mehdi-bouhalassa** [comment]
Any updates to this?

**Comment by bp12345** [comment]
I came across this post while searching for a solution to the problem below. Has anyone implemented a solution yet?


**Error**

```
Uncaught TypeError: this.clearStatus is not a function
Uncaught TypeError: this.getValue is not a function
```
    
```
    AccountsTemplates.addFields([
        {
            _id: "roles",
    	    type: "radio",
    	    displayName: "Account type",
    	    required: true,
            class: "userType",
    	    select: [
    	        {
    	        text: "Teacher",
    	        value: "is_teacher",
    	      }, {
    	        text: "Student",
    	        value: "is_student",
    	      }
    	    ],
        },
      ]);
```

**Comment by diegoadolf** [comment]
Same issue here. Basically the same use case as bp12345

**Comment by diegonc** [comment]
Hi, I created pull request #690 which fixes this issue.
It would be great if it could be reviewed and tested more exhaustively.

**Comment by cesarve77** [comment]
+1
