### ISSUE TITLE
Error: Can't set `forbidClientAccountCreation`

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#476]
I just updated an old project from pre meteor 1.0, I went ahead and removed a number of packages and add meteor-useracconuts but I'm getting the following error 

Error: Can't set `forbidClientAccountCreation` more than once
W20150722-14:39:30.165(3)? (STDERR)     at packages/accounts-base/accounts_common.js:95:1

Here are the packages that I have installed noting should create this conflict 

http
jquery
raix:handlebar-helpers@0.1.1
email
matteodem:server-session@0.4.1
chrismbeckett:toastr@0.1.0
amr:parsley.js
iron:router
cmather:handlebars-server
dsyko:hopscotch
jparker:gravatar
gadicohen:sitemaps
natestrauser:connection-banner
percolatestudio:percolatestudio-migrations
ryw:blog
reywood:iron-router-ga
woody:stripe-easy
gadicohen:phantomjs
gentlenode:spiderable-ssl
multiply:iron-router-progress
twbs:bootstrap
momentjs:moment
wylio:mandrill
underscore
underscorestring:underscore.string
percolatestudio:segment.io
meteor-platform
accounts-password
accounts-facebook
accounts-google
useraccounts:bootstrap

**Comment by almogdesign** [comment]
Never find were the issue coming from 

Accounts.config({sendVerificationEmail: true, forbidClientAccountCreation: false});

**Comment by aleksander351** [comment]
Hello, did you solve this problem? Where did you put your configuration code?
