### ISSUE TITLE
disable autofocus for atPwdForm

### ISSUE THREAD

**Issue by donmarcello** [meteor-useraccounts/core#477]
The new autofocus feature is always scrolling to far down on the page, hiding the social login buttons.

Is there a way to disable the autofocus feature?

**Comment by gwendall** [comment]
+1

**Comment by splendido** [comment]
Added an option right now, see [this commit](https://github.com/meteor-useraccounts/core/commit/f64841c3c7db2f4eb14f812c9affaffa30ab7066).

I'm now going to document this new `focusFirstInput` option.
