### ISSUE TITLE
Can I configure a built-in field without removing it and adding it back?

### ISSUE THREAD

**Issue by oblitum** [meteor-useraccounts/core#478]
Following the Guide it seems that to configure the `email` field, for example, I'll have to remove it and add a new one. By doing that I lose the display order I had initially. If I want to keep this order am I forced to remove all built-in fields and add them back in the order I wish? It's seems the only two options from the Guide.

**Comment by splendido** [comment]
You might try to trick the existing object within `AccountsTemplates._fields`:

```javascript
var email = _.filter(AccountsTemplates._fields, function(f) {return f._id == 'email'});
if (email) {
  email.errStr = 'Check the address!';
}
```

but I'm not sure whether to suggest something like this or not ;-)
