### ISSUE TITLE
Accessing the value of custom fields on user sign 

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#482]
I'm running into the following issue, I'm pretty sure I'm just doing something wrong 

https://github.com/meteor-useraccounts/bootstrap/issues/37

**Comment by splendido** [comment]
Could you please explain a little more?

Additional fields are put into the `profile` field of the user object, so you can get them from the `Meteor.users` collection whenever you need them.
If you need to access them on user creation (e.g. to copy them somewhere else or to modify them...), lets have a look at ['Accounts.onCreateUser`](https://docs.meteor.com/#/full/accounts_oncreateuser).

Let me know if you need further help1

**Comment by almogdesign** [comment]
I fotgot to close this but it was an issue on my end I was clearing the option.profile field
