### ISSUE TITLE
Meteor 1.2 support - compatibility break with less package

### ISSUE THREAD

**Issue by jasonxeno** [meteor-useraccounts/core#483]
from https://forums.meteor.com/t/try-out-a-preview-of-batch-build-plugins-and-other-1-2-features/7374

Preview release of Meteor 1.2 is released now.

"We've made one backwards-incompatible change to packages. To include static assets in packages, you now need to explicitly specify {isAsset: true} in your api.addFiles call. This is not necessary for static assets in apps, and doesn't affect published packages, just package sources."

"Because of this change to these packages, we've bumped their major version numbers. Packages that include less files will need to publish a new version using this preview (or an RC) before you can use them."

I'm having this error with the preview release:

```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0-plugins.0_1.
   Constraints on package "less":
   * less@=2.5.0-plugins.0_1 <- top level
   * less@1.0.11 <- useraccounts:bootstrap 1.11.1
   
=> Your application has errors. Waiting for file change.
```

**Comment by splendido** [comment]
I can only suggest to keep a local copy of the package and change the required version for `less` within the `package.js` file.
Unfortunately, releasing also RC version for all the packages would be too much work, and I cannot afford it.

As soon as v1.2 will be out I'll try to update the packages accordingly.

Let me know if you need more help!
Thanks

**Comment by mibcadet** [comment]
So here is the moment, release 1.2 of Meteor. 
How much time you need to update useraccounts to it?

**Comment by splendido** [comment]
@mibcadet, dependencies on the `less` package were already removed a few releases ago...
...the only one still in place (by mistake) is for the `useraccounts:polymer` package.

I'll try to remove it asap...
