### ISSUE TITLE
What is the required data / subscriptions to routes when autopublish is removed?

### ISSUE THREAD

**Issue by steve-ross** [meteor-useraccounts/core#492]
Specifically I can't seem to find any info on how to get the reset password stuff to work when you remove auto publish. 

Any help would be greatly appreciated

**Comment by Tim-W** [comment]
This should work out-of-the-box when you remove autopublish. What issues are you running into?

To get reset password to work, you need to configure a mail server.

**Comment by steve-ross** [comment]
The routes don't load, I get 'did you forget to call this.next()' when I click on the reset link

**Comment by Tim-W** [comment]
That shouldn't be an issue of useraccounts package itself I think... Check your onBeforeAction hooks on your iron routes. I also can't imagine this having anything to do with autopublish, unless maybe the subscriptions are failing?

**Comment by steve-ross** [comment]
I tried removing all of my onbefore actions and i still can't get it to work. What publications are required for the password reset token to work?

**Comment by steve-ross** [comment]
Ok I got it sorted out. There was indeed another file with a before action which was the problem.

However if someone does want to know how to configure the routes with iron router when you have an app that requires a user for every route you have to configure reset password like this:

```
AccountsTemplates.configureRoute('resetPwd', {
  waitOn: function(){
    return Meteor.subscribe('enrolledUser',this.params.paramToken);
  },
  data: function(){
    if(Meteor.userId())  Router.go('root');
    else return Meteor.users.findOne();
  }
});

```

And your enrolledUser publication:

```
Meteor.publish('enrolledUser', function(token) {
  check(token, Match.Any);
  return Meteor.users.find({"services.password.reset.token": token}, {fields: {_id: 1}});
});
```

**Comment by splendido** [comment]
I'm pretty sure you don't need anything like that to get your reset password route to work.
It's just the official `Accounts` API that lets you veryfy tokens
Lets try with the [bootstrap boilerplate](https://github.com/meteor-useraccounts/boilerplates/tree/master/bootstrap) (after `autopublish` removal...) which was updated to use the lates versions of useraccounts packages...
