### ISSUE TITLE
Mask a signUp form text input

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [meteor-useraccounts/core#493]
Hello, im using this to create a mask on my input field, on signUp form:

var loadMask = function(){
	var state = AccountsTemplates.getState();
	console.log(state);
	if (state=='signUp'){
		$('#at-field-birthday').mask('00/00/0000');
		$('#at-field-cellphone').mask('(00) 0000-0000');  
	}
}

Template.atForm.hooks({
  rendered: function () {
    Deps.autorun(loadMask);
  }
});

But it does not work , i think it's because loadMask is called before the DOM is ready...
How can I solve this ?

**Comment by Tim-W** [comment]
Have you tried using the Template.atForm.onRendered() callback? That should be triggered when the DOM is ready for the accountsTemplates form.

**Comment by juliomac** [comment]
Hi @rafaelcorreiapoli , Did you solve it?
