### ISSUE TITLE
Feature Design: Support for guest/anonymous accounts

### ISSUE THREAD

**Issue by brettle** [meteor-useraccounts/core#499]
I know that @splendido is working on support for guest accounts for 2.0, but I was wondering if a PR that adds such support would be considered. My thinking is to add a `signedInUserId` configuration option whose value is a function that returns the `_id` of the user who is currently "signed in". To support anonymous/guest accounts, this could return null for such users. The core code would be changed to use `signedInUserId()` is places where it uses `Meteor.userId()` or `Meteor.user()` to determine whether the current user is signed in.

Does this make sense? If so, what should the default be for `signedInUserId`? A couple options:

Option 1:
```javascript
function () { return Meteor.userId(); }
```

Options 2:
```javascript
function () {
  var user = Meteor.user();
  if (! user) {
    return null;
  }
  // If the user has a username, a profile.name, or at least one email address,
  // then they aren't anonymous, so return them.
  if (typeof(user.username) === 'string'
      || user.profile && typeof(user.profile.name) === 'string'
      || (user.emails && user.emails.length > 0
          && typeof(user.emails[0].address) === 'string')) {
    return user._id;
  }
  // The user is anonymous, so return null
  return null;
}
```
I could live with either, but would prefer Option 2 because it would mean [my accounts-anonymous package](https://github.com/brettle/meteor-accounts-anonymous) would work without needing to override the default.

Thoughts?

**Comment by splendido** [comment]
See #340.

The thing is I'd like to concentrate on providing a good and stable base for v2.0 on which build amazing stuff later on, guest users support included.
If rather I'll have to follow issues and PRs I seriously doubt I'll ever have time to write code.

Actually adding flawless guest users support is much more complicated than what you describe above and since it might open quite big security issues I'd like to consider it with the due concentration.

I hope this makes sense!

**Comment by brettle** [comment]
I totally understand. I know how hard it can be to find time to do both support and new development.

FYI, I've worked around the lack of support for anonymous accounts in the current version by releasing [brettle:accounts-anonymous-ui](/brettle/meteor-accounts-anonymous-ui). It monkey patches the useraccounts suite to treat anonymous users as logged out. For more information and a demo, see http://brettle-accounts-demo.meteor.com.

**Comment by splendido** [comment]
Ok, I'll have a look at it when I'll come to this again.

Tnx!
