### ISSUE TITLE
How to forbidden some reserved word to registered as username?

### ISSUE THREAD

**Issue by yokas** [meteor-useraccounts/core#509]
I have a route  `/:username`, so I would like to forbidden usernames like `login`, `loggout`

**Comment by splendido** [comment]
Lets have a look at ['Accounts.onCreateUser`](https://docs.meteor.com/#/full/accounts_oncreateuser).
That is the place where to throw an exception in case the selected username is not *valid* for you.

You might also think to tell the user the selected name is not going to be accepted (so, before it presses the register button) by setting up some custom validation rule for the username field. Lets have a look at [form-fields-configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration) and [custom-validation](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#custom-validation)
