### ISSUE TITLE
I would like to translate

### ISSUE THREAD

**Issue by juliankim** [meteor-useraccounts/core#512]
I would like to volunteer to translate this app into Korean. :) (I18n)

**Comment by splendido** [comment]
Hi @juliankim,
at the moment we're relying on [softwarerero:accounts-t9n](https://github.com/softwarerero/meteor-accounts-t9n) for the i18n.

Feel free to contribute there!


...in a near future we'll have to revise the i18n support for UserAccounts and we'll count on you for the Korean part ;-)

**Comment by juliankim** [comment]
I'm more than willing to contribute to translation :D just tell me when and how. Thanks!

**Comment by juliankim** [comment]
@splendido 
Alright, I translated for meteor-accounts-t9n and I believe it is added now. Is there anything more that I can do? :)

**Comment by splendido** [comment]
not for now, but I'll be back as soon as I'll have some i18n file you can work on! :)
Tnx!

**Comment by juliankim** [comment]
@splendido I'm still waiting haha

**Comment by splendido** [comment]
I haven't forgotten about you!
But I'm still a little behind...

If you write me an email I'll invite you to the LingoHub project I'm trying to set up to start playing on it ;-)

**Comment by splendido** [comment]
@juliankim: I'd like to invite you on LingoHub to contribute to the v2.0 i18n.
How can I get your email address?

**Comment by juliankim** [comment]
@splendido cpn.julain@gmail.com :)

**Comment by juliankim** [comment]
Sorry! Found a typo cpn.julian.com@gmail.com @splendido

**Comment by splendido** [comment]
perhaps another typo? ;-)

**Comment by splendido** [comment]
is cpnjulian@gmail.com fine?

**Comment by juliankim** [comment]
It's cpn.julian@gmail.com :)

**Comment by splendido** [comment]
Invite sent!
thanks :-)
