### ISSUE TITLE
Form loads with Must be logged in error by default

### ISSUE THREAD

**Issue by philipobrien** [meteor-useraccounts/core#516]
Whenever I go to the sign in page of my app I get the error shown before doing anything

![image](https://cloud.githubusercontent.com/assets/1763813/9359734/796c0a44-468a-11e5-9237-ddbf369840c2.png)

I configure the accounts as follows

```js
AccountsTemplates.configure({
    confirmPassword: true,
    homeRoutePath: '/'
});

AccountsTemplates.configureRoute('signIn', {
    path: '/signin',
    template: 'atForm',
    layoutTemplate: 'account',
    redirect: '/'
});

AccountsTemplates.configureRoute('signUp', {
    path: '/signup',
    template: 'atForm',
    layoutTemplate: 'account',
    redirect: '/'
});


AccountsTemplates.configureRoute('ensureSignedIn', {
    template: 'atForm',
    layoutTemplate: 'account'
});
```

I think it is because I use the `ensureSignedIn` plugin and don't have an individual `signin` route

```js
Router.plugin('ensureSignedIn');

Router.configure({
    layoutTemplate: 'layout',
    notFoundTemplate: 'notFound',
    loadingTemplate: 'loading'
});

Router.route('/', {
    name: 'dashboard'
});
```

What is the best way to avoid this?

**Comment by splendido** [comment]
The problem is probably the `ensureSignedIn` plugin being applied to every routes, the ones configured for UserAccounts included. This is due to the call

```javascript
Router.plugin('ensureSignedIn');
```

which should be something like 

```javascript
Router.plugin('ensureSignedIn', {
  except: _.pluck(AccountsTemplates.routes, 'name').concat(['home'])
});
```

also explained [here](https://github.com/meteor-useraccounts/core/issues/406#issuecomment-106882540)

**Comment by splendido** [comment]
This is also well explained in the [content protection section](https://github.com/meteor-useraccounts/iron-routing/blob/master/README.md#content-protection) of the [useraccounts:iron-routing](https://github.com/meteor-useraccounts/iron-routing) package...
