### ISSUE TITLE
[iron-routing] routing error upon startup

### ISSUE THREAD

**Issue by chiester** [meteor-useraccounts/core#517]
I have iron:router installed. I just updated useraccounts to 1.12.2 and now when I start up my server, I get this error: 

" You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!"

Why?

**Comment by chiester** [comment]
I added useraccounts:iron-routing (a very confusing name, btw). 

Here is the error I get now upon startup: 

"Error: changePwd route configured but enablePasswordChange set to false!" 

Here is the line from my at_config.js: 

enablePasswordChange: true,

**Comment by splendido** [comment]
Routes should now be configured AFTER normal options since they're now defined on the fly...

I think I should add another note to the[documentation for the useraccounts:iron-routing package](https://github.com/meteor-useraccounts/iron-routing).

**Comment by splendido** [comment]
Actually this is the same as #514

**Comment by splendido** [comment]
see https://github.com/meteor-useraccounts/iron-routing/commit/ab184ca1c056e62a3d75c364f6387e75a158da60
