### ISSUE TITLE
Trying to run this locally getting error

### ISSUE THREAD

**Issue by Aggr0vatE** [meteor-useraccounts/core#521]
Hi, I am trying to run this code locally on localhost, but I get the following error:

Error: Can't set `forbidClientAccountCreation` more than once
    at packages/accounts-base/accounts_common.js:95:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Object.Accounts.config (packages/accounts-base/accounts_common.js:92:1)
    at app\server\config.js:1:45
    at app\server\config.js:7:3
    at C:\Users\steph_000\Documents\My Projects\testbasic\.meteor\local\build\programs\server\boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\steph_000\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\steph_000\Documents\My Projects\testbasic\.meteor\local\build\programs\server\boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.

I am currently using accounts-ui-bootstrap-3 for my login package, but I have tried to switch to the plain accounts-ui and I still get the same error. Also, I have removed accounts-base.

**Comment by splendido** [comment]
This package has nothing to do with `accounts-ui` and the use of both at the same time is not supported nor incouraged.

UserAccounts packages set `forbidClientAccountCreation` to true by default for security reasons.
Lets try to remove all packages related to `accounts-ui` and the problem should go away ;-)

**Comment by Aggr0vatE** [comment]
Ok, so I removed everything that was related to accounts-ui and some unneeded packages but I still get the error. 

These are the following packages I have left in my project:
houston:admin
insecure
iron:router
jquery
meteor-platform
twbs:bootstrap
useraccounts:core

**Comment by Aggr0vatE** [comment]
OK so now I added this code to both/lib/config/at_config.js

AccountsTemplates.configure({
    // Behavior
    confirmPassword: true,
    enablePasswordChange: true,
    forbidClientAccountCreation: false,
    overrideLoginErrors: true,
    sendVerificationEmail: false,
    lowercaseUsername: false,
    focusFirstInput: true,

    // Appearance
    showAddRemoveServices: false,
    showForgotPasswordLink: false,
    showLabels: true,
    showPlaceholders: true,
    showResendVerificationEmailLink: false,

    // Client-side Validation
    continuousValidation: false,
    negativeFeedback: false,
    negativeValidation: true,
    positiveValidation: true,
    positiveFeedback: true,
    showValidating: true,

    // Privacy Policy and Terms of Use
    privacyUrl: 'privacy',
    termsUrl: 'terms-of-use',

    // Redirects
    homeRoutePath: '/home',
    redirectTimeout: 4000,

    // Hooks
    onLogoutHook: myLogoutFunc,
    onSubmitHook: mySubmitFunc,
    preSignUpHook: myPreSubmitFunc,

    // Texts
    texts: {
      button: {
          signUp: "Register Now!"
      },
      socialSignUp: "Register",
      socialIcons: {
          "meteor-developer": "fa fa-rocket"
      },
      title: {
          forgotPwd: "Recover Your Password"
      },
    },
});

But now I get the following error:

ReferenceError: myLogoutFunc is not defined
    at app\both\lib\config\at_config.js:35:19
    at app\both\lib\config\at_config.js:54:3
    at C:\Users\steph_000\Documents\My Projects\testbasic\.meteor\local\build\programs\server\boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\steph_000\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\steph_000\Documents\My Projects\testbasic\.meteor\local\build\programs\server\boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by splendido** [comment]
You're getting this error because of the section *Hooks* which is trying to set some callbacks you don't have.

Actually you could comment the whole call to `AccountsTemplates.configure` and defaults would apply.
You could then start to set what you want to get different from what provided as default.

Let me know!

**Comment by Aggr0vatE** [comment]
I figured it out

I had this code in server/config.js:

Accounts.config({sendVerificationEmail: true, forbidClientAccountCreation: false}); 

Meteor.startup(function () {
  process.env.MAIL_URL = 'imap.1and1.com';
});

I just had to take out forbidClientAccountCreation there and it worked!

*picard facepalm*

**Comment by Aggr0vatE** [comment]
Now, just one last question, what is the code to add the sign in button? Because I added {{>atForm}} but there seemed to be no button.

**Comment by Aggr0vatE** [comment]
ok so atform puts the whole form in, so do i just have to link the button to atform?

**Comment by splendido** [comment]
ok, great!

if you have some sort of navbar you can put it `{{> atNavButton}}` and configure at least the `signIn` route with:

```javascript
AccountsTemplates.configureRoute('signIn')
```

(but this needs some routing package, like e.g. `useraccounts:iron-routing`)

Otherwise simply create your own button responding to the click with a `Router.go` to the page where you have set up `atForm`...

**Comment by Aggr0vatE** [comment]
ok, so I will install useraccounts iron routing. I am pretty sure they are the same as I already have iron:router. :D

**Comment by Aggr0vatE** [comment]
welp, looks like my navbar is blocking some of the log in. Can I add some sort of <br> in there so that the login form is not as high up?

**Comment by Aggr0vatE** [comment]
ok so I figured that out by adding some simple css code, but is there a way to add more text boxes to the registration page?

**Comment by splendido** [comment]
Yes! Just read through the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md), especially the section about [form fields configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration)
