### ISSUE TITLE
useraccounts:iron-routing Singup not working

### ISSUE THREAD

**Issue by armandomendivil** [meteor-useraccounts/core#524]
I want to create a new register but show me an error: signups forbidden

Template.register.events({
    'submit .register-form': function (event) {
        
        event.preventDefault();

        var email = event.target.email.value;
        var password = event.target.password.value;

        var user = {'email':email,password:password};
        Accounts.createUser(user,function(err){
            if(!err) {
                toastr.success("User created", "Success!"); 
                Router.go('/');
            } else {
                console.log(err.reason);
                toastr.error(err.reason, "Error")
            }
        });
    }
});

**Comment by heliostatic** [comment]
Just ran into the same issue. Haven't gotten to the bottom of it yet.

**Comment by splendido** [comment]
Hi there,
isn't the sign up form provided with useracconuts working for you?
Lets have a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) to get started and possibly at [bootstrap-iron-router](https://github.com/meteor-useraccounts/boilerplates/tree/master/bootstrap-iron-router) if you're interested in IR.

There should be no need to rewrite your own logic, this is what the useraccounts packages should do for you...

**Comment by splendido** [comment]
UserAccount packages create new user with a custom server-side-only method and client side account creation is disabled on purpose (see [these lines](https://github.com/meteor-useraccounts/core/blob/ed52d006774c4a4726d108723ad32d004d1433ef/lib/server.js#L169-L179)): that's a choice about security and there's no way around this...

**Comment by Twisterking** [comment]
So what do I do if I want to use your package but also want to create a user on the client at some point using the standard `Accounts.createUser()` function? I want to call it on the client as calling it on the server and wrapping it in a standard Meteor method would imply that the password is transferred in plain text when calling the method - which obviously is not ideal! So what's the best way to do this?!
