### ISSUE TITLE
Suggestion: Limit register and login attempts to protect against brute force attacks

### ISSUE THREAD

**Issue by cosio55** [meteor-useraccounts/core#526]
Hi, I think it would be amazing to add a functionality to protect the apps of brute force attacks by limititing the number of attempts to register users and logins, maybe adding plugins like eluck:accounts-lockout or zeroasterisk:throttle-accounts should do the trick, but I think this would be a great feature to implement on the core.

**Comment by splendido** [comment]
I agree!

But I see it better done with plugin packages for version 2.0
Thoughts?

**Comment by splendido** [comment]
This is now implemented within Meteor core with [DDPRateLimiter](https://docs.meteor.com/#/full/ddpratelimiter)
