### ISSUE TITLE
Override CSS class for atNavButton

### ISSUE THREAD

**Issue by taxigy** [meteor-useraccounts/core#532]
I use `atNavButton` in a custom designed navigation sidebar, and the button's current appearance doesn't fit. I understand it's possible to override appearance directly in CSS, but I'd love to define custom class for this button, just like

```html
{{> atNavButton class="btn btn-block my-custom-super-nav-button-class"}}
```

Does this feature already exist or has it been scheduled?

**Comment by splendido** [comment]
Hi @taxigy,
the configuration options to easily change classes for templates' elements will enter v2.0 but for now you can simply override the template using [aldeed:template-extension](https://atmospherejs.com/aldeed/template-extension).

[This](https://github.com/meteor-useraccounts/core/issues/366#issuecomment-96380408) is the latest comment about this, but you can also have a look at #212.
