### ISSUE TITLE
Cant Route to Singup or Login Page

### ISSUE THREAD

**Issue by sferoze** [meteor-useraccounts/core#533]
I have no idea what is preventing me from navigation to the login or signup page when I am already logged in. 

Going to the login page is not important but when logged in the user should still be able to go to the sign up page. 

I have no route filters or anything but I cannot go to the sign up page when logged in. 

It just prevents me or routes to the dashboard. Why is this happening? How can I turn this off

**Comment by sferoze** [comment]
What I really want to do, is be able to visit the signup page if your already logged in, and allow the user to signup for another account which would automatically log the current user out and then signin with the new account

**Comment by splendido** [comment]
@sferoze [these lines](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/core.js#L182-L194) are those purposely used to redirect logged in users away from the sign in and sign up pages (as well as others...)

What you're asking is a little weird to me: I usually don't see sign up links while I'm logged into very popular web sites...

What you could do is add a `onBeforeAction` hook to your sign up route to get the user automatically logged out, but I'm not sure your hook will run before the one I'm linking above.
