### ISSUE TITLE
Please update dependency to softwarerero:accounts-t9n to latest versions again

### ISSUE THREAD

**Issue by fabyeah** [meteor-useraccounts/core#534]
Since version 1.1.0 it is possible to send only  selected languages to the client instead of all translations, which reduces bandwidth:
https://github.com/softwarerero/meteor-accounts-t9n/tree/4d143e856e8e301018e05ff4c1d6eeb6c3ed129a#send-only-some-language-files-to-the-client-new-in-version-110

**Comment by splendido** [comment]
See aa87c75cd23c4d8fb70ff8b97bcde602add8e069

tnx!

**Comment by fabyeah** [comment]
Great! Thank you @splendido
