### ISSUE TITLE
Login redirect based on user role

### ISSUE THREAD

**Issue by shactdeveloper** [meteor-useraccounts/core#535]
Hello, it's not an issue but a question.
How can I set diferent redirects pages when user logs in according to user role?

**Comment by splendido** [comment]
Lets have a look at the [onSubmitHook](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#onsubmithook)

You could do something like:

```javascript
var mySubmitFunc = function(error, state){
  if (!error) {
    if (state === "signIn" || state === "signUp") {
      // Successfully logged in
      var userId = meteor.userId();
      if (Roles.userIsInRole(userId, ['view-secrets','admin'])) {
        Router.go('/my-secret-stuff');
      }
      // ...
    }
  }
};

AccountsTemplates.configure({
    onSubmitHook: mySubmitFunc
});
```

**Comment by shactdeveloper** [comment]
Perfect!! Thanks man

**Comment by splendido** [comment]
I've just realized there's another option: see, e.g., the [Routes](https://github.com/meteor-useraccounts/iron-routing#routes) section for [useraccounts:iron-routing](https://github.com/meteor-useraccounts/iron-routing) and this [post on SO](http://stackoverflow.com/questions/29171033/meteor-useraccounts-and-alanning-meteor-roles-check-role-on-sign-in/29864010#29864010)

Using the `redirect` parameter might be clearer...

**Comment by shactdeveloper** [comment]
Nice, I will have a try!
