### ISSUE TITLE
postSignUpHook Feature

### ISSUE THREAD

**Issue by shwaydogg** [meteor-useraccounts/core#536]
I propose adding a `postSignUpHook` that would run server side only or a `postSignUpHookServer` and `postSignUpHookClient`.

This would address issues that came up in these SO questions:

http://stackoverflow.com/questions/30482814/meteor-how-to-assign-different-roles-to-users-during-sign-up-process/32468020#32468020
http://stackoverflow.com/questions/12984637/is-there-a-post-createuser-hook-in-meteor-when-using-accounts-ui-package/13483188#comment52798127_13483188

^see my comments as shwaydogg

I'll write and make a pull request, but following instructions to bat around here first.

Cheers!

**Comment by splendido** [comment]
What about calling it `onCreateUser`? Do you think this could make things clearer (recalling the aim for [Accounts.onCreateUser](https://docs.meteor.com/#/full/accounts_oncreateuser) or could it be confusing?

In any case, I agree it makes sense to have another hook just after user creation.
The place where tu put it should be around [here](https://github.com/meteor-useraccounts/core/blob/master/lib/server_methods.js#L114)

**Comment by shwaydogg** [comment]
Yep, I think it would be misleading.  90% of the motivation for this addition is because Meteor's Accounts.onCreateUser is aptly named **on** not **post** because the new use has NOT been added to the user collection yet.  This is what caused the issues in the SO questions.

I'd also say best to stay with the linguistics of the current hook names such as `preSignUpHook`: clear and precise!

Sound good?

Also, @splendido, thanks for the headsup on the where it should go in the code!  I'd found the same spot before asking, had to make sure it wasn't going to be a crazy edit before saying I'd do it ;)

**Comment by splendido** [comment]
:+1:

**Comment by nalexeric** [comment]
@shwaydogg any news on this?

**Comment by shwaydogg** [comment]
@nalexeric & @splendido, I made pull request #586

**Comment by splendido** [comment]
merged, tnx!
