### ISSUE TITLE
How to translate or override filed error message?

### ISSUE THREAD

**Issue by zhaoyao91** [meteor-useraccounts/core#541]
I am Chinese, I want to translate the filed error messages to Chinese, such as 'Invalid email‘， ’Minimum required length: 6‘， ’Required Field‘。

By setting errStr, I can only override message as 'Invalid email', but for others, I don't know the right way. could you help me?

**Comment by derwaldgeist** [comment]
Have you seen the ```softwarerero:accounts-t9n``` package? It already contains Chinese translations for the standard texts. But for custom texts, I am also struggling with i18n, which is why I came here.

**Comment by zhaoyao91** [comment]
@derwaldgeist yes I have tried the t9n, but what I show here were not translated yet, and some translations may not satisfy our need.

**Comment by derwaldgeist** [comment]
Ok, just wanted to make sure you did not miss this package.

**Comment by splendido** [comment]
@zhaoyao91 lets have a look at #418 and #200.

Btw, `Invalid email` should be already translated: see [this line](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/zh_hk.coffee#L94), [this line](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/zh_tw.coffee#L94), and [this line](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/zh_cn.coffee#L94)

**Comment by zhaoyao91** [comment]
@splendido please see what I post on  [#418](https://github.com/meteor-useraccounts/core/issues/418)

**Comment by lytstephen** [comment]
Hi, I'm having the same trouble still now, and I'm not getting a working solutions from the suggested methods. Anyone know how to go about this?
