### ISSUE TITLE
need link to github on example page

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/core#542]
when i search for useraccounts this page always come up first for me
http://useraccounts-bootstrap.meteor.com/

please add a link to the repo! Would be helpful to me and also helpful to people who land on that page and dunno where to find the repo.

Cheers,

**Comment by splendido** [comment]
That's a good idea!
I'll try to add something on the navbar for the next deploy...

Tnx!

**Comment by splendido** [comment]
this should be now solved with the addition of the content on the landing page:

> Hello Meteorites!
> If you'd like to discover more about useraccounts packages for [Meteor](https://www.meteor.com/), you can have a [look at them on Atmosphere](https://atmospherejs.com/useraccounts) or at the [meteor-useraccounts GitHub organization](https://github.com/meteor-useraccounts/)
> Head instead to the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md) to read a bit of documentation, or lets have a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) for a quick start!

Thank you for the hint!
