### ISSUE TITLE
Is there a way to use a date input?

### ISSUE THREAD

**Issue by cosio55** [meteor-useraccounts/core#545]
Hi, I allready looked in your documentation and saw that the supported current formats for inputs are: password, email, text, tel, url, checkbox, select, radio, hidden, I just wanted to know if there was a way to add a date input as I need to ask my users for their birthday. Thanks in advance!

**Comment by PhilippSpo** [comment]
You actually can do it even if there is no type `date` currently supported.
First add a custom field to the signIn template (the trick is in the `template` property):
```js
AccountsTemplates.addField({
    _id: "dateOfBirth",
    type: "text",
    template: "dateTemplate",
    required: true,
    negativeValidation: false,
    negativeFeedback: true
});
```
Then just define your template and use whatever input field you wish:
```html
<template name="dateTemplate">
  <div class="at-input field">
    <div class="ui">
      <input type="date" id="at-field-{{_id}}" name="at-field-{{_id}}" {{disabled}}>
      <label for="at-field-{{_id}}">
        Date of birth
      </label>
    </div>
  </div>
</template>
```
You might still need to have some styling to do, but this works fine for me for now ;)

**Comment by cosio55** [comment]
Thanks, this helped me a lot!

**Comment by gVolop** [comment]
not a perfect solution.
please, help me solve this,  if u can. -->  https://github.com/meteor-useraccounts/core/issues/613
