### ISSUE TITLE
How to remove a specific service from signin/signup options?

### ISSUE THREAD

**Issue by zylootino** [meteor-useraccounts/core#549]
Hi there,
I am only allowing Google signin, but another package I am using (yogiben:pretty-emails) has a dependency on accounts-password. So the useraccounts forms show the email/password input in the options. How can I hide them?
Thanks a lot :)

**Comment by MehdiSolati** [comment]
bump

**Comment by splendido** [comment]
you can override the atForm template as described [here](https://github.com/meteor-useraccounts/core/issues/300#issuecomment-76585295) removing the part about `pwdForm`.

But this won't prevent users from using the browser's console and register/log-in with the `accounts-password` API!
