### ISSUE TITLE
How to customize for different types of users?

### ISSUE THREAD

**Issue by calvinfroedge** [meteor-useraccounts/core#559]
I would like to have something like this:

1) User selects their type: 'Type A', 'Type B'

2) Selecting A or B gives them some of the same sign up form inputs, but also some different ones, including different oauth providers (LinkedIn vs Github)

What would be the preferred way to implement such logic? Would it be a custom template? Or maybe listening to some events on form value changes and modifying the DOM? Looking for some best practices guidance. Thank you!

**Comment by splendido** [comment]
this is something that was already asked and quite a long discussion about this can be read in #358.
More recent issues about this are #377 and #460.

My thinking is that we could solve this by putting a select input for the user type on the registration form and ask for other required fields in a second step.
Something like this (without the selection of the type of user) is already implemented in Telescope where after sign-in/registration (both with password or oauth) you're asked to complete the required fields of your profile page before being able to do anything else...
This should solve also #451 #178 #462

**Comment by calvinfroedge** [comment]
Thank you for the response. I had actually checked all of these issues already, as I spent nearly a day exploring this problem. I am not using IronRouter, so those options are not available to me. As far as customizing the fields, I added some radio fields but received errors. I believe there was another issue about that. I changed to a select field and it worked.

The biggest issue for me, however, is related to the oauth implementation. `Accounts.onCreateUser` and `AT.onSubmitHook` are not sufficient for me. I need more fine-grained control over what options are sent to the server after the OAuth provider finishes, and as `onCreateUser` is client side my only option is to implement a shared session between client and server. I already did this in Meteor, but I have done this in the past in my own project (https://github.com/calvinfroedge/legolas) and found it to be buggy, as it is dependent on persistent state.

After reviewing the Meteor code, I have found that I can pass a callback to each `loginWithProvider` method. If I wrap this in a `Meteor.call` from the client, I have access to the user created by the OAuth process and can make modifications to the user profile (such as adding a login type) as soon as the OAuth finishes.

I think `meteor-useraccounts` is a great project, but for my needs, I would prefer having precise control over the flow. My suggestion (and I realize it is always more helpful when people send pull requests, rather than just complain) is to create a hook for every event possible. 

If it is possible to do something like I have mentioned while still using `meteor-useraccounts`, without pointing to somewhat unrelated issues, I would love to hear it, and am happy to pay for your time. Thank you!

**Comment by splendido** [comment]
So the user type selection should be something independent from the login method right?

In this case it doesn't make that much sense to show additional fields within the password login form since oauth registration will follow another flow.
And would 3rd parties services subsets be disjoint for different user types?

**Comment by calvinfroedge** [comment]
The real problem here is just that as a user I do not have complete control over the events which happen. I will post the solution that I make later today, and if it is possible to do this with meteor-useraccounts, please let me know.

**Comment by splendido** [comment]
This might somehow be linked to #558

**Comment by calvinfroedge** [comment]
@splendido I did eventually come up with a way to resolve this. I'm not sure if this will work for meteor-useraccounts or not, but it certainly solves my issue in a bug-free and scalable way. https://github.com/meteor/meteor/issues/5456

**Comment by splendido** [comment]
I'm reasoning about a more comrehensive solution for v2.0 (not committed on GH yet) which should solve the problem about having different input fields for different user types.
Specifically it'll be a plugin package probably named `useraccounts:user-types`.
