### ISSUE TITLE
how to hide social buttons when I have some services installed

### ISSUE THREAD

**Issue by zhaoyao91** [meteor-useraccounts/core#567]
I have installed accounts-weibo for some reason and I don't what the user to signup with it. but it show up automatically. how to hide it?

**Comment by splendido** [comment]
First of all, please note that even in case you're successfully going to hide the button, any user will still be able to open un the console of her browser and run `Meteor.loginWithWeibo(...)`.

only configured services should be shown, so you shouldn't see the weibo button unless you have it properly configured into the db or you also have `accounts-ui` installed (not suggested...): see [these lines](https://github.com/meteor-useraccounts/core/blob/4f2d4067e7e4ee6146de9692ec4699c9580068e7/lib/core.js#L560-L569)

In case, you could override the template helper used to get the list of services and filter weibo out.
See [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_oauth.js)

```javascript
Template.atOauth.helpers({
    oauthService: function() {
        var services = AccountsTemplates.oauthServices();
        return _.filter(services, function(service) {
          return service._id !== 'weibo';
        });
    },
});

**Comment by guilhermedecampo** [comment]
A good idea also to remove the `showServicesSeparator`

```
import { Template } from 'meteor/templating'

Template.atForm.helpers({
  showOauthServices: () => false,
  showServicesSeparator: () => false,
})
```
