### ISSUE TITLE
AccountsTemplates.addFields using dynamic values for select

### ISSUE THREAD

**Issue by Kunal1985** [meteor-useraccounts/core#569]
Hi,

I am trying to assign dynamic values to select option as below:
AccountsTemplates.addFields([
	{
		_id: 'customField',
		type: 'select',
		displayName: 'Custom Field',
		select: custFunct(),
	}
]);

custFunct() is a function i have defined as below
var custFunct = function() {
    var jsonArr = [];
	var jsonObj = {};
	jsonObj.text = "Cust1";
	jsonObj.value = "cust1";
	jsonArr.push(jsonObj);
	
	jsonObj = {};
	jsonObj.text = "Cust2";
	jsonObj.value = "cust2";
	jsonArr.push(jsonObj);
	
	return jsonArr;
};

Post this I am able to see the dropdown getting populated with Cust1 and Cust2 correctly

Now, i have to get these values from one of my collection which is not working as below
var custFunct = function() {
	return CustCollection.find().fetch(); // this line gives error that CustCollection is not defined. 
};

Kindly suggest how to proceed.

**Comment by cunneen** [comment]
+1. I can't figure out any way to get reactive data sources in a SELECT using the default templates. It won't work in a Tracker.autorun() block.

**Comment by splendido** [comment]
Have you already found out about #356 and #328?

**Comment by cunneen** [comment]
No, I searched for but didn't find them. Thanks!
For the record, my solution is the same as your last comment on #328. But it would be nice for the default templates to be reactive.

**Comment by cunneen** [comment]
@splendido any idea about the best way to validate dynamic selects as per your suggestion in #328 ?

**Comment by splendido** [comment]
I think a [custom valudation function](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#custom-validation) could be used to pick up values from the collection you're using and check one of those was actually chosen.

**Comment by cunneen** [comment]
custom validation functions aren't getting run when I use a custom template.

**Comment by splendido** [comment]
this is weird...
how are you defining your custom template?
do you have a public reproduction for the problem?

**Comment by cunneen** [comment]
This link should illustrate the problem. How can I hook the select's validation function to its onchange event? 

http://meteorpad.com/pad/t5LdBwn6YiXjCFwko/UserAccounts%20Validation

**Comment by splendido** [comment]
@cunneen, sorry for the late reply.

I had a look at the problem and it's a mixture of things:
1. validation events for selects never fired so far! My bad :-(
2. to actually get validation performed you should keep the correct naming for fields' id: `at-field-school` is what you need (`at-field-<field_name>` is what is used for every template, lets have a look [here](https://github.com/meteor-useraccounts/unstyled/blob/master/lib/at_input.html#L32) for example)
``` html
<template name="selectSchool">
  <label for="at-field-school">{{displayName}}</label>
  <select id="at-field-{{_id}}" name="at-field-{{_id}}">
    <option value="select">Please select</option>
    <option value="one">School One</option>
    <option value="two">School Two</option>
  </select>
</template>
```

then you also need to enable validation setting to `true` either _negativeValidation_ or _positiveValidation_ (or both, see the Guide) when you configure the field:

```javascript
AccountsTemplates.addFields([
	/* ... */
	{
		_id: 'school', //Add a school select to the form
		type: 'select',
		displayName: 'Select a school',
		select: [],
		template: "selectSchool",
		errStr: 'Select a School',
		func: function(value){
			if (Meteor.isClient) {
					console.log("Validating school..." + value);
					this.setSuccess();
					// or this.setError(userExists);
					this.setValidating(false);

					return;
			}
		},
		negativeValidation: true,
	},
	/* ... */
]);
```

hopefully this should be enough to solve your issue!
