### ISSUE TITLE
Meteor.loginWithFacebook() results in white screen on Android

### ISSUE THREAD

**Issue by LucNaterop** [meteor-useraccounts/core#577]
I added the accounts-facebook package to the app and provided the App ID and App Secret from the facebook app. Now, logging in via facebook works fine on ios and browser. But on Android, I get a white screen of death. There are a few notes [here](https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients#popup-versus-redirect-flow) about `window.close` not being supported on mobile platforms, so I chose the redirect flow. Still, I get the white screen of death. Has anybody been able to get facebook login working on Android?

**Comment by splendido** [comment]
@LucNaterop I think this is more a question for the forums or, eventually, an issue to be opened on the official meteor repository.

What the `useraccounts:core` package does is simply calling `Meteor.loginWithFacebook()` method on button click, nothing else.

I'm sorry I cannot be of any help.
