### ISSUE TITLE
Customize verification/password reset/etc email

### ISSUE THREAD

**Issue by marktomm** [meteor-useraccounts/core#581]
Is there a way to use a custom template for emails? Or change/translate the title/body text somehow?

**Comment by marktomm** [comment]
meteor-useraccounts uses Meteor Accounts for verification/reset email. (http://docs.meteor.com/#/full/accounts_sendresetpasswordemail)

rtfm material sry.

**Comment by chrise86** [comment]
While it's possible to alter the text following the Meteor guides, is there any way of changing the full HTML template?

**Comment by soitech** [comment]
Thanks, I just kept digging through the docs for meteor/useraccounts-core and kept missing this info in the official documentation.
