### ISSUE TITLE
Having an extra space before the suffix

### ISSUE THREAD

**Issue by mitar** [meteor-useraccounts/core#583]
I would like to have a dot at the end of the "If you already have an account" link, but when I configure`signInLink_suff` to`'.'`, I get:

```
If you already have an account sign in .
```

**Comment by splendido** [comment]
I'd say it would be a bigger problem if with:

```javascript
AccountsTemplates.configure({
  texts: {
    signInLink_pre: "Go to",
    signInLink_link: "signin",
    signInLink_suff: "page if you already have an account.",
  },
});
```

what you get would be: "Go to sign inpage if you already have an account."
For this reason I'm not keen to remove the _extra _ space between the two parts.

My suggestion is to override the `atSigninLink` template to add the final dot while getting rid of the suffix:

```shell
meteor add aldeed:template-extension
```

```html
<template name="myAtSigninLink">
  <div class="at-signin-link">
    <p>
      {{preText}}
      <a href="{{signInLink}}" id="at-signIn" class="at-link at-signin {{disabled}}">{{linkText}}</a>.
    </p>
  </div>
</template>
```

```javascript
Template.myAtSigninLink.replaces("atSigninLink");
```

**Comment by mitar** [comment]
Isn't it easier then to do:

```
AccountsTemplates.configure({
  texts: {
    signInLink_pre: "Go to",
    signInLink_link: "signin",
    signInLink_suff: " page if you already have an account.",
  },
});
```

Then you do not have to override any template, you can keep the official stuff around, know that it will get updated, and you can configure it directly from the code?

**Comment by splendido** [comment]
The thing is this will also be a problem when using i18n/t9n keys to get reactive translations.
And I'm not sure whether we could ask people to translate keys being carefully to keep a space at the begin of the string.

Thoughts?

**Comment by mitar** [comment]
Oh, if you are talking about translations then the whole current approach is wrong. Translation strings should be then something like `Go to {{link}} page if you already have an account.` so that translator can move the link around in the string as it fits the language. This prefix/suffix is very bad for translators.

**Comment by mitar** [comment]
So then there should be two strings:
* `signInLink_description: "Go to {{link}} page if you already have an account."`
* `signInLink_linkText: "signin"`

**Comment by mitar** [comment]
I have seen this problem a lot. For example, many assume that there is no space before `:` and then you find template like `{{translatedString 'foo'}}: {{value}}`. But in French language they put space before `:`. So you in fact should move `:` into the string: `{{translatedString 'foo:'}} {{value}}`, but even that is not OK, because some languages would have to move value somewhere else and it is not at the end. So concatenating never ends well.

**Comment by splendido** [comment]
I'm trying to use placeholders for v2.0: see the [en Oauth strings](https://github.com/meteor-useraccounts/i18n/blob/master/i18n/oauth/en.i18n.json) for example.
This way, as you said, translators will be able to move the placeholder wherever needed.

The thing with the link in the middle of a sentence is a bit more complicated to deal with.
I can't get how the "Go to {{link}} page if you already have an account." could solve the problem though...
How would you see it done?

Any hint for a practical solution would be much appreciated ;-)

**Comment by mitar** [comment]
> The thing with the link in the middle of a sentence is a bit more complicated to deal with.

I do not understand? Why is this a problem? You have two strings to translate though, the one which generates the link, and the other which generates text around.

**Comment by splendido** [comment]
Once you have your string(s), how do you _split_ them to (reactively) produce your DOM elements?
How to use them into the template?

Now it's:

```html
{{prefix}} <a href='#'>{{text}}</a> {{suffix}}
```

but how to achieve the same starting from one single string (or two)?

...or what you mean is really keep a placeholder inside the string, look for it and split the text accordingly?

**Comment by mitar** [comment]
I must say that I completely do not get your question. But let me still try to answer. :-)

I would have two strings to translate:

* `signInLink_description: "Go to {{link}} page if you already have an account."`
* `signInLink_linkText: "signin"`

First, the important part is that placeholders should be named, so that you can switch the order around. Again, in some languages the order is changed.

So then you first render the link:

```
var link = '<a href='#'>' + translate(signInLink_linkText) + '</a>';
```

And then:

```
var description = translate(signInLink_description, {link: link});
```

You can even use Blaze rendering inside `translate`, if you want (`Blaze.toHTML`). Or just use your own way to replace placeholders.

More tricky things become when you want to translate counting strings.
