### ISSUE TITLE
Recaptcha validation duration UX

### ISSUE THREAD

**Issue by fix** [meteor-useraccounts/core#584]
When enabling recaptcha, if you register, click on recaptcha and validate the form BEFORE the recatcha has finished the processing, it raises an error, which is sensible but bad UX.

What about enabling a timeout or waiting a for a callback from recaptcha (if availbale)?

**Comment by splendido** [comment]
Not the best ever solution but simply ignoring the submit event in case recaptcha validation is not complete should provide a better UX.
