### ISSUE TITLE
Thrown Errors go to console, but not to register form

### ISSUE THREAD

**Issue by KHam0425** [meteor-useraccounts/core#593]
preSignUpHook: function(password, info) {
    if (info.profile.role === "student" && typeof(info.email) !==
      'undefined') {
      throw new Error('Students MUST NOT enter email addresses when creating an account'
      );
    }
    if (info.profile.role === "instructor" && !info.userName) {
      throw new Error('Instructors MUST register using username and a valid email address'
      )
    }

...

    onSubmitHook: function(error, state) {
    if (!error) {
    //blah blah blah do stuff for legit registrations
    }else{
        AccountsTemplates.state.form.get(error);
    }

I would assume that an error thrown in the preSignUpHook would carry into the onSubmitHook, since that is where error handling seems to occur, but is there a different way to display custom error messages letting users know how to fix their registration problems?  In my case, I don't want students entering their email addresses, for privacy reasons of minors, when we can use their usernames to communicate.  However, instructors need to have a student-facing username, and a private email address for admin -> instructor communication.  Anything obvious I'm doing wrong?  I'm willing to provide more code, but I thought it might be able to be handled by looking over what I've provided.

I am using useraccounts-semantic-ui and iron-router, but I'm not routing anything until I've validated correct user registration.  As you can see, I'm also writing user roles into the user.profile using alanning:roles, but that's not relevant other than those roles would be the triggers for thrown errors.

I've looked over the different error issues and followed the breadcrumbs, but I'm not finding an issue like this one where the intent it to handle the error from a preSignUpHook validation in the onSubmitHook.  Is it a failure to call next with the error contained in it (grasping for straws, honestly).

**Comment by splendido** [comment]
hello @KHam0425,
I hope to be able to provide a more comprehensive validation system with v2.0 but for now we have to use what we have...

In your case, to give feedback to the user I'd say it should be enough to manually set an error on the form just before throwing the error to cancel the submit operation:

```javascript
preSignUpHook: function(password, info) {
    if (/* condition */) {
      var errMsg = 'Students MUST NOT enter email addresses when creating an account';
      AccountsTemplates.setDisabled(false);
      AccountsTemplates.state.form.set("error", [errMsg]);
      throw new Error(errMsg);
    }
  },
```

alternativaly you could set the error on the email input field like this:

```javascript
preSignUpHook: function(password, info) {
    if (/* condition */) {
      var emailField = AccountsTemplates.getField("email");
      var errMsg = 'Students MUST NOT enter email addresses when creating an account';
      AccountsTemplates.setDisabled(false);
      emailField.setError(errMsg);
      throw new Error(errMsg);
    }
  },
```

Let me know if you need more pointers!
