### ISSUE TITLE
Adding custom classes to atNavButton

### ISSUE THREAD

**Issue by moshemo** [meteor-useraccounts/core#595]
Hi,

I am using useraccounts:semantic-ui and I would like to add a class of primary to the login/logout button.  Any idea how I can do this? 

Thanks,

Moshe

**Comment by splendido** [comment]
Hi @moshemo,
the best way is to override the template as explained in #212 

so, basically:

run
```shell
meteor add aldeed:template-extension
```

add your own custom template
```html
<template name="myAtNavButton">
  <div class="item">
    <div class="ui primary button" id="at-nav-button">{{text}}</div>
  </div>
</template>
```

and require it to be used in place of the original one:
```javascript
Template.myAtNavButton.replaces("atNavButton");
```

**Comment by mozfet** [comment]
Hi @splendido,

I'm trying this approach, the markup works and the button looks nice, but it does nothing when clicked on...

Any ideas how to fix this?

Thanks!

**Comment by mozfet** [comment]
No worries, I figured it out: I accidentally left out the id="at-nav-button" from my extension, so the atNavButton helpers was not seeing the event as coming from my button.
