### ISSUE TITLE
Error: grecaptcha is not defined 

### ISSUE THREAD

**Issue by cesarve77** [meteor-useraccounts/core#600]
Hello, First thanks for this great package.
and second sorry for my english

I have this issue:

When I try to singup with a already register email i got

```
ReferenceError: grecaptcha is not defined
```
no matter if option showReCaptcha: false,

thanks for your attention.

**Comment by cesarve77** [comment]
I made a 

```
$ meteor update
````
and problem solved

**Comment by Levino** [comment]
Related #599
