### ISSUE TITLE
Feature request: Hook for transparent logins

### ISSUE THREAD

**Issue by derwaldgeist** [meteor-useraccounts/core#604]
My app is internationalized using the ```tap:i18n package```. I've also set-up a user preference, so the app will show up in the correct language if the user logs in. I placed this logic in an onSubmit() hook of the useraccounts package.

This works if the user logs in via the login form, but it doesn't work if the user is logged in transparently, using a login token. So after a hot-code reload, for instance, my app always shows up in its default language, i.e. English.

It would be nice to have a hook that is not only fired on the submit of the login form, but also when the user is transparently logged in based on a user token.

I've also tried ```Accounts.onLogin()```, but this behaves just like the ```onSubmit()``` handler.

**Comment by splendido** [comment]
@derwaldgeist I'd say the best you can do is something like this (on the client side...):

```javascript
  Tracker.autorun(function(){
    var user = Meteor.user();
    if (user) {
      console.log('Now user ' + user._id + ' is logged in...');
      // get language here...
      // var lang = ...

      // check whether a different language should be set
      // var currLang = ...
      // if (lang !== currLang) {
      //   // set new language here...
      // }
    }
    }
    else {
      console.log('No user logged in!');
      
      // Possibly set default language here (if different from the current one)
    }
  });
```

it should work in any case, independently of hot-reloads or the packages you're using the deal with login/logout operations...

Let me know if this works for you.

**Comment by derwaldgeist** [comment]
Hi @splendido, thanks for your reply! Funny thing is: this is exactly the workaround I implemented yesterday :-) It worked, but as you said, the autorun is triggered on each change of the user object, which happens quite often in my app. Good idea to execute a Mongo query for specific properties, will try that.

**Comment by splendido** [comment]
```javascript
var lastUserId;

Tracker.autorun(function(){
  var userId = Meteor.userId();
  if (userId && userId !== lastUserId) {
    console.log('User ' + userId + ' just logged in!');

    // get user object here
    var user = Meteor.users.findOne(userId);

    // get preferred user language here...
    var lang = (user.profile && user.profile.lang) || 'en';

    // check whether a different language should be set
    var currLang = TAPi18n.getLanguage();
    if (lang !== currLang) {
      // set new language here...
      TAPi18n.setLanguage(lang);
    }
  }
  else {
    console.log('No user logged in!');

    // Possibly set default language here (if different from the current one)
  }

  lastUserId = userId;
});
```

this should be a working example

**Comment by cocaux** [comment]
Hi, 

`user.profile.lang` is undefined for me, is that normal ?

Many thanks for your help
