### ISSUE TITLE
AccountsTemplates.getState() didn't work

### ISSUE THREAD

**Issue by gVolop** [meteor-useraccounts/core#608]
on Accounts.onCreateUser i call to another function, and it need to know if current execution has called by onCreateUser. 
i'm try AccountsTemplates.getState() and get this:
TypeError: Object [object Object] has no method 'getState'
maybe it not available on server side?

and another problem is that on client it's always returns the last state, and it never returned 'hide'.

**Comment by splendido** [comment]
`AccountsTemplates.getState` is available on the client side only.
Moreover from inside `Accounts.onCreateUser` all the actions generated from AccountsTemplates are already over and there's no way to get additional info.

For your last question: the `hide` state is never set by current operation flows, but you can set it manually in case you need (for any reason) to temporarly make the `atForm` template disappear.

What are you trying to achieve?
