### ISSUE TITLE
Verify email does not send after deployment: how to set from field

### ISSUE THREAD

**Issue by tdmoneybanks** [meteor-useraccounts/core#609]
I am trying to send emails from my deployed app (at digital ocean) via Mandrill and the willio:mandrill package. After deployment, I am able to send an email from my app using the Mandrill API 
`
Mandrill.messages.send({
message: {
"text": "Greetings from XBdash.com!",
"from_email": "keith@xbdash.com",
"from_name": "Keith - XBdash.com",
"subject": "App Started",
"to": [
{ email: "kguirao87@gmail.com", name: "Keith Guirao" }
]
}
}, function( error, response ) {
if ( error ) {
console.log( error );
} else {
console.log( response );
}
});
`
This email sends so I know I have my MAIL_URL set and am able to access my mandrill account from the application. However, when I try to get an account-tied email such as verify email or reset password, it does not send. I believe this is because I am unable/dont know how to set the "from" field of email like I am with the above code. However I imagine that it could also be because of something else so here is the code that alters what the verifyEmail email looks like.
`
Accounts.emailTemplates.verifyEmail.subject = function(user) {
    return 'Activate your XBdash account';
}
Accounts.emailTemplates.verifyEmail.html = function (user, url) {
    var result;
    try {
        result = Mandrill.templates.render({
            template_name: 'verify-email',
            template_content: [
                {
                    name: 'CONFIRMURL',
                    content: url
                },
                {
                    name: 'FNAME',
                    content: user.username
                }
            ],
            merge_vars: [
                {
                    name: 'CONFIRMURL',
                    content: url
                },
                {
                    name: 'FNAME',
                    content: user.username
                }
            ]
        });
    } catch (error) {
    	console.error('Error while rendering Mandrill template', error);
    }
    return result.data.html;
}
`
How would I be able to set the from field or otherwise fix the verify email through mandrill?
BTW, I was using this guide for help but still havent been able to fix the issue. https://themeteorchef.com/snippets/sending-email-with-mandrill/

**Comment by BrianJLennon** [comment]
I tto would really like to know how to get emails working with useraccounts boilerplate. Any help appreciated. Thanks.
