### ISSUE TITLE
How to customize password_again field ?

### ISSUE THREAD

**Issue by Rebolon** [meteor-useraccounts/core#633]
I'm trying to customize the password_agin field, but it's quite hard : 

if i do an AccountsTemplates.getField('password_again') it's not found neither on server, nor on client.
So it's impossible to customize placeholder or displayName...

**Comment by splendido** [comment]
Yeah, it doesn't exist from the beginning.
But if you add it beforehand you should get what you want.

```javascript
AccountsTemplates.addField({
    _id: 'password_again',
    type: 'password',
    /* etc etc. */
});
```

[here](https://github.com/meteor-useraccounts/core/blob/4f2d4067e7e4ee6146de9692ec4699c9580068e7/lib/client.js#L143-L158) are the lines where the default configuration is set.
