### ISSUE TITLE
Redirect on Verify Email not working

### ISSUE THREAD

**Issue by kartikTT** [meteor-useraccounts/core#638]
I'm getting the following error when I click the verify link in the verification email:

`Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]`

I can access the Meteor.user() object in the console but my redirect function does not run (nothing gets logged in console). Here's the test function I'm trying to run on verifying email:

```
AccountsTemplates.configureRoute('verifyEmail',{
	redirect: function(){
		console.log('verified email');
	}
});
```

Any thoughts on how to get the redirect function running?

**Comment by MichaelJCole** [comment]
@kartikTT here's what I'm using:

```
AccountsTemplates.configureRoute('verifyEmail', {
  redirect: function(){
    var user = Meteor.user();
    if (user) {
      Meteor.call('recalculateSomeStuff');
      Router.go('home');
    }
  }
});
```

**Comment by kartikTT** [comment]
@MichaelJCole thanks for the note. I'm actually not getting the 403 anymore,but my redirect function still isn't running at all.

Changing the redirectTimeout doesn't help either. Not sure what could be preventing the redirect from being executed?

**Comment by kartikTT** [comment]
Update: the redirect is invoked if I set enforceEmailVerification: false. Assuming its because of [this line](https://github.com/meteor-useraccounts/core/blob/0d0b83e41a5812381617bdb95a72c94c822ef8e1/lib/templates_helpers/at_pwd_form.js#L233) as referenced in #578.

I definitely need the enforceEmailVerfication functionality - there must be a way to both redirect and keep this enabled?

**Comment by kartikTT** [comment]
Solved this by adding "atVerifyEmail" to my array of routes exempted from "ensureSignedIn".

```
Router.plugin('ensureSignedIn',{
	except:[ 'atSignIn', 'atSignUp', 'atForgotPassword', 'atVerifyEmail']
})
```

Maybe documenting this could help others?
