### ISSUE TITLE
enforceEmailVerification and case-sensitive

### ISSUE THREAD

**Issue by AlexanderPD** [meteor-useraccounts/core#654]
I have this scenario:
- i have set enforceEmailVerification and sendVerificationEmail to True
- user sign up from his computer with mail "foo@bar.com" and complete registration using the confirmation mail
- everything is working using the mail foo@bar.com
- user try to login from his phone, but his smartphone makes the first letter uppercase, so the user type "Foo@bar.com"
- user get the error "mail not verified"

Setting enforceEmailVerification to false i have no problem at all, but i want the user to confirm his mail. I'm not sure if i'm doing something wrong or if this is an actual bug, any idea on how to fix it?

**Comment by wildhart** [comment]
I get this exact same problem.  I suspect the problem is with this code in core/lib/server.js starting at line 125:

````
      var ok = true;
      var loginEmail = attempt.methodArguments[0].user.email;
      if (loginEmail) {
        var email = _.filter(user.emails, function(obj) {
          return obj.address === loginEmail;   // THIS NEEDS TO BE A CASE INSENSITIVE COMPARISON
        });
        if (!email.length || !email[0].verified) {
          ok = false;
        }
      } 
````

I don't know how to replace useraccounts:core with my own version to test this though.  Can anyone help?
