### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by cdolek** [meteor-useraccounts/core#679]
http://useraccounts-bootstrap.meteor.com/
http://useraccounts-foundation.meteor.com/
http://useraccounts-ionic.meteor.com/
http://useraccounts-materialize.meteor.com/
http://useraccounts-polymer.meteor.com/
http://useraccounts-ratchet.meteor.com/
http://useraccounts-semantic-ui.meteor.com/

**Comment by fafournier** [comment]
duplicate of #660
