### ISSUE TITLE
postSignUpHook

### ISSUE THREAD

**Issue by frankapimenta** [meteor-useraccounts/core#681]
defined on imports/startup/client/accounts_config.js.

```javascript```
AccountsTemplates.configure({
  postSignUpHook: (userId, info) => {
    console.log(userId, info); // never gets printed on meteor console
  }
});

```

I think the hook is not being triggered.
I have:
useraccounts:core@1.14.2
useraccounts:flow-routing@1.14.2

**Comment by frankapimenta** [comment]
For whomever has this issue notice that this hook (server side hook) must be defined in a server side file. 
If you define it in a client side file (along with other configs) it is not going to be triggered.
I thought that it could be defined in the client side that then the package would run it on the server side but it does not happen.

**Comment by spacemunkay** [comment]
Or in my case, I didn't realize that it had already been defined in another file, and thus my new configuration setting was getting overridden.
