### ISSUE TITLE
How to change fields order?

### ISSUE THREAD

**Issue by Salketer** [meteor-useraccounts/core#727]
Hello,

I have tried to ask for the user's first and last name before asking for their e-mail, to do so I removed the email field and added it back after the other fields.

This worked, but the problem is that the email field lost all its defaults, I need to fetch the regexp to test the email validity and so on...

Is there a way to simply move the fields? Or fetch the current field setup before removing it so I can add the same one again?

**Comment by MichaelJCole** [comment]
I got this code pattern from another issue.  Give it a try:

```
var email = AccountsTemplates.removeField('email');
var password = AccountsTemplates.removeField('password');
AccountsTemplates.addFields([{
    _id: 'name',
    type: 'text',
    displayName: 'First and Last Name',
    required: true,
    minLength: 5,
    re: /^[a-zA-Z0-9-' ]{2,50}$/, // see 2_Users.js
    errStr: 'Please enter your first then last name',
}, email, password]);
```

**Comment by Salketer** [comment]
Thank you, works like a charm. The guide is not very explicit on the fact that the removeField method actually returns the field.
