### ISSUE TITLE
Configuring emails sent?

### ISSUE THREAD

**Issue by Salketer** [meteor-useraccounts/core#734]
Hello,

I could not find the right way to do it in the guide... I am looking to configure the content of the mails (I'm sure I already read about that, but can't retrieve it) and I'd also like to be able to configure sender's info and if possible add custom mail headers. If it is at all possible, I'd really love to know how.

Thank you.

**Comment by guidouil** [comment]
You can find all the details here http://docs.meteor.com/api/passwords.html#Accounts-emailTemplates

**Comment by Salketer** [comment]
Thank you! It wasn't clear that it was using the underlying Accounts for
that.

2017-03-09 22:12 GMT+01:00 Guillaume Darbonne <notifications@github.com>:
