### ISSUE TITLE
Passing query parameters to sign up route

### ISSUE THREAD

**Issue by geritol** [meteor-useraccounts/core#95]
Just a question. When do you plan to add checkbox support for reg. field?
- one more. Maybe it would be nice to be able to add login parameters via client javascript. I mean to add data to user 'profile' by some code that is is not in the reg. template. For example adding user type (user.type) to a profile based on whether the user user registers on /register?u=admin or register?u=mod Note this is just an example.

**Comment by elie222** [comment]
@splendido is there a way to run your example without adding reg_code to the profile? Or does this have to be overriden in onCreateUser?

**Comment by elie222** [comment]
@splendido the following pattern works with the query in the url, but if the user switches page on the site, you lose the query url. Is there a simple way around this?
```
AccountsTemplates.addField({
    _id: 'reg_code',
    type: 'hidden'
});
```

**Comment by splendido** [comment]
At the moment there's no way to keep the query parameter within AccountsTemplates.
But you could try to set up another `onBeforeAction` hook to extrac it and put it into a session variable or something similar...

As for your previous comment, yes: I think `onCreateUser` is the place where to deal with the registration code and possibly the right place to remove it from the user object in case you don't need it later on

**Comment by acomito** [comment]
I want to add a document (not to user collection) when a user account is created.

The user fills out a form, and I store the info in a session variable. At the end of the form, they fill out email and password. This is the atForm which calls onCreateUser.... I can't figure out how to pass the session variable along so that I can insert the document once the user is created.

**Comment by elie222** [comment]
You could store the session variable in a hidden field of the signup form
