### ISSUE TITLE
Signups forbidden when using together with accounts-ui

### ISSUE THREAD

**Issue by riaan53** [meteor-useraccounts/core#96]
Hi!

This package is evolving nicely! 

I need to use accounts-ui together with accounts-templates-bootstrap. Everything works except when I create a new account in accounts-ui I get a 'Signups forbidden' error.

I have set `forbidClientAccountCreation: false` in the config.

Any suggestions?

Regards,
Riaan

**Comment by v1nay** [comment]
I was getting the same error because of conflicting packages. In my case, had to remove  `useraccounts:bootstrap` package so that `accounts-ui` works. 

I use `mizzao:bootstrap-3` for styling.

**Comment by thomasspiesser** [comment]
I need to display sign-up and sign-in side by side, so I need my custom sign-up form. can i call `ATCreateUserServer` from the client create new users? otherwise, how do reset `forbidClientAccountCreation` to false?

**Comment by brylie** [comment]
@thomasspiesser you may need to open a separate issue for this support request. Are you also using the **accounts-ui** package?

**Comment by thomasspiesser** [comment]
@brylie no, i'm not using accounts-ui so far. only useraccounts: core and bootstrap.

**Comment by reduxdj** [comment]
Signups forbidden
+1 - here are my packages:

useraccounts:core
accounts-base
accounts-password
accounts-facebook
accounts-ui

Ugh this hurtz kittenz.

**Comment by brylie** [comment]
@reduxdj remove accounts-ui

**Comment by reduxdj** [comment]
I removed accounts-ui, and I am still getting signups forbidden, and this is set to  forbidClientAccountCreation: false

**Comment by reduxdj** [comment]
Also, I removed this package and the same thing happens.

meteor remove useraccounts:bootstrap

Changes to your project's package version selections:

softwarerero:accounts-t9n  removed from your project
useraccounts:bootstrap     removed from your project
useraccounts:core          removed from your project

useraccounts:bootstrap: removed dependency
meteor add useraccounts:core

Changes to your project's package version selections:

softwarerero:accounts-t9n  added, version 1.0.9
useraccounts:core          added, version 1.11.1

Still, signups forbidden, using meteor admin too...

meteor-platform
coffeescript
reduxfj:react-meteor-cjsx
stylus
less
email
aldeed:autoform@5.1.2
alanning:roles
aldeed:collection2
aldeed:simple-schema
fortawesome:fontawesome
raix:handlebar-helpers
cfs:standard-packages
cfs:gridfs
aldeed:template-extension
cfs:graphicsmagick
yogiben:helpers
iron:router
yogiben:autoform-modals
yogiben:pretty-email
yogiben:autoform-file
yogiben:autoform-map
multiply:iron-router-progress
manuelschoebel:ms-seo
spiderable
jparker:gravatar
tap:i18n
service-configuration
yogiben:mixpanel
juliancwirko:s-alert
juliancwirko:s-alert-stackslide
momentjs:moment
zimme:iron-router-active
user-thumbs
comments
favorites
dburles:collection-helpers
reywood:publish-composite
natestrauser:animate-css
meteorhacks:subs-manager
fastclick
notifications
yogiben:admin
timmyg:wow
tsega:skrollr
utilities:avatar
jquery
ian:accounts-ui-bootstrap-3
twbs:bootstrap
accounts-facebook
accounts-password
useraccounts:core

**Comment by splendido** [comment]
could it be some other pacakge among your ones setting is to true?
I don't think this is a problem with UserAccounts...

**Comment by rockodragon99** [comment]
Having the same problem, which must have been introduced by something I added, because it used to work. Was there any resolution?
I'm using:
accounts-password
alanning:roles
aldeed:autoform
aldeed:collection2
aldeed:simple-schema
anti:fake
cmather:handlebars-server
cunneen:mailgun
dburles:collection-helpers
dburles:factory
iron:router
less
matb33:collection-hooks
meteor-platform
momentjs:moment
mrt:underscore-string-latest
msavin:mongol
reywood:publish-composite
useraccounts:bootstrap
useraccounts:core
useraccounts:iron-routing
yasinuslu:blaze-meta
zimme:active-route

Thanks

**Comment by ignacy130** [comment]
Same thing: cannot register and login from main app, only through /admin. I'm working on Microscope clone. It worked some days ago :(

**Comment by MichaelJCole** [comment]
Hey, I'm running into this, and not sure what direction to go.

I have 4 projects as microservices.  They all share some code. Some of that code is UserAccounts which is super helpful.

One of those microservices needs a custom sign-up/sign-in form.  Email, password, signup, signin.  That's it.  

I'm getting this error with my custom form when I call `Accounts.createUser()`, like described above.

What's the simplest thing that could possibly work?

I tried switching it for `Meteor.call('ATCreateUserServer', {})` but started getting 500 errors.

Is there an easy way to either switch `Accounts.createUser()` back on?  
I get "Signups forbidden" even with this:
```
AccountsTemplates.configure({
  forbidClientAccountCreation: false,
```
Or, what should I pass to `ATCreateUserServer`?
Or, how can what's the best way to customize the `ATForm` template? 

Thanks!

Mike

**Comment by MichaelJCole** [comment]
Hey, I think I got a version of this working.  Maybe not the best way to do it, suggestions welcome :-)

```
Template.connectFormAccount.events({
  'click .step-button-register': function(e, template) {
    template.error.set(false);
    var email = $('#formEmail').val();
    var password = $('#formPassword').val(); 
    
    Meteor.call('ATCreateUserServer', {
      email: email,
      password: Accounts._hashPassword(password),
      profile: {},  // This is important to prevent 500
    }, function(err) {
      // ATCreateUserServer callback
      if (err) return template.error.set(Helpers.decodeLoginError(err));

      Meteor.loginWithPassword(email, password, function(err) {
        // loginWithPassword callback
        if (err) return template.error.set(Helpers.decodeLoginError(err));
        Helpers.connectForm.setStep('account', 'next');
      });
    });
  },
'click .step-button-signin': function(e, template) {
    template.error.set(false);
    Meteor.loginWithPassword(
      $('#formEmail').val(),
      $('#formPassword').val(),
      function(err) {
        if (err) return template.error.set(Helpers.decodeLoginError(err));
        Helpers.connectForm.setStep('account', 'next');
      }
    );
  },
});
```
This let me have a custom sign-in/sign-up form and use the `{{> loginButtons}}` in the navbar.  The reason to have both packages (useraccounts and ian:accounts-ui-bootstrap-3) is that:

  * useraccounts is used by my other microservices that share code.  
  * ian:accounts-ui-bootstrap-3 has a nice {{> loginButtons }} with a nice simple change password.
  * I needed a custom form anyways.

Hope this helps someone else :-)

**Comment by Twisterking** [comment]
So wait a second ... There is no way to use `Accounts.createUser()` on the **client** while using meteor-useraccounts? sorry but what the f? I tried setting `forbidClientAccountCreation: false` and all that but I always get the `Signups forbidden 403 Error`. There has to be some way to use this package (using the unstyled version) while also being able to use the standard `Accounts.createUser()` method of Meteor if I want to?!

**Comment by thomasspiesser** [comment]
@Twisterking please mind your language!

You can use `Accounts._hashPassword()` to prevent plain text password transfer.

**Comment by Twisterking** [comment]
Sorry about that!
Well alright but what do I do from there? I then have a SHA256 encrypted password, but I need the actual plain text password again to feed it into `Accounts.createUser()` on the **server** right? Or can I just use the whole object which is returned by `Accounts._hashPassword()` and use it for the `password` key in `options` in `Accounts.createUser(options)`?

**Comment by thomasspiesser** [comment]
Exactly!

**Comment by tdotholla** [comment]
So are we at a consensus here? the magic reproduction of the `[403]` for forbidden users is: 
if both packages are installed: `useraccounts` & `accounts-ui` or `accounts-core` packages? 

i'm still wrapping it in a server method and calling it from the client, but still getting the forbidden. 
all of my `'forbidClientRegistration'` is set to `false`.

**Comment by msj121** [comment]
Wait why can't I use useraccounts:bootstrap with this functionality? Aren't they meant to work together?

**Comment by tdotholla** [comment]
try removing the `accounts-ui` package and try again... 
my packages: 
`
fourseven:scss
accounts-password
accounts-base
http
iron:router
orionjs:core
materialize:materialize
orionjs:materialize
nicolaslopezj:roles
useraccounts:iron-routing
useraccounts:core
simple:reactive-method
aldeed:autoform
accounts-facebook
accounts-google
nicolaslopezj:tabular-materialize
useraccounts:materialize
orionjs:image-attribute
mdg:geolocation
orionjs:file-attribute
vsivsi:orion-file-collection`

**Comment by msj121** [comment]
The following is my list of packages... I don't have accounts-ui as far as I can tell:

```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
tracker                 # Meteor's client-side reactive programming library

jquery

es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

iron:router
ejson
accounts-password
email

random
momentjs:moment
aldeed:tabular
simple:reactive-method
reactive-var
alanning:roles
standard-minifier-css
standard-minifier-js
tomi:upload-server
tomi:upload-jquery
#accounts-facebook
accounts-google
#accounts-twitter
sergeyt:typeahead
useraccounts:bootstrap
useraccounts:iron-routing
fourseven:scss
twbs:bootstrap
matteodem:easy-search@=1.6.4
```

**Comment by thsowers** [comment]
@msj121 I had the same problem, but removing `useraccounts:iron-routing` worked for me. I think it was becuase `useraccounts:core` was attached to it

**Comment by msj121** [comment]
@thsowers Thanks, will try it. How did you replace all of the useful code?

**Comment by bevinhex** [comment]
Same thing here, these are some of my packages:
```
accounts-password@1.3.3
less@2.7.8
accounts-ui-unstyled
mdg:camera
benjick:webcam
session@1.1.7
nerdmed:camanjs
react-meteor-data
msavin:mongol
practicalmeteor:faker
useraccounts:core
useraccounts:bootstrap
```
login forbidden message

**Comment by bevinhex** [comment]
Guys, I solved it by putting following code in the root directory, meaning running these code for both server and client , think "forbidClientAccountCreation:false" is the main evil
```
let submitForm = function(error,state){
  console.log(error,state);
  if(!error){
    if(state==="signIn"){
      //login successful
      browserHistory.push('camera');
    }
    if(state==="signUp"){
      //register successful
      browserHistory.push('camera');
    }
  }
};
AccountsTemplates.configure({
  forbidClientAccountCreation:false,
  overrideLoginErrors:false,
  negativeValidation: true,
  positiveValidation: true,
  showValidating:true,
  onSubmitHook:submitForm,
  homeRoutePath:'/camera',
});
```

**Comment by ifalldev** [comment]
Hi, I had the same issue and nothing worked for me.

My way to solve this was that I put the `Accounts.createUser()` wrapped in a `Meteor.methods` which I call when the form is submitted.

Fixed it for me =)

**Comment by MastaBaba** [comment]
Had the same issue, suddenly.
Essentially, I removed 'accounts-password' then added it again. This seemingly solved the problem.
